export const ERROR_CODES = {
  PROCESS_ERROR: "PROCESS_ERROR",
  TIMEOUT: "TIMEOUT",
  BUILD_FAILURE: "BUILD_FAILURE",
  TEST_FAILURE: "TEST_FAILURE",
  DATABASE_FAILURE: "DATABASE_FAILURE",
  REVIEW_FAILURE: "REVIEW_FAILURE",
  MODEL_ERROR: "MODEL_ERROR",
  PLAN_INVALID: "PLAN_INVALID",
  MAX_ITERATIONS: "MAX_ITERATIONS",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
