import type { ReactNode } from 'react';

export const metadata = {
  title: 'Web App',
  description: 'Generated by web-sub-agent',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
