INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('achieve', 'đạt được', '/əˈtʃiːv/', 'She achieved her IELTS goal.', 'education'),
  ('benefit', 'lợi ích', '/ˈbenɪfɪt/', 'Reading brings many benefits.', 'education'),
  ('pollution', 'sự ô nhiễm', '/pəˈluːʃn/', 'Air pollution is serious.', 'environment'),
  ('sustainable', 'bền vững', '/səˈsteɪnəbl/', 'We need sustainable energy.', 'environment'),
  ('efficient', 'hiệu quả', '/ɪˈfɪʃnt/', 'This method is very efficient.', 'technology'),
  ('innovation', 'sự đổi mới', '/ˌɪnəˈveɪʃn/', 'Innovation drives growth.', 'technology'),
  ('phenomenon', 'hiện tượng', '/fəˈnɒmɪnən/', 'A strange phenomenon occurred.', 'society'),
  ('diverse', 'đa dạng', '/daɪˈvɜːs/', 'A diverse community thrives.', 'society'),
  ('obesity', 'bệnh béo phì', '/əʊˈbiːsəti/', 'Obesity affects many children.', 'health'),
  ('nutritious', 'bổ dưỡng', '/nuːˈtrɪʃəs/', 'Eat nutritious food daily.', 'health'),
  ('dedicate', 'cống hiến', '/ˈdedɪkeɪt/', 'He dedicates time to study.', 'education'),
  ('curriculum', 'chương trình học', '/kəˈrɪkjələm/', 'A new curriculum was introduced.', 'education'),
  ('deforestation', 'nạn phá rừng', '/diːˌfɒrɪˈsteɪʃn/', 'Deforestation harms wildlife.', 'environment'),
  ('biodiversity', 'đa dạng sinh học', '/ˌbaɪəʊdaɪˈvɜːsəti/', 'Protect biodiversity now.', 'environment'),
  ('artificial', 'nhân tạo', '/ˌɑːtɪˈfɪʃl/', 'Artificial intelligence grows fast.', 'technology'),
  ('breakthrough', 'bước đột phá', '/ˈbreɪkθruː/', 'A breakthrough in science.', 'technology'),
  ('inequality', 'bất bình đẳng', '/ˌɪnɪˈkwɒləti/', 'Fight social inequality.', 'society'),
  ('urbanisation', 'đô thị hóa', '/ˌɜːbənaɪˈzeɪʃn/', 'Urbanisation is rapid.', 'society'),
  ('immunity', 'miễn dịch', '/ɪˈmjuːnəti/', 'Vaccines build immunity.', 'health'),
  ('therapy', 'trị liệu', '/ˈθerəpi/', 'Music therapy helps patients.', 'health'),
  ('fluent', 'trôi chảy', '/ˈfluːənt/', 'She speaks fluent English.', 'education'),
  ('accent', 'giọng', '/ˈæksənt/', 'He has a British accent.', 'education'),
  ('emit', 'thải ra', '/iˈmɪt/', 'Cars emit harmful gases.', 'environment'),
  ('climate', 'khí hậu', '/ˈklaɪmət/', 'Climate change is real.', 'environment'),
  ('gadget', 'thiết bị nhỏ', '/ˈɡædʒɪt/', 'A useful kitchen gadget.', 'technology'),
  ('algorithm', 'thuật toán', '/ˈælɡərɪðəm/', 'Learn basic algorithms.', 'technology'),
  ('poverty', 'nghèo đói', '/ˈpɒvəti/', 'End poverty by 2030.', 'society'),
  ('justice', 'công lý', '/ˈdʒʌstɪs/', 'Fight for justice.', 'society'),
  ('symptom', 'triệu chứng', '/ˈsɪmptəm/', 'Flu symptoms include fever.', 'health'),
  ('vaccine', 'vắc-xin', '/ˈvæksiːn/', 'Vaccines save lives.', 'health')
ON CONFLICT (en) DO NOTHING;
