INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('ability', 'khả năng', '/əˈbɪləti/', 'Her ability amazes everyone.', 'education'),
  ('achievement', 'thành tựu', '/əˈtʃiːvmənt/', 'Winning was a great achievement.', 'education'),
  ('academic', 'thuộc học thuật', '/ˌækəˈdemɪk/', 'She writes academic papers.', 'education'),
  ('admire', 'ngưỡng mộ', '/ədˈmaɪə/', 'I admire his courage.', 'education'),
  ('admit', 'thừa nhận', '/ədˈmɪt/', 'He admitted the mistake.', 'education'),
  ('assignment', 'bài tập được giao', '/əˈsaɪnmənt/', 'Finish the assignment today.', 'education'),
  ('analyse', 'phân tích', '/ˈænəlaɪz/', 'Analyse the data carefully.', 'education'),
  ('arrange', 'sắp xếp', '/əˈreɪndʒ/', 'Arrange the books by topic.', 'education'),
  ('attend', 'tham dự', '/əˈtend/', 'She attends every class.', 'education'),
  ('attention', 'sự chú ý', '/əˈtenʃn/', 'Pay attention in class.', 'education'),
  ('award', 'giải thưởng', '/əˈwɔːd/', 'He won a science award.', 'education'),
  ('assessment', 'sự đánh giá', '/əˈsesmənt/', 'Exams are one form of assessment.', 'education'),
  ('assist', 'hỗ trợ', '/əˈsɪst/', 'Teachers assist slow learners.', 'education'),
  ('aspire', 'khao khát', '/əˈspaɪə/', 'She aspires to study abroad.', 'education'),
  ('attain', 'đạt được', '/əˈteɪn/', 'He attained high scores.', 'education'),
  ('admission', 'sự nhập học', '/ədˈmɪʃn/', 'Admission opens in May.', 'education'),
  ('absorb', 'hấp thụ', '/əbˈzɔːb/', 'Trees absorb carbon dioxide.', 'environment'),
  ('agriculture', 'nông nghiệp', '/ˈæɡrɪkʌltʃə/', 'Agriculture feeds the nation.', 'environment'),
  ('atmosphere', 'bầu khí quyển', '/ˈætməsfɪə/', 'Protect our atmosphere.', 'environment'),
  ('conserve', 'bảo tồn', '/kənˈsɜːv/', 'Conserve water every day.', 'environment'),
  ('cyclone', 'bão nhiệt đới', '/ˈsaɪkləʊn/', 'A cyclone hit the coast.', 'environment'),
  ('drought', 'hạn hán', '/draʊt/', 'Drought ruined the crops.', 'environment'),
  ('earthquake', 'động đất', '/ˈɜːθkweɪk/', 'The earthquake shook the city.', 'environment'),
  ('erosion', 'xói mòn', '/ɪˈrəʊʒn/', 'Prevent soil erosion now.', 'environment'),
  ('extinct', 'tuyệt chủng', '/ɪkˈstɪŋkt/', 'Dinosaurs are extinct.', 'environment'),
  ('flood', 'lũ lụt', '/flʌd/', 'Floods damaged many homes.', 'environment'),
  ('fog', 'sương mù', '/fɒɡ/', 'Dense fog delayed flights.', 'environment'),
  ('frost', 'sương giá', '/frɒst/', 'Frost covered the fields.', 'environment'),
  ('glacier', 'sông băng', '/ˈɡlæsiə/', 'Glaciers are melting fast.', 'environment'),
  ('habitat', 'môi trường sống', '/ˈhæbɪtæt/', 'Protect wildlife habitats.', 'environment'),
  ('harvest', 'vụ thu hoạch', '/ˈhɑːvɪst/', 'A rich rice harvest.', 'environment'),
  ('hurricane', 'bão lớn', '/ˈhʌrɪkən/', 'The hurricane passed quickly.', 'environment'),
  ('access', 'truy cập', '/ˈækses/', 'You need access to wifi.', 'technology'),
  ('activate', 'kích hoạt', '/ˈæktɪveɪt/', 'Activate your account first.', 'technology'),
  ('app', 'ứng dụng', '/æp/', 'Download this useful app.', 'technology'),
  ('advance', 'tiến bộ', '/ədˈvɑːns/', 'Great advance in medicine.', 'technology'),
  ('automatic', 'tự động', '/ˌɔːtəˈmætɪk/', 'The doors are automatic.', 'technology'),
  ('browser', 'trình duyệt', '/ˈbraʊzə/', 'Open a new browser tab.', 'technology'),
  ('bug', 'lỗi phần mềm', '/bʌɡ/', 'Fix every bug fast.', 'technology'),
  ('cable', 'dây cáp', '/ˈkeɪbl/', 'Check the cable connection.', 'technology'),
  ('database', 'cơ sở dữ liệu', '/ˈdeɪtəbeɪs/', 'Save it in a database.', 'technology'),
  ('desktop', 'máy tính để bàn', '/ˈdesktɒp/', 'Clean your desktop daily.', 'technology'),
  ('device', 'thiết bị', '/dɪˈvaɪs/', 'A useful smart device.', 'technology'),
  ('digital', 'kỹ thuật số', '/ˈdɪdʒɪtl/', 'Life in the digital age.', 'technology'),
  ('download', 'tải xuống', '/ˌdaʊnˈləʊd/', 'Download the app now.', 'technology'),
  ('file', 'tệp tin', '/faɪl/', 'Save the file first.', 'technology'),
  ('hacker', 'tin tặc', '/ˈhækə/', 'Beware of hackers online.', 'technology'),
  ('keyboard', 'bàn phím', '/ˈkiːbɔːd/', 'Type on the keyboard.', 'technology')
ON CONFLICT (en) DO NOTHING;
