INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('addiction', 'sự nghiện', '/əˈdɪkʃn/', 'Fight phone addiction early.', 'health'),
  ('ankle', 'mắt cá chân', '/ˈæŋkl/', 'She twisted her ankle.', 'health'),
  ('ambulance', 'xe cứu thương', '/ˈæmbjələns/', 'Call an ambulance fast.', 'health'),
  ('anxiety', 'sự lo âu', '/æŋˈzaɪəti/', 'Exams cause him anxiety.', 'health'),
  ('appetite', 'sự ngon miệng', '/ˈæpɪtaɪt/', 'Illness kills appetite.', 'health'),
  ('allergy', 'dị ứng', '/ˈælədʒi/', 'Pollen causes my allergy.', 'health'),
  ('bandage', 'băng gạc', '/ˈbændɪdʒ/', 'Put a bandage on it.', 'health'),
  ('cough', 'ho', '/kɒf/', 'A dry cough lasted weeks.', 'health'),
  ('deaf', 'điếc', '/def/', 'Loud noise can make you deaf.', 'health'),
  ('diagnosis', 'chẩn đoán', '/ˌdaɪəɡˈnəʊsɪs/', 'A correct early diagnosis.', 'health'),
  ('diet', 'chế độ ăn', '/ˈdaɪət/', 'A balanced diet matters.', 'health'),
  ('dizzy', 'chóng mặt', '/ˈdɪzi/', 'I feel dizzy today.', 'health'),
  ('dose', 'liều thuốc', '/dəʊs/', 'Take one dose daily.', 'health'),
  ('faint', 'ngất xỉu', '/feɪnt/', 'She fainted from heat.', 'health'),
  ('fever', 'sốt', '/ˈfiːvə/', 'Rest with a high fever.', 'health'),
  ('clinic', 'phòng khám', '/ˈklɪnɪk/', 'Visit the nearby clinic.', 'health'),
  ('abandon', 'từ bỏ', '/əˈbændən/', 'Never abandon your dreams.', 'society'),
  ('abolish', 'bãi bỏ', '/əˈbɒlɪʃ/', 'Abolish the old rule.', 'society'),
  ('abuse', 'lạm dụng', '/əˈbjuːs/', 'Stop drug abuse now.', 'society'),
  ('activist', 'nhà hoạt động', '/ˈæktɪvɪst/', 'An activist spoke loudly.', 'society'),
  ('adopt', 'thông qua', '/əˈdɒpt/', 'Adopt a new policy.', 'society'),
  ('aid', 'viện trợ', '/eɪd/', 'Send aid to victims.', 'society'),
  ('alliance', 'liên minh', '/əˈlaɪəns/', 'A strong alliance formed.', 'society'),
  ('amend', 'sửa đổi', '/əˈmend/', 'Amend the law soon.', 'society'),
  ('anger', 'cơn giận', '/ˈæŋɡə/', 'Control your anger well.', 'society'),
  ('anniversary', 'lễ kỷ niệm', '/ˌænɪˈvɜːsəri/', 'A tenth anniversary party.', 'society'),
  ('anticipate', 'dự đoán', '/ænˈtɪsɪpeɪt/', 'We anticipate problems.', 'society'),
  ('arrest', 'bắt giữ', '/əˈrest/', 'Police made an arrest.', 'society'),
  ('attitude', 'thái độ', '/ˈætɪtjuːd/', 'A positive attitude wins.', 'society'),
  ('audience', 'khán giả', '/ˈɔːdiəns/', 'A large audience clapped.', 'society'),
  ('authority', 'chính quyền', '/ɔːˈθɒrəti/', 'Respect local authority.', 'society'),
  ('census', 'điều tra dân số', '/ˈsensəs/', 'A census runs each decade.', 'society'),
  ('absolute', 'tuyệt đối', '/ˈæbsəluːt/', 'I have absolute trust.', 'general'),
  ('accelerate', 'tăng tốc', '/əkˈseləreɪt/', 'The car began to accelerate.', 'general'),
  ('accept', 'chấp nhận', '/əkˈsept/', 'Accept the truth bravely.', 'general'),
  ('accident', 'tai nạn', '/ˈæksɪdənt/', 'A car accident happened.', 'general'),
  ('accommodate', 'cung cấp chỗ ở', '/əˈkɒmədeɪt/', 'Hotels accommodate guests.', 'general'),
  ('accompany', 'đi cùng', '/əˈkʌmpəni/', 'She accompanied her son.', 'general'),
  ('accomplish', 'hoàn thành', '/əˈkʌmplɪʃ/', 'We accomplished the task.', 'general'),
  ('accurate', 'chính xác', '/ˈækjərət/', 'An accurate report matters.', 'general'),
  ('adapt', 'thích nghi', '/əˈdæpt/', 'Adapt to the new school.', 'general'),
  ('adventure', 'chuyến phiêu lưu', '/ədˈventʃə/', 'A bold adventure awaits.', 'general'),
  ('advice', 'lời khuyên', '/ədˈvaɪs/', 'Take my advice please.', 'general'),
  ('advise', 'khuyên', '/ədˈvaɪz/', 'I advise you to rest.', 'general'),
  ('affect', 'ảnh hưởng', '/əˈfekt/', 'Smoking affects health.', 'general'),
  ('afford', 'đủ khả năng chi trả', '/əˈfɔːd/', 'We cannot afford a car.', 'general'),
  ('agree', 'đồng ý', '/əˈɡriː/', 'I agree with you.', 'general'),
  ('allow', 'cho phép', '/əˈlaʊ/', 'They allow pets inside.', 'general')
ON CONFLICT (en) DO NOTHING;
