INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('semester', 'học kỳ', '/sɪˈmestə/', 'A new semester begins soon.', 'education'),
  ('scholarship', 'học bổng', '/ˈskɒləʃɪp/', 'She won a full scholarship.', 'education'),
  ('lecture', 'bài giảng', '/ˈlektʃə/', 'The lecture lasted one hour.', 'education'),
  ('seminar', 'hội thảo', '/ˈsemɪnɑː/', 'Join our weekend seminar.', 'education'),
  ('thesis', 'luận văn', '/ˈθiːsɪs/', 'He defends his thesis today.', 'education'),
  ('diploma', 'bằng cấp', '/dɪˈpləʊmə/', 'A diploma opens many doors.', 'education'),
  ('dormitory', 'ký túc xá', '/ˈdɔːmətri/', 'Life in the dormitory is fun.', 'education'),
  ('examiner', 'giám khảo', '/ɪɡˈzæmɪnə/', 'The examiner smiled kindly.', 'education'),
  ('cheat', 'gian lận', '/tʃiːt/', 'Never cheat in exams.', 'education'),
  ('memorize', 'ghi nhớ', '/ˈmeməraɪz/', 'Memorize ten words daily.', 'education'),
  ('revise', 'ôn tập', '/rɪˈvaɪz/', 'Revise before the test.', 'education'),
  ('tutor', 'gia sư', '/ˈtjuːtə/', 'A tutor helps after school.', 'education'),
  ('faculty', 'khoa', '/ˈfækəlti/', 'She joined the law faculty.', 'education'),
  ('campus', 'khuôn viên trường', '/ˈkæmpəs/', 'A green peaceful campus.', 'education'),
  ('librarian', 'thủ thư', '/laɪˈbreəriən/', 'Ask the kind librarian.', 'education'),
  ('principal', 'hiệu trưởng', '/ˈprɪnsəpl/', 'Our principal is strict.', 'education'),
  ('graduate', 'tốt nghiệp', '/ˈɡrædʒuət/', 'They graduate in June.', 'education'),
  ('enroll', 'ghi danh', '/ɪnˈrəʊl/', 'Enroll before September ends.', 'education'),
  ('suspend', 'đình chỉ', '/səˈspend/', 'Late fees suspend accounts.', 'education'),
  ('expel', 'đuổi học', '/ɪkˈspel/', 'Cheating can expel students.', 'education'),
  ('plagiarism', 'đạo văn', '/ˈpleɪdʒərɪzəm/', 'Plagiarism brings zero marks.', 'education'),
  ('deadline', 'hạn chót', '/ˈdedlaɪn/', 'Meet every deadline early.', 'education'),
  ('textbook', 'sách giáo khoa', '/ˈtekstbʊk/', 'Open your textbook now.', 'education'),
  ('kindergarten', 'mẫu giáo', '/ˈkɪndəɡɑːtn/', 'Kids love kindergarten.', 'education'),
  ('dropout', 'bỏ học', '/ˈdrɒpaʊt/', 'Help dropouts return soon.', 'education'),
  ('honor', 'danh dự', '/ˈɒnə/', 'Graduate with great honor.', 'education'),
  ('avalanche', 'tuyết lở', '/ˈævəlɑːnʃ/', 'An avalanche blocked roads.', 'environment'),
  ('ash', 'tro', '/æʃ/', 'Volcanic ash covered roofs.', 'environment'),
  ('acre', 'mẫu đất', '/ˈeɪkə/', 'They own fifty acres.', 'environment'),
  ('acid', 'axit', '/ˈæsɪd/', 'Acid rain harms forests.', 'environment'),
  ('compost', 'phân ủ', '/ˈkɒmpɒst/', 'Compost all food waste.', 'environment'),
  ('crater', 'miệng núi lửa', '/ˈkreɪtə/', 'A deep ancient crater.', 'environment'),
  ('desert', 'sa mạc', '/ˈdezət/', 'Cross the hot desert.', 'environment'),
  ('dew', 'sương', '/djuː/', 'Morning dew still shines.', 'environment'),
  ('drizzle', 'mưa phùn', '/ˈdrɪzl/', 'Light drizzle cools streets.', 'environment'),
  ('dune', 'cồn cát', '/djuːn/', 'Climb the sandy dune.', 'environment'),
  ('ecosystem', 'hệ sinh thái', '/ˈiːkəʊsɪstəm/', 'Save each ecosystem now.', 'environment'),
  ('estuary', 'cửa sông', '/ˈestʃuəri/', 'Birds gather at estuaries.', 'environment'),
  ('fauna', 'động vật hoang dã', '/ˈfɔːnə/', 'Rich fauna needs shelter.', 'environment'),
  ('flora', 'thực vật', '/ˈflɔːrə/', 'Rare flora grows here.', 'environment'),
  ('fossil', 'hóa thạch', '/ˈfɒsl/', 'A fossil from dinosaurs.', 'environment'),
  ('geyser', 'mạch nước nóng', '/ˈɡiːzə/', 'A tall geyser erupts.', 'environment'),
  ('hail', 'mưa đá', '/heɪl/', 'Hail broke many windows.', 'environment'),
  ('humid', 'ẩm ướt', '/ˈhjuːmɪd/', 'Hot humid summer days.', 'environment'),
  ('iceberg', 'tảng băng trôi', '/ˈaɪsbɜːɡ/', 'An iceberg floats north.', 'environment'),
  ('lagoon', 'đầm phá', '/ləˈɡuːn/', 'Swim in blue lagoons.', 'environment'),
  ('landslide', 'sạt lở đất', '/ˈlændslaɪd/', 'Rain caused a landslide.', 'environment'),
  ('marsh', 'đầm lầy', '/mɑːʃ/', 'Frogs live in marshes.', 'environment'),
  ('meadow', 'đồng cỏ', '/ˈmedəʊ/', 'Cows graze the meadow.', 'environment'),
  ('oasis', 'ốc đảo', '/əʊˈeɪsɪs/', 'Rest at the oasis.', 'environment'),
  ('pebble', 'sỏi', '/ˈpebl/', 'Smooth pebbles line paths.', 'environment'),
  ('puddle', 'vũng nước', '/ˈpʌdl/', 'Jump over each puddle.', 'environment'),
  ('antenna', 'ăng-ten', '/ænˈtenə/', 'Fix the roof antenna.', 'technology'),
  ('backup', 'sao lưu', '/ˈbækʌp/', 'Back up files daily.', 'technology'),
  ('bandwidth', 'băng thông', '/ˈbændwɪdθ/', 'Upgrade your bandwidth now.', 'technology'),
  ('binary', 'nhị phân', '/ˈbaɪnəri/', 'Computers use binary code.', 'technology'),
  ('bookmark', 'đánh dấu trang', '/ˈbʊkmɑːk/', 'Bookmark this useful page.', 'technology'),
  ('boot', 'khởi động', '/buːt/', 'Boot the old laptop.', 'technology'),
  ('broadband', 'băng rộng', '/ˈbrɔːdbænd/', 'Fast broadband for all.', 'technology'),
  ('cache', 'bộ nhớ đệm', '/kæʃ/', 'Clear the cache now.', 'technology'),
  ('click', 'nhấp chuột', '/klɪk/', 'Click the blue button.', 'technology'),
  ('cloud', 'đám mây', '/klaʊd/', 'Store it in the cloud.', 'technology'),
  ('code', 'mã nguồn', '/kəʊd/', 'Learn to code early.', 'technology'),
  ('cookie', 'cookie trình duyệt', '/ˈkʊki/', 'Accept all site cookies.', 'technology'),
  ('cursor', 'con trỏ', '/ˈkɜːsə/', 'Move the mouse cursor.', 'technology'),
  ('cyber', 'mạng', '/ˈsaɪbə/', 'Cyber safety matters most.', 'technology'),
  ('debug', 'gỡ lỗi', '/ˌdiːˈbʌɡ/', 'Debug until tests pass.', 'technology'),
  ('delete', 'xóa bỏ', '/dɪˈliːt/', 'Delete old drafts monthly.', 'technology'),
  ('emoji', 'biểu tượng cảm xúc', '/iˈməʊdʒi/', 'Send a happy emoji.', 'technology'),
  ('encrypt', 'mã hóa', '/ɪnˈkrɪpt/', 'Encrypt private messages.', 'technology'),
  ('firewall', 'tường lửa', '/ˈfaɪəwɔːl/', 'A strong firewall protects.', 'technology'),
  ('folder', 'thư mục', '/ˈfəʊldə/', 'Make a new folder.', 'technology'),
  ('graphics', 'đồ họa', '/ˈɡræfɪks/', 'Sharp modern graphics.', 'technology'),
  ('hack', 'tấn công mạng', '/hæk/', 'Never hack any accounts.', 'technology'),
  ('homepage', 'trang chủ', '/ˈhəʊmpeɪdʒ/', 'Start at the homepage.', 'technology'),
  ('icon', 'biểu tượng', '/ˈaɪkɒn/', 'Tap the green icon.', 'technology'),
  ('inbox', 'hộp thư đến', '/ˈɪnbɒks/', 'Check your inbox daily.', 'technology'),
  ('joystick', 'cần điều khiển', '/ˈdʒɔɪstɪk/', 'Grab the game joystick.', 'technology')
ON CONFLICT (en) DO NOTHING;
