INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('ache', 'cơn đau', '/eɪk/', 'A dull tooth ache.', 'health'),
  ('bald', 'hói đầu', '/bɔːld/', 'He went bald early.', 'health'),
  ('blister', 'mụn nước', '/ˈblɪstə/', 'A blister from new shoes.', 'health'),
  ('bruise', 'vết bầm', '/bruːz/', 'A bruise after football.', 'health'),
  ('calorie', 'calo', '/ˈkæləri/', 'Count calories each meal.', 'health'),
  ('cavity', 'lỗ sâu răng', '/ˈkævəti/', 'A cavity needs filling.', 'health'),
  ('choke', 'nghẹn', '/tʃəʊk/', 'He choked on rice.', 'health'),
  ('cramp', 'chuột rút', '/kræmp/', 'Leg cramps at night.', 'health'),
  ('dehydrated', 'mất nước', '/ˌdiːhaɪˈdreɪtɪd/', 'Drink up when dehydrated.', 'health'),
  ('dentist', 'nha sĩ', '/ˈdentɪst/', 'Visit your dentist yearly.', 'health'),
  ('drowsy', 'buồn ngủ', '/ˈdraʊzi/', 'Long drives make me drowsy.', 'health'),
  ('epidemic', 'dịch bệnh', '/ˌepɪˈdemɪk/', 'Stop the flu epidemic.', 'health'),
  ('fatigue', 'mệt mỏi', '/fəˈtiːɡ/', 'Rest cures deep fatigue.', 'health'),
  ('fracture', 'gãy xương', '/ˈfræktʃə/', 'A fracture needs a cast.', 'health'),
  ('germ', 'vi trùng', '/dʒɜːm/', 'Wash away every germ.', 'health'),
  ('headache', 'đau đầu', '/ˈhedeɪk/', 'A loud headache today.', 'health'),
  ('heal', 'chữa lành', '/hiːl/', 'Time will heal wounds.', 'health'),
  ('hygiene', 'vệ sinh', '/ˈhaɪdʒiːn/', 'Good hygiene saves lives.', 'health'),
  ('inhale', 'hít vào', '/ɪnˈheɪl/', 'Inhale deeply then relax.', 'health'),
  ('insomnia', 'mất ngủ', '/ɪnˈsɒmniə/', 'Stress brings bad insomnia.', 'health'),
  ('itch', 'ngứa', '/ɪtʃ/', 'An itch after mosquito bites.', 'health'),
  ('joint', 'khớp xương', '/dʒɔɪnt/', 'Exercise keeps joints young.', 'health'),
  ('lump', 'cục u', '/lʌmp/', 'A small painful lump.', 'health'),
  ('migraine', 'đau nửa đầu', '/ˈmiːɡreɪn/', 'Dark rooms ease migraines.', 'health'),
  ('nausea', 'buồn nôn', '/ˈnɔːziə/', 'Pills may cause nausea.', 'health'),
  ('nurse', 'y tá', '/nɜːs/', 'A kind night nurse.', 'health'),
  ('ballot', 'bỏ phiếu', '/ˈbælət/', 'Cast a secret ballot.', 'society'),
  ('beggar', 'ăn xin', '/ˈbeɡə/', 'Help every beggar kindly.', 'society'),
  ('bribe', 'hối lộ', '/braɪb/', 'Refuse every bribe firmly.', 'society'),
  ('campaign', 'chiến dịch', '/kæmˈpeɪn/', 'A clean city campaign.', 'society'),
  ('ceremony', 'buổi lễ', '/ˈserəməni/', 'A grand opening ceremony.', 'society'),
  ('charity', 'từ thiện', '/ˈtʃærəti/', 'Give to local charity.', 'society'),
  ('citizen', 'công dân', '/ˈsɪtɪzn/', 'Every citizen can vote.', 'society'),
  ('civilian', 'thường dân', '/sɪˈvɪliən/', 'Protect hurt civilians.', 'society'),
  ('coalition', 'liên minh', '/ˌkəʊəˈlɪʃn/', 'A new ruling coalition.', 'society'),
  ('colony', 'thuộc địa', '/ˈkɒləni/', 'An old trade colony.', 'society'),
  ('custom', 'phong tục', '/ˈkʌstəm/', 'Respect local customs here.', 'society'),
  ('delegate', 'đại biểu', '/ˈdelɪɡət/', 'Each delegate gets one vote.', 'society'),
  ('democracy', 'dân chủ', '/dɪˈmɒkrəsi/', 'Build strong democracy.', 'society'),
  ('demonstrate', 'biểu tình', '/ˈdemənstreɪt/', 'Crowds demonstrate downtown.', 'society'),
  ('dictator', 'độc tài', '/dɪkˈteɪtə/', 'No one loves dictators.', 'society'),
  ('divorce', 'ly hôn', '/dɪˈvɔːs/', 'Divorce hurts the kids.', 'society'),
  ('donate', 'quyên góp', '/dəʊˈneɪt/', 'Donate books to schools.', 'society'),
  ('election', 'bầu cử', '/ɪˈlekʃn/', 'Fair free elections matter.', 'society'),
  ('embassy', 'đại sứ quán', '/ˈembəsi/', 'Call your home embassy.', 'society'),
  ('emigrate', 'di cư', '/ˈemɪɡreɪt/', 'Many emigrate for work.', 'society'),
  ('ethnic', 'dân tộc', '/ˈeθnɪk/', 'Many ethnic groups unite.', 'society'),
  ('exile', 'lưu đày', '/ˈeksaɪl/', 'Years in harsh exile.', 'society'),
  ('famine', 'nạn đói', '/ˈfæmɪn/', 'End world famine soon.', 'society'),
  ('forum', 'diễn đàn', '/ˈfɔːrəm/', 'Join the youth forum.', 'society'),
  ('gossip', 'tin đồn', '/ˈɡɒsɪp/', 'Ignore empty gossip daily.', 'society'),
  ('heritage', 'di sản', '/ˈherɪtɪdʒ/', 'Proud of our heritage.', 'society'),
  ('baggage', 'hành lý', '/ˈbæɡɪdʒ/', 'Claim your baggage here.', 'general'),
  ('balcony', 'ban công', '/ˈbælkəni/', 'Coffee on the balcony.', 'general'),
  ('bargain', 'mặc cả', '/ˈbɑːɡɪn/', 'Bargain at night markets.', 'general'),
  ('barrier', 'rào cản', '/ˈbæriə/', 'Break every language barrier.', 'general'),
  ('basic', 'cơ bản', '/ˈbeɪsɪk/', 'Master the basic steps.', 'general'),
  ('basis', 'cơ sở', '/ˈbeɪsɪs/', 'Trust forms the basis.', 'general'),
  ('basket', 'giỏ', '/ˈbɑːskɪt/', 'A basket full of fruit.', 'general'),
  ('battery', 'pin', '/ˈbætri/', 'Charge the phone battery.', 'general'),
  ('battle', 'trận chiến', '/ˈbætl/', 'A fierce final battle.', 'general'),
  ('behave', 'cư xử', '/bɪˈheɪv/', 'Behave well at school.', 'general'),
  ('beloved', 'yêu dấu', '/bɪˈlʌvd/', 'My beloved hometown river.', 'general'),
  ('bend', 'uốn cong', '/bend/', 'Bend the wire gently.', 'general'),
  ('betray', 'phản bội', '/bɪˈtreɪ/', 'Never betray close friends.', 'general'),
  ('beware', 'coi chừng', '/bɪˈweə/', 'Beware of pickpockets here.', 'general'),
  ('bias', 'thiên kiến', '/ˈbaɪəs/', 'News without any bias.', 'general'),
  ('bid', 'đấu giá', '/bɪd/', 'Bid for the old painting.', 'general'),
  ('bilingual', 'song ngữ', '/ˌbaɪˈlɪŋɡwəl/', 'Bilingual signs help tourists.', 'general'),
  ('bless', 'ban phước', '/bles/', 'Bless this new house.', 'general'),
  ('blind', 'mù', '/blaɪnd/', 'Love is sometimes blind.', 'general'),
  ('blink', 'chớp mắt', '/blɪŋk/', 'He did not even blink.', 'general'),
  ('blizzard', 'bão tuyết', '/ˈblɪzəd/', 'A blizzard closed schools.', 'general'),
  ('bloom', 'nở hoa', '/bluːm/', 'Roses bloom in May.', 'general'),
  ('blossom', 'hoa nở', '/ˈblɒsəm/', 'Spring blossoms smell sweet.', 'general'),
  ('bluff', 'hù dọa', '/blʌf/', 'Call his empty bluff.', 'general'),
  ('blunt', 'cùn', '/blʌnt/', 'A blunt knife cuts badly.', 'general'),
  ('blur', 'mờ nhòe', '/blɜː/', 'Tears blur my vision.', 'general')
ON CONFLICT (en) DO NOTHING;
