INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('meeting', 'cuộc họp', '/ˈmiːtɪŋ/', 'A long Monday meeting.', 'toeic'),
  ('schedule', 'lịch trình', '/ˈʃedjuːl/', 'Check the work schedule.', 'toeic'),
  ('appointment', 'cuộc hẹn', '/əˈpɔɪntmənt/', 'Book a dentist appointment.', 'toeic'),
  ('report', 'báo cáo', '/rɪˈpɔːt/', 'Send the weekly report.', 'toeic'),
  ('memo', 'ghi nhớ nội bộ', '/ˈmeməʊ/', 'Read every office memo.', 'toeic'),
  ('agenda', 'chương trình nghị sự', '/əˈdʒendə/', 'Set the meeting agenda.', 'toeic'),
  ('invoice', 'hóa đơn', '/ˈɪnvɔɪs/', 'Pay the late invoice.', 'toeic'),
  ('receipt', 'biên lai', '/rɪˈsiːt/', 'Keep every shop receipt.', 'toeic'),
  ('budget', 'ngân sách', '/ˈbʌdʒɪt/', 'Plan the yearly budget.', 'toeic'),
  ('proposal', 'đề xuất', '/prəˈpəʊzl/', 'Write a clear proposal.', 'toeic'),
  ('contract', 'hợp đồng', '/ˈkɒntrækt/', 'Sign the new contract.', 'toeic'),
  ('negotiate', 'đàm phán', '/nɪˈɡəʊʃieɪt/', 'Negotiate a better salary.', 'toeic'),
  ('minute', 'biên bản họp', '/ˈmɪnɪt/', 'Read the meeting minutes.', 'toeic'),
  ('chairman', 'chủ tịch', '/ˈtʃeəmən/', 'Our kind old chairman.', 'toeic'),
  ('colleague', 'đồng nghiệp', '/ˈkɒliːɡ/', 'Help new colleagues daily.', 'toeic'),
  ('department', 'phòng ban', '/dɪˈpɑːtmənt/', 'Join the sales department.', 'toeic'),
  ('branch', 'chi nhánh', '/brɑːntʃ/', 'Open a new branch office.', 'toeic'),
  ('headquarters', 'trụ sở chính', '/ˌhedˈkwɔːtəz/', 'Visit the headquarters soon.', 'toeic'),
  ('subsidiary', 'công ty con', '/səbˈsɪdiəri/', 'A small profitable subsidiary.', 'toeic'),
  ('merger', 'sáp nhập', '/ˈmɜːdʒə/', 'News of a big merger.', 'toeic'),
  ('acquisition', 'sự mua lại', '/ˌækwɪˈzɪʃn/', 'A costly new acquisition.', 'toeic'),
  ('takeover', 'tiếp quản', '/ˈteɪkəʊvə/', 'A friendly company takeover.', 'toeic'),
  ('stakeholder', 'bên liên quan', '/ˈsteɪkhəʊldə/', 'Meet every key stakeholder.', 'toeic'),
  ('shareholder', 'cổ đông', '/ˈʃeəhəʊldə/', 'Angry worried shareholders.', 'toeic'),
  ('revenue', 'doanh thu', '/ˈrevənjuː/', 'Rising yearly revenue.', 'toeic'),
  ('profit', 'lợi nhuận', '/ˈprɒfɪt/', 'Share the net profit.', 'toeic'),
  ('loss', 'thua lỗ', '/lɒs/', 'Report every loss fast.', 'toeic'),
  ('deficit', 'thâm hụt', '/ˈdefɪsɪt/', 'Cut the budget deficit.', 'toeic'),
  ('surplus', 'thặng dư', '/ˈsɜːpləs/', 'A record trade surplus.', 'toeic'),
  ('audit', 'kiểm toán', '/ˈɔːdɪt/', 'An annual tax audit.', 'toeic'),
  ('payroll', 'bảng lương', '/ˈpeɪrəʊl/', 'Check the monthly payroll.', 'toeic'),
  ('overtime', 'làm thêm giờ', '/ˈəʊvətaɪm/', 'Paid weekend overtime.', 'toeic'),
  ('shift', 'ca làm việc', '/ʃɪft/', 'Night shift starts now.', 'toeic'),
  ('resign', 'từ chức', '/rɪˈzaɪn/', 'She may soon resign.', 'toeic'),
  ('recruit', 'tuyển dụng', '/rɪˈkruːt/', 'Recruit skilled young staff.', 'toeic'),
  ('interview', 'phỏng vấn', '/ˈɪntəvjuː/', 'A short job interview.', 'toeic'),
  ('candidate', 'ứng viên', '/ˈkændɪdət/', 'The best job candidate.', 'toeic'),
  ('resume', 'sơ yếu lý lịch', '/ˈrezjʊmeɪ/', 'Update your resume today.', 'toeic'),
  ('vacancy', 'vị trí trống', '/ˈveɪkənsi/', 'Fill each job vacancy.', 'toeic'),
  ('internship', 'thực tập', '/ˈɪntɜːnʃɪp/', 'A paid summer internship.', 'toeic')
ON CONFLICT (en) DO NOTHING;
