INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('itinerary', 'lịch trình chuyến đi', '/aɪˈtɪnərəri/', 'Print the trip itinerary.', 'toeic'),
  ('booking', 'đặt chỗ', '/ˈbʊkɪŋ/', 'Confirm every flight booking.', 'toeic'),
  ('reservation', 'đặt trước', '/ˌrezəˈveɪʃn/', 'Make a hotel reservation.', 'toeic'),
  ('check-in', 'làm thủ tục', '/ˈtʃek ɪn/', 'Online check-in saves time.', 'toeic'),
  ('boarding', 'lên máy bay', '/ˈbɔːdɪŋ/', 'Late boarding annoys all.', 'toeic'),
  ('delay', 'trì hoãn', '/dɪˈleɪ/', 'Rain caused long delays.', 'toeic'),
  ('cancel', 'hủy bỏ', '/ˈkænsl/', 'Never cancel last minute.', 'toeic'),
  ('refund', 'hoàn tiền', '/ˈriːfʌnd/', 'Request a full refund.', 'toeic'),
  ('fare', 'giá vé', '/feə/', 'Cheap off-peak fares.', 'toeic'),
  ('luggage', 'hành lý', '/ˈlʌɡɪdʒ/', 'Lost airport luggage again.', 'toeic'),
  ('shuttle', 'xe đưa đón', '/ˈʃʌtl/', 'Free hotel shuttle buses.', 'toeic'),
  ('commute', 'đi làm hàng ngày', '/kəˈmjuːt/', 'A long daily commute.', 'toeic'),
  ('traffic', 'giao thông', '/ˈtræfɪk/', 'Heavy rush-hour traffic.', 'toeic'),
  ('route', 'tuyến đường', '/ruːt/', 'Plan the fastest route.', 'toeic'),
  ('detour', 'đường vòng', '/ˈdiːtʊə/', 'Take a short detour.', 'toeic'),
  ('landmark', 'địa danh', '/ˈlændmɑːk/', 'Famous historic landmarks.', 'toeic'),
  ('souvenir', 'quà lưu niệm', '/ˌsuːvəˈnɪə/', 'Buy cheap fun souvenirs.', 'toeic'),
  ('brochure', 'tờ rơi', '/ˈbrəʊʃə/', 'Pick up a tour brochure.', 'toeic'),
  ('exhibition', 'triển lãm', '/ˌeksɪˈbɪʃn/', 'A grand art exhibition.', 'toeic'),
  ('conference', 'hội nghị', '/ˈkɒnfərəns/', 'Annual sales conference time.', 'toeic'),
  ('workshop', 'hội thảo thực hành', '/ˈwɜːkʃɒp/', 'Join a weekend workshop.', 'toeic'),
  ('banquet', 'yến tiệc', '/ˈbæŋkwɪt/', 'A formal awards banquet.', 'toeic'),
  ('cater', 'phục vụ ăn uống', '/ˈkeɪtə/', 'Cater all office parties.', 'toeic'),
  ('venue', 'địa điểm tổ chức', '/ˈvenjuː/', 'Book the wedding venue.', 'toeic'),
  ('attendee', 'người tham dự', '/ˌætenˈdiː/', 'Greet every new attendee.', 'toeic'),
  ('pamphlet', 'tờ gấp', '/ˈpæmflət/', 'Hand out each pamphlet.', 'toeic'),
  ('directory', 'danh bạ', '/dəˈrektəri/', 'Check the staff directory.', 'toeic'),
  ('extension', 'số máy lẻ', '/ɪkˈstenʃn/', 'Dial my extension please.', 'toeic'),
  ('voicemail', 'thư thoại', '/ˈvɔɪsmeɪl/', 'Leave a short voicemail.', 'toeic'),
  ('photocopy', 'sao chụp', '/ˈfəʊtəkɒpi/', 'Photocopy these contracts.', 'toeic'),
  ('staple', 'ghim bấm', '/ˈsteɪpl/', 'Staple the pages together.', 'toeic'),
  ('shred', 'hủy tài liệu', '/ʃred/', 'Shred all old receipts.', 'toeic'),
  ('archive', 'lưu trữ', '/ˈɑːkaɪv/', 'Archive old tax files.', 'toeic'),
  ('retrieve', 'lấy lại', '/rɪˈtriːv/', 'Retrieve deleted emails fast.', 'toeic'),
  ('overdue', 'quá hạn', '/ˌəʊvəˈdjuː/', 'Two overdue library books.', 'toeic'),
  ('renew', 'gia hạn', '/rɪˈnjuː/', 'Renew your gym card.', 'toeic'),
  ('expire', 'hết hạn', '/ɪkˈspaɪə/', 'Passports expire in May.', 'toeic'),
  ('warranty', 'bảo hành', '/ˈwɒrənti/', 'A two-year free warranty.', 'toeic'),
  ('maintenance', 'bảo trì', '/ˈmeɪntənəns/', 'Monthly elevator maintenance.', 'toeic'),
  ('outsource', 'thuê ngoài', '/ˈaʊtsɔːs/', 'Outsource the night cleaning.', 'toeic')
ON CONFLICT (en) DO NOTHING;
