INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('discount', 'giảm giá', '/ˈdɪskaʊnt/', 'Big weekend discounts here.', 'toeic'),
  ('coupon', 'phiếu giảm giá', '/ˈkuːpɒn/', 'Clip every paper coupon.', 'toeic'),
  ('clearance', 'xả hàng', '/ˈklɪərəns/', 'Final clearance sale today.', 'toeic'),
  ('exchange', 'đổi hàng', '/ɪksˈtʃeɪndʒ/', 'Exchange sizes for free.', 'toeic'),
  ('guarantee', 'bảo đảm', '/ˌɡærənˈtiː/', 'We guarantee fresh food.', 'toeic'),
  ('brand', 'thương hiệu', '/brænd/', 'A trusted global brand.', 'toeic'),
  ('logo', 'biểu trưng', '/ˈləʊɡəʊ/', 'A simple memorable logo.', 'toeic'),
  ('slogan', 'khẩu hiệu', '/ˈsləʊɡən/', 'A catchy new slogan.', 'toeic'),
  ('advertise', 'quảng cáo', '/ˈædvətaɪz/', 'Advertise on night buses.', 'toeic'),
  ('commercial', 'quảng cáo TV', '/kəˈmɜːʃl/', 'A funny short commercial.', 'toeic'),
  ('billboard', 'biển quảng cáo', '/ˈbɪlbɔːd/', 'Giant roadside billboards.', 'toeic'),
  ('sponsor', 'tài trợ', '/ˈspɒnsə/', 'Sponsor the school team.', 'toeic'),
  ('launch', 'ra mắt', '/lɔːntʃ/', 'Launch the app in June.', 'toeic'),
  ('quota', 'hạn ngạch', '/ˈkwəʊtə/', 'Meet the monthly quota.', 'toeic'),
  ('commission', 'hoa hồng', '/kəˈmɪʃn/', 'Earn ten percent commission.', 'toeic'),
  ('bonus', 'tiền thưởng', '/ˈbəʊnəs/', 'A generous Tet bonus.', 'toeic'),
  ('raise', 'tăng lương', '/reɪz/', 'Ask for a fair raise.', 'toeic'),
  ('deduction', 'khoản khấu trừ', '/dɪˈdʌkʃn/', 'Small monthly tax deductions.', 'toeic'),
  ('statement', 'sao kê', '/ˈsteɪtmənt/', 'Check bank statements monthly.', 'toeic'),
  ('overdraft', 'thấu chi', '/ˈəʊvədrɑːft/', 'Avoid costly bank overdrafts.', 'toeic'),
  ('interest', 'lãi suất', '/ˈɪntrəst/', 'Low simple bank interest.', 'toeic'),
  ('mortgage', 'thế chấp', '/ˈmɔːɡɪdʒ/', 'A thirty-year home mortgage.', 'toeic'),
  ('lease', 'thuê dài hạn', '/liːs/', 'Sign a two-year lease.', 'toeic'),
  ('tenant', 'người thuê nhà', '/ˈtenənt/', 'Kind helpful new tenants.', 'toeic'),
  ('landlord', 'chủ nhà', '/ˈlændlɔːd/', 'Call the strict landlord.', 'toeic'),
  ('deposit', 'tiền đặt cọc', '/dɪˈpɒzɪt/', 'Pay a small deposit.', 'toeic'),
  ('installment', 'trả góp', '/ɪnˈstɔːlmənt/', 'Easy monthly installments.', 'toeic'),
  ('bankrupt', 'phá sản', '/ˈbæŋkrʌpt/', 'The old firm went bankrupt.', 'toeic'),
  ('debt', 'nợ nần', '/det/', 'Clear all credit debts.', 'toeic'),
  ('creditor', 'chủ nợ', '/ˈkredɪtə/', 'Pay each angry creditor.', 'toeic'),
  ('haggle', 'mặc cả', '/ˈhæɡl/', 'Haggle at night markets.', 'toeic'),
  ('wholesale', 'bán sỉ', '/ˈhəʊlseɪl/', 'Buy rice at wholesale.', 'toeic'),
  ('retail', 'bán lẻ', '/ˈriːteɪl/', 'Work in busy retail.', 'toeic'),
  ('inventory', 'hàng tồn kho', '/ˈɪnvəntri/', 'Count store inventory nightly.', 'toeic'),
  ('shortage', 'thiếu hụt', '/ˈʃɔːtɪdʒ/', 'A sudden rice shortage.', 'toeic'),
  ('shipment', 'lô hàng', '/ˈʃɪpmənt/', 'Track each late shipment.', 'toeic'),
  ('freight', 'cước vận chuyển', '/freɪt/', 'High air freight costs.', 'toeic'),
  ('cargo', 'hàng hóa', '/ˈkɑːɡəʊ/', 'Unload the heavy cargo.', 'toeic'),
  ('warehouse', 'kho hàng', '/ˈweəhaʊs/', 'A huge cold warehouse.', 'toeic'),
  ('crate', 'thùng gỗ', '/kreɪt/', 'Pack fruit in crates.', 'toeic')
ON CONFLICT (en) DO NOTHING;
