INSERT INTO words (en, vi, ipa, example, topic) VALUES
  ('prescription', 'đơn thuốc', '/prɪˈskrɪpʃn/', 'Show your doctor prescription.', 'toeic'),
  ('pharmacy', 'hiệu thuốc', '/ˈfɑːməsi/', 'A late-night city pharmacy.', 'toeic'),
  ('ailment', 'bệnh nhẹ', '/ˈeɪlmənt/', 'Treat each minor ailment.', 'toeic'),
  ('remedy', 'cách chữa', '/ˈremədi/', 'Honey is a good remedy.', 'toeic'),
  ('barber', 'thợ cắt tóc', '/ˈbɑːbə/', 'A skilled old barber.', 'toeic'),
  ('laundromat', 'tiệm giặt tự phục vụ', '/ˈlɔːndrəmæt/', 'Wash at the corner laundromat.', 'toeic'),
  ('dry-clean', 'giặt khô', '/ˌdraɪ ˈkliːn/', 'Dry-clean the wool suit.', 'toeic'),
  ('tailor', 'thợ may', '/ˈteɪlə/', 'A careful young tailor.', 'toeic'),
  ('locksmith', 'thợ khóa', '/ˈlɒksmɪθ/', 'Call a fast locksmith.', 'toeic'),
  ('plumber', 'thợ sửa ống nước', '/ˈplʌmə/', 'A busy kind plumber.', 'toeic'),
  ('electrician', 'thợ điện', '/ˌɪlekˈtrɪʃn/', 'Hire a licensed electrician.', 'toeic'),
  ('janitor', 'lao công', '/ˈdʒænɪtə/', 'Thank the night janitor.', 'toeic'),
  ('concierge', 'lễ tân khách sạn', '/ˌkɒnsiˈeəʒ/', 'Ask the hotel concierge.', 'toeic'),
  ('housekeeping', 'dọn phòng', '/ˈhaʊskiːpɪŋ/', 'Daily hotel housekeeping.', 'toeic'),
  ('checkout', 'trả phòng', '/ˈtʃekaʊt/', 'Checkout is at noon.', 'toeic'),
  ('minibar', 'tủ lạnh mini', '/ˈmɪnibɑː/', 'Pricey hotel minibar snacks.', 'toeic'),
  ('occupancy', 'công suất phòng', '/ˈɒkjəpənsi/', 'Full summer occupancy rates.', 'toeic'),
  ('suite', 'phòng hạng sang', '/swiːt/', 'Book the top suite.', 'toeic'),
  ('lobby', 'sảnh', '/ˈlɒbi/', 'Meet in the grand lobby.', 'toeic'),
  ('elevator', 'thang máy', '/ˈelɪveɪtə/', 'Take the fast elevator.', 'toeic'),
  ('escalator', 'thang cuốn', '/ˈeskəleɪtə/', 'Stand right on escalators.', 'toeic'),
  ('parking', 'bãi đỗ xe', '/ˈpɑːkɪŋ/', 'Free basement parking here.', 'toeic'),
  ('valet', 'giữ xe hộ', '/ˈvæleɪ/', 'Tip the quick valet.', 'toeic'),
  ('toll', 'phí đường bộ', '/təʊl/', 'Pay each highway toll.', 'toeic'),
  ('subway', 'tàu điện ngầm', '/ˈsʌbweɪ/', 'Ride the crowded subway.', 'toeic'),
  ('ferry', 'phà', '/ˈferi/', 'Catch the last ferry.', 'toeic'),
  ('cruise', 'du thuyền', '/kruːz/', 'A cheap river cruise.', 'toeic'),
  ('passport', 'hộ chiếu', '/ˈpɑːspɔːt/', 'Check passport expiry dates.', 'toeic'),
  ('visa', 'thị thực', '/ˈviːzə/', 'Apply for a work visa.', 'toeic'),
  ('customs', 'hải quan', '/ˈkʌstəmz/', 'Pass through green customs.', 'toeic'),
  ('declare', 'khai báo', '/dɪˈkleə/', 'Declare all cash over limits.', 'toeic'),
  ('duty-free', 'miễn thuế', '/ˌdjuːti ˈfriː/', 'Shop in duty-free stores.', 'toeic'),
  ('postcard', 'bưu thiếp', '/ˈpəʊstkɑːd/', 'Send pretty beach postcards.', 'toeic'),
  ('stamp', 'tem thư', '/stæmp/', 'Rare old postage stamps.', 'toeic'),
  ('parcel', 'bưu kiện', '/ˈpɑːsl/', 'Track your late parcel.', 'toeic'),
  ('courier', 'chuyển phát nhanh', '/ˈkʊriə/', 'A same-day bike courier.', 'toeic'),
  ('track', 'theo dõi đơn', '/træk/', 'Track parcels by phone.', 'toeic'),
  ('signature', 'chữ ký', '/ˈsɪɡnətʃə/', 'Sign with a clear signature.', 'toeic'),
  ('billing', 'thanh toán', '/ˈbɪlɪŋ/', 'Monthly online phone billing.', 'toeic'),
  ('paycheck', 'phiếu lương', '/ˈpeɪtʃek/', 'First monthly paycheck joy.', 'toeic')
ON CONFLICT (en) DO NOTHING;
