-- TOEIC Phase 1.2 continued: Reading Part 6 (text completion) + Part 7 (comprehension).
-- Questions sharing a passage are linked by passage_id; Part 5 rows keep both NULL.

ALTER TABLE toeic_questions ADD COLUMN IF NOT EXISTS passage_id INTEGER;
ALTER TABLE toeic_questions ADD COLUMN IF NOT EXISTS passage_text TEXT;

-- Part 6, Text A: office relocation email (ids 31-34, passage 101)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(31, 6, 'reading', 'Please note that our office ___ to the new building next month.', '["will relocate", "relocated", "relocates", "relocating"]', 0, 'Tương lai đơn với mốc "next month" diễn tả kế hoạch đã định → will relocate.', 'tenses', 'office', 101, 'To: All Staff\nSubject: Office Relocation\n\nPlease note that our office ___ (31) to the new building next month. All personal belongings must be packed ___ (32) May 30. The new office offers a ___ (33) working environment with modern facilities. ___ (34) you have any questions, please contact the admin team.\n\nBest regards,\nMs. Carter'),
(32, 6, 'reading', 'All personal belongings must be packed ___ May 30.', '["by", "on", "at", "in"]', 0, '"By + mốc thời gian" = chậm nhất vào lúc đó (deadline đóng gói).', 'prepositions', 'office', 101, 'To: All Staff\nSubject: Office Relocation\n\nPlease note that our office ___ (31) to the new building next month. All personal belongings must be packed ___ (32) May 30. The new office offers a ___ (33) working environment with modern facilities. ___ (34) you have any questions, please contact the admin team.\n\nBest regards,\nMs. Carter'),
(33, 6, 'reading', 'The new office offers a ___ working environment with modern facilities.', '["comfortable", "comfort", "comfortably", "comforts"]', 0, 'Cần tính từ bổ nghĩa "working environment" → comfortable (thoải mái).', 'word-forms', 'office', 101, 'To: All Staff\nSubject: Office Relocation\n\nPlease note that our office ___ (31) to the new building next month. All personal belongings must be packed ___ (32) May 30. The new office offers a ___ (33) working environment with modern facilities. ___ (34) you have any questions, please contact the admin team.\n\nBest regards,\nMs. Carter'),
(34, 6, 'reading', '___ you have any questions, please contact the admin team.', '["If", "Unless", "Despite", "Without"]', 0, 'Mệnh đề điều kiện "If you have..." (nếu có thắc mắc); các đáp án khác không hợp nghĩa.', 'conjunctions', 'office', 101, 'To: All Staff\nSubject: Office Relocation\n\nPlease note that our office ___ (31) to the new building next month. All personal belongings must be packed ___ (32) May 30. The new office offers a ___ (33) working environment with modern facilities. ___ (34) you have any questions, please contact the admin team.\n\nBest regards,\nMs. Carter'),
-- Part 6, Text B: IT maintenance memo (ids 35-38, passage 102)
(35, 6, 'reading', 'The IT department will perform system maintenance ___ Saturday night.', '["on", "in", "at", "to"]', 0, 'Ngày trong tuần (Saturday night) đi với giới từ "on".', 'prepositions', 'it', 102, 'MEMO\nTo: All Employees\n\nThe IT department will perform system maintenance ___ (35) Saturday night. During the maintenance, the email system will be ___ (36) unavailable. We apologize ___ (37) any inconvenience this may cause. The maintenance is expected to finish ___ (38) 6 a.m. on Sunday.\n\nIT Department'),
(36, 6, 'reading', 'During the maintenance, the email system will be ___ unavailable.', '["temporarily", "temporary", "temper", "temptation"]', 0, 'Cần trạng từ bổ nghĩa tính từ "unavailable" → temporarily (tạm thời).', 'word-forms', 'it', 102, 'MEMO\nTo: All Employees\n\nThe IT department will perform system maintenance ___ (35) Saturday night. During the maintenance, the email system will be ___ (36) unavailable. We apologize ___ (37) any inconvenience this may cause. The maintenance is expected to finish ___ (38) 6 a.m. on Sunday.\n\nIT Department'),
(37, 6, 'reading', 'We apologize ___ any inconvenience this may cause.', '["for", "to", "about", "with"]', 0, '"Apologize for + vấn đề" (xin lỗi về sự bất tiện).', 'prepositions', 'it', 102, 'MEMO\nTo: All Employees\n\nThe IT department will perform system maintenance ___ (35) Saturday night. During the maintenance, the email system will be ___ (36) unavailable. We apologize ___ (37) any inconvenience this may cause. The maintenance is expected to finish ___ (38) 6 a.m. on Sunday.\n\nIT Department'),
(38, 6, 'reading', 'The maintenance is expected to finish ___ 6 a.m. on Sunday.', '["by", "until", "to", "from"]', 0, '"Finish by + mốc" = xong chậm nhất lúc đó; "until" dùng cho hành động kéo dài.', 'prepositions', 'it', 102, 'MEMO\nTo: All Employees\n\nThe IT department will perform system maintenance ___ (35) Saturday night. During the maintenance, the email system will be ___ (36) unavailable. We apologize ___ (37) any inconvenience this may cause. The maintenance is expected to finish ___ (38) 6 a.m. on Sunday.\n\nIT Department')
ON CONFLICT (id) DO NOTHING;

-- Part 7, Passage C: delivery notice (ids 39-41, passage 201)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(39, 7, 'reading', 'What service is advertised in the notice?', '["Free same-day delivery for city orders over $50", "Free international shipping", "Discounts on weekend orders", "24-hour phone support"]', 0, 'Thông báo ghi rõ free same-day delivery cho đơn nội thành trên $50.', 'comprehension', 'logistics', 201, 'NOTICE\nFastShip Delivery\n\nFree same-day delivery for orders over $50 within the city, Monday to Friday. Orders placed after 3 p.m. will be delivered the next day. To track your package, visit our website and enter your order number.'),
(40, 7, 'reading', 'According to the notice, what happens to orders placed after 3 p.m.?', '["They will be delivered the next day", "They cost an extra fee", "They are canceled", "They arrive the same evening"]', 0, 'Câu "Orders placed after 3 p.m. will be delivered the next day" trả lời trực tiếp.', 'comprehension', 'logistics', 201, 'NOTICE\nFastShip Delivery\n\nFree same-day delivery for orders over $50 within the city, Monday to Friday. Orders placed after 3 p.m. will be delivered the next day. To track your package, visit our website and enter your order number.'),
(41, 7, 'reading', 'The word "within" in the notice is closest in meaning to ___.', '["inside", "without", "beyond", "during"]', 0, '"Within the city" = bên trong thành phố → inside.', 'vocabulary', 'logistics', 201, 'NOTICE\nFastShip Delivery\n\nFree same-day delivery for orders over $50 within the city, Monday to Friday. Orders placed after 3 p.m. will be delivered the next day. To track your package, visit our website and enter your order number.'),
-- Part 7, Passage D: meeting email (ids 42-44, passage 202)
(42, 7, 'reading', 'Why was this email written?', '["To inform staff about a room and time change", "To invite new employees", "To cancel the budget review", "To announce a new manager"]', 0, 'Email báo đổi phòng/họp (Room 204, 10 giờ sáng thứ Sáu).', 'comprehension', 'meetings', 202, 'Dear team,\n\nPlease note that Friday''s budget review has been moved to Room 204 and will start at 10 a.m. instead of 9 a.m. The agenda remains the same. If you have any questions, please contact Ms. Lee before Thursday.\n\nThank you,\nMr. Park'),
(43, 7, 'reading', 'Who should staff contact with questions?', '["Ms. Lee", "Mr. Park", "The director", "The admin team"]', 0, 'Cuối email: "...please contact Ms. Lee before Thursday".', 'comprehension', 'meetings', 202, 'Dear team,\n\nPlease note that Friday''s budget review has been moved to Room 204 and will start at 10 a.m. instead of 9 a.m. The agenda remains the same. If you have any questions, please contact Ms. Lee before Thursday.\n\nThank you,\nMr. Park'),
(44, 7, 'reading', 'What time will the meeting start?', '["10 a.m.", "9 a.m.", "2 p.m.", "4 p.m."]', 0, 'Email ghi rõ "will start at 10 a.m. instead of 9 a.m.".', 'comprehension', 'meetings', 202, 'Dear team,\n\nPlease note that Friday''s budget review has been moved to Room 204 and will start at 10 a.m. instead of 9 a.m. The agenda remains the same. If you have any questions, please contact Ms. Lee before Thursday.\n\nThank you,\nMr. Park'),
-- Part 7, Passage E: job ad (ids 45-47, passage 203)
(45, 7, 'reading', 'What position is advertised?', '["A part-time marketing assistant", "A full-time accountant", "A delivery driver", "An IT manager"]', 0, 'Tiêu đề: part-time marketing assistant, 20 giờ/tuần.', 'comprehension', 'hr', 203, 'GreenTech Solutions is looking for a part-time marketing assistant (20 hours per week). Requirements: fluent English, good Excel skills. Interested candidates should send a resume by May 15 to hr@greentech.example.com.'),
(46, 7, 'reading', 'Which of the following is NOT mentioned as a requirement?', '["A driver''s license", "Fluent English", "Good Excel skills", "A resume"]', 0, 'Quảng cáo chỉ đòi tiếng Anh, Excel và resume — không nhắc bằng lái.', 'comprehension', 'hr', 203, 'GreenTech Solutions is looking for a part-time marketing assistant (20 hours per week). Requirements: fluent English, good Excel skills. Interested candidates should send a resume by May 15 to hr@greentech.example.com.'),
(47, 7, 'reading', 'What is the application deadline?', '["May 15", "May 5", "June 15", "April 30"]', 0, '"...send a resume by May 15..." — by = chậm nhất ngày đó.', 'comprehension', 'hr', 203, 'GreenTech Solutions is looking for a part-time marketing assistant (20 hours per week). Requirements: fluent English, good Excel skills. Interested candidates should send a resume by May 15 to hr@greentech.example.com.')
ON CONFLICT (id) DO NOTHING;
