-- TOEIC Listening bank (TTS-based, no audio hosting): Part 1 (photos as scene
-- descriptions), Part 2 (Q-R), Part 3 (conversations), Part 4 (talks).
-- audio_text = what the browser TTS reads; transcript = shown in review.

ALTER TABLE toeic_questions ADD COLUMN IF NOT EXISTS transcript TEXT;
ALTER TABLE toeic_questions ADD COLUMN IF NOT EXISTS audio_text TEXT;

-- Part 1: photos (ids 101-105, section listening)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, transcript, audio_text) VALUES
(101, 1, 'listening', 'Bức ảnh: hai đồng nghiệp đang họp trong phòng họp, một người chỉ vào biểu đồ trên màn hình.', '["They are having a meeting.", "They are eating lunch.", "They are swimming.", "They are driving."]', 0, 'Trong ảnh mọi người họp và chỉ biểu đồ → "having a meeting" đúng.', 'photo', 'meetings', 'They are having a meeting.', 'A. They are having a meeting. B. They are eating lunch. C. They are swimming. D. They are driving.'),
(102, 1, 'listening', 'Bức ảnh: một nhân viên đang gõ máy tính tại bàn làm việc gần cửa sổ.', '["She is typing on a computer.", "She is cooking dinner.", "She is playing tennis.", "She is boarding a plane."]', 0, 'Người phụ nữ gõ máy tính ở bàn làm việc → typing on a computer.', 'photo', 'office', 'She is typing on a computer.', 'A. She is typing on a computer. B. She is cooking dinner. C. She is playing tennis. D. She is boarding a plane.'),
(103, 1, 'listening', 'Bức ảnh: hành khách xếp hàng ở quầy làm thủ tục sân bay.', '["Passengers are waiting at the check-in counter.", "Passengers are swimming.", "Passengers are having dinner.", "Passengers are planting trees."]', 0, 'Xếp hàng ở quầy check-in → waiting at the check-in counter.', 'photo', 'travel', 'Passengers are waiting at the check-in counter.', 'A. Passengers are waiting at the check-in counter. B. Passengers are swimming. C. Passengers are having dinner. D. Passengers are planting trees.'),
(104, 1, 'listening', 'Bức ảnh: công nhân đang xếp thùng hàng lên xe tải trong kho.', '["Workers are loading boxes onto a truck.", "Workers are dancing.", "Workers are reading books.", "Workers are fishing."]', 0, 'Xếp thùng lên xe tải → loading boxes onto a truck.', 'photo', 'logistics', 'Workers are loading boxes onto a truck.', 'A. Workers are loading boxes onto a truck. B. Workers are dancing. C. Workers are reading books. D. Workers are fishing.'),
(105, 1, 'listening', 'Bức ảnh: một người đàn ông đang nghe điện thoại bên bàn làm việc có tài liệu.', '["He is talking on the phone.", "He is sleeping.", "He is running.", "He is painting."]', 0, 'Nghe/gọi điện thoại → talking on the phone.', 'photo', 'office', 'He is talking on the phone.', 'A. He is talking on the phone. B. He is sleeping. C. He is running. D. He is painting.')
ON CONFLICT (id) DO NOTHING;

-- Part 2: question-response (ids 106-115)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, transcript, audio_text) VALUES
(106, 2, 'listening', 'When will the new printer arrive?', '["Next Tuesday.", "In the meeting room.", "The red one."]', 0, 'Hỏi "when" (khi nào) → đáp án thời gian "Next Tuesday".', 'wh-question', 'office', 'When will the new printer arrive? Next Tuesday.', 'When will the new printer arrive? A. Next Tuesday. B. In the meeting room. C. The red one.'),
(107, 2, 'listening', 'Who is in charge of the marketing budget?', '["Ms. Adams is.", "At 3 p.m.", "Yes, very much."]', 0, 'Hỏi "who" (ai) → đáp án chỉ người "Ms. Adams is".', 'wh-question', 'marketing', 'Who is in charge of the marketing budget? Ms. Adams is.', 'Who is in charge of the marketing budget? A. Ms. Adams is. B. At 3 p.m. C. Yes, very much.'),
(108, 2, 'listening', 'Would you like me to reserve a conference room?', '["Yes, please. Room 204.", "No, I arrived late.", "The room is big."]', 0, 'Lời đề nghị → chấp nhận "Yes, please" + chi tiết phòng.', 'offer', 'meetings', 'Would you like me to reserve a conference room? Yes, please. Room 204.', 'Would you like me to reserve a conference room? A. Yes, please. Room 204. B. No, I arrived late. C. The room is big.'),
(109, 2, 'listening', 'The quarterly report is due tomorrow, isn''t it?', '["Yes, I submitted it this morning.", "No, I like coffee.", "The report is long."]', 0, 'Câu hỏi đuôi xác nhận → trả lời Yes/No + thông tin liên quan.', 'tag-question', 'finance', 'The quarterly report is due tomorrow, isn''t it? Yes, I submitted it this morning.', 'The quarterly report is due tomorrow, isn''t it? A. Yes, I submitted it this morning. B. No, I like coffee. C. The report is long.'),
(110, 2, 'listening', 'How long does the flight to Singapore take?', '["About six hours.", "At Gate 12.", "With my colleague."]', 0, 'Hỏi "how long" (bao lâu) → đáp án khoảng thời gian.', 'wh-question', 'travel', 'How long does the flight to Singapore take? About six hours.', 'How long does the flight to Singapore take? A. About six hours. B. At Gate 12. C. With my colleague.'),
(111, 2, 'listening', 'Did you send the invoice to the client?', '["Yes, I emailed it yesterday.", "No, the office is closed.", "The invoice is white."]', 0, 'Hỏi Yes/No quá khứ → "Yes, I emailed it yesterday".', 'yes-no', 'finance', 'Did you send the invoice to the client? Yes, I emailed it yesterday.', 'Did you send the invoice to the client? A. Yes, I emailed it yesterday. B. No, the office is closed. C. The invoice is white.'),
(112, 2, 'listening', 'Where should we hold the product launch?', '["The Grand Hotel downtown.", "Next Friday.", "Two hundred guests."]', 0, 'Hỏi "where" (ở đâu) → đáp án địa điểm.', 'wh-question', 'marketing', 'Where should we hold the product launch? The Grand Hotel downtown.', 'Where should we hold the product launch? A. The Grand Hotel downtown. B. Next Friday. C. Two hundred guests.'),
(113, 2, 'listening', 'Could you forward me last week''s sales figures?', '["Sure, I''ll send them right away.", "No, I don''t like sales.", "The figures are numbers."]', 0, 'Nhờ vả lịch sự → đồng ý "Sure, I''ll send them right away".', 'request', 'sales', 'Could you forward me last week''s sales figures? Sure, I''ll send them right away.', 'Could you forward me last week''s sales figures? A. Sure, I''ll send them right away. B. No, I don''t like sales. C. The figures are numbers.'),
(114, 2, 'listening', 'Why was the training session postponed?', '["Because the trainer was sick.", "In Room 105.", "For two hours."]', 0, 'Hỏi "why" (tại sao) → đáp án lý do với "Because".', 'wh-question', 'hr', 'Why was the training session postponed? Because the trainer was sick.', 'Why was the training session postponed? A. Because the trainer was sick. B. In Room 105. C. For two hours.'),
(115, 2, 'listening', 'You have worked here since 2020, haven''t you?', '["That''s right, over five years now.", "No, I prefer tea.", "The office is large."]', 0, 'Câu hỏi đuôi → xác nhận "That''s right" + thông tin thêm.', 'tag-question', 'hr', 'You have worked here since 2020, haven''t you? That''s right, over five years now.', 'You have worked here since 2020, haven''t you? A. That''s right, over five years now. B. No, I prefer tea. C. The office is large.')
ON CONFLICT (id) DO NOTHING;

-- Part 3: conversation 1, office move (ids 116-118, passage 301)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, transcript, audio_text) VALUES
(116, 3, 'listening', 'What are the speakers mainly discussing?', '["An office relocation", "A new product", "A holiday party", "A job interview"]', 0, 'Cả hội thoại xoay quanh việc chuyển văn phòng sang tầng 5.', 'main-idea', 'office', 301, 'Woman: Have you heard? We are moving to the fifth floor next month.\nMan: Really? Will our team stay together?\nWoman: Yes, and the new space has a bigger meeting room.', 'Woman: Have you heard? We are moving to the fifth floor next month? Man: Really? Will our team stay together? Woman: Yes, and the new space has a bigger meeting room.'),
(117, 3, 'listening', 'When will the move happen?', '["Next month", "Tomorrow", "Last week", "Next year"]', 0, '"...moving to the fifth floor next month".', 'detail', 'office', 301, 'Woman: Have you heard? We are moving to the fifth floor next month.\nMan: Really? Will our team stay together?\nWoman: Yes, and the new space has a bigger meeting room.', 'Woman: Have you heard? We are moving to the fifth floor next month? Man: Really? Will our team stay together? Woman: Yes, and the new space has a bigger meeting room.'),
(118, 3, 'listening', 'What does the woman say about the new space?', '["It has a bigger meeting room", "It is smaller", "It has no windows", "It is far away"]', 0, '"...the new space has a bigger meeting room".', 'detail', 'office', 301, 'Woman: Have you heard? We are moving to the fifth floor next month.\nMan: Really? Will our team stay together?\nWoman: Yes, and the new space has a bigger meeting room.', 'Woman: Have you heard? We are moving to the fifth floor next month? Man: Really? Will our team stay together? Woman: Yes, and the new space has a bigger meeting room.'),
-- Part 3: conversation 2, late delivery (ids 119-121, passage 302)
(119, 3, 'listening', 'What is the man''s problem?', '["His order arrived late", "His bill was wrong", "He lost his key", "He missed a flight"]', 0, 'Người đàn ông phàn nàn đơn hàng đến trễ 2 ngày.', 'main-idea', 'support', 302, 'Man: Hello, my order arrived two days late.\nWoman: I''m sorry to hear that. May I have your order number?\nMan: It''s 45892. I need these parts urgently.\nWoman: I''ll upgrade your next shipment to express delivery for free.', 'Man: Hello, my order arrived two days late? Woman: I am sorry to hear that. May I have your order number? Man: It is 45892. I need these parts urgently. Woman: I will upgrade your next shipment to express delivery for free.'),
(120, 3, 'listening', 'What does the woman ask for?', '["The order number", "A credit card", "An email address", "A home address"]', 0, '"May I have your order number?"', 'detail', 'support', 302, 'Man: Hello, my order arrived two days late.\nWoman: I''m sorry to hear that. May I have your order number?\nMan: It''s 45892. I need these parts urgently.\nWoman: I''ll upgrade your next shipment to express delivery for free.', 'Man: Hello, my order arrived two days late? Woman: I am sorry to hear that. May I have your order number? Man: It is 45892. I need these parts urgently. Woman: I will upgrade your next shipment to express delivery for free.'),
(121, 3, 'listening', 'What does the woman offer to do?', '["Upgrade the next shipment for free", "Give a full refund", "Cancel the order", "Call the manager"]', 0, '"I''ll upgrade your next shipment to express delivery for free".', 'detail', 'support', 302, 'Man: Hello, my order arrived two days late.\nWoman: I''m sorry to hear that. May I have your order number?\nMan: It''s 45892. I need these parts urgently.\nWoman: I''ll upgrade your next shipment to express delivery for free.', 'Man: Hello, my order arrived two days late? Woman: I am sorry to hear that. May I have your order number? Man: It is 45892. I need these parts urgently. Woman: I will upgrade your next shipment to express delivery for free.')
ON CONFLICT (id) DO NOTHING;

-- Part 4: talk 1, store announcement (ids 122-124, passage 401)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, transcript, audio_text) VALUES
(122, 4, 'listening', 'Where is this announcement made?', '["In a department store", "At an airport", "In a bank", "At a school"]', 0, 'Nhắc đến tầng 3, khu điện tử giảm giá → trung tâm mua sắm.', 'main-idea', 'sales', 401, 'Attention shoppers! Our electronics department on the third floor is offering 20 percent off all laptops today only. Please visit our customer service desk on the first floor for more details. Thank you for shopping with us!', 'Attention shoppers! Our electronics department on the third floor is offering 20 percent off all laptops today only. Please visit our customer service desk on the first floor for more details. Thank you for shopping with us!'),
(123, 4, 'listening', 'What is on sale?', '["Laptops", "Phones", "Shoes", "Books"]', 0, '"...20 percent off all laptops today only".', 'detail', 'sales', 401, 'Attention shoppers! Our electronics department on the third floor is offering 20 percent off all laptops today only. Please visit our customer service desk on the first floor for more details. Thank you for shopping with us!', 'Attention shoppers! Our electronics department on the third floor is offering 20 percent off all laptops today only. Please visit our customer service desk on the first floor for more details. Thank you for shopping with us!'),
(124, 4, 'listening', 'Where can listeners get more information?', '["At the customer service desk", "At the exit", "On the website", "By phone"]', 0, '"...visit our customer service desk on the first floor...".', 'detail', 'sales', 401, 'Attention shoppers! Our electronics department on the third floor is offering 20 percent off all laptops today only. Please visit our customer service desk on the first floor for more details. Thank you for shopping with us!', 'Attention shoppers! Our electronics department on the third floor is offering 20 percent off all laptops today only. Please visit our customer service desk on the first floor for more details. Thank you for shopping with us!'),
-- Part 4: talk 2, voicemail (ids 125-127, passage 402)
(125, 4, 'listening', 'Who is the message for?', '["Mr. Thompson", "Ms. Lee", "The IT team", "All staff"]', 0, '"Hi, this is David calling for Mr. Thompson...".', 'detail', 'office', 402, 'Hi, this is David calling for Mr. Thompson regarding tomorrow''s 9 a.m. meeting. I''m afraid I have to reschedule it to Thursday at 2 p.m. Please call me back at 555-0148 to confirm. Thanks!', 'Hi, this is David calling for Mr. Thompson regarding the 9 a.m. meeting tomorrow. I am afraid I have to reschedule it to Thursday at 2 p.m. Please call me back to confirm. Thanks!'),
(126, 4, 'listening', 'What does the caller want to do?', '["Reschedule a meeting", "Cancel a contract", "Order supplies", "Book a flight"]', 0, '"...I have to reschedule it to Thursday at 2 p.m.".', 'main-idea', 'office', 402, 'Hi, this is David calling for Mr. Thompson regarding tomorrow''s 9 a.m. meeting. I''m afraid I have to reschedule it to Thursday at 2 p.m. Please call me back at 555-0148 to confirm. Thanks!', 'Hi, this is David calling for Mr. Thompson regarding the 9 a.m. meeting tomorrow. I am afraid I have to reschedule it to Thursday at 2 p.m. Please call me back to confirm. Thanks!'),
(127, 4, 'listening', 'What should Mr. Thompson do?', '["Call back to confirm", "Send an email", "Visit the office", "Wait until Friday"]', 0, '"Please call me back ... to confirm".', 'detail', 'office', 402, 'Hi, this is David calling for Mr. Thompson regarding tomorrow''s 9 a.m. meeting. I''m afraid I have to reschedule it to Thursday at 2 p.m. Please call me back at 555-0148 to confirm. Thanks!', 'Hi, this is David calling for Mr. Thompson regarding the 9 a.m. meeting tomorrow. I am afraid I have to reschedule it to Thursday at 2 p.m. Please call me back to confirm. Thanks!')
ON CONFLICT (id) DO NOTHING;
