-- TOEIC bank expansion 1/5: +40 Part 5 questions (ids 200-239).

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic) VALUES
(200, 5, 'reading', 'The board will announce the merger ___ a press conference tomorrow.', '["at", "during", "in", "on"]', 0, '"At a press conference" — cụm cố định chỉ địa điểm sự kiện.', 'prepositions', 'general'),
(201, 5, 'reading', 'She has worked in logistics ___ she graduated from university.', '["since", "for", "from", "during"]', 0, '"Since + mốc" (tốt nghiệp đại học).', 'prepositions', 'logistics'),
(202, 5, 'reading', 'All applications must be received ___ 5 p.m. on Friday.', '["by", "until", "to", "for"]', 0, '"By + mốc giờ" = deadline chậm nhất.', 'prepositions', 'hr'),
(203, 5, 'reading', 'The new CEO is known ___ turning struggling companies around.', '["for", "as", "to", "with"]', 0, '"Be known for + điểm mạnh" (nổi tiếng về...).', 'prepositions', 'general'),
(204, 5, 'reading', 'Employees are encouraged to share ideas ___ the weekly meeting.', '["during", "for", "since", "without"]', 0, '"During + sự kiện" (trong suốt cuộc họp).', 'prepositions', 'meetings'),
(205, 5, 'reading', 'Installation usually takes ___ thirty minutes.', '["about", "over", "above", "against"]', 0, '"About + số lượng" = khoảng (xấp xỉ 30 phút).', 'vocabulary', 'it'),
(206, 5, 'reading', 'If we ___ the budget now, the project will fail.', '["cut", "will cut", "cutting", "to cut"]', 0, 'Điều kiện loại 1: If + hiện tại đơn.', 'conditionals', 'finance'),
(207, 5, 'reading', 'The client requested that the proposal ___ revised immediately.', '["be", "was", "is", "were"]', 0, 'Giả định sau "request that": be + V3.', 'subjunctive', 'sales'),
(208, 5, 'reading', 'Neither the invoice nor the receipts ___ been processed yet.', '["have", "has", "is", "was"]', 0, '"Neither...nor" theo chủ ngữ gần nhất (receipts → have).', 'agreement', 'finance'),
(209, 5, 'reading', 'Marketing expenses have risen ___ 15 percent this year.', '["by", "to", "at", "with"]', 0, '"Rise by + mức %" (tăng bao nhiêu).', 'prepositions', 'marketing'),
(210, 5, 'reading', 'She apologized ___ missing the deadline.', '["for", "to", "about", "of"]', 0, '"Apologize for + V-ing".', 'gerunds', 'office'),
(211, 5, 'reading', 'The warehouse staff is responsible ___ packing daily orders.', '["for", "to", "of", "with"]', 0, '"Responsible for + V-ing".', 'gerunds', 'logistics'),
(212, 5, 'reading', 'We look forward to ___ your new catalogue.', '["receiving", "receive", "received", "receives"]', 0, '"Look forward to + V-ing".', 'gerunds', 'sales'),
(213, 5, 'reading', 'The conference room ___ cleaned every evening.', '["is", "are", "be", "been"]', 0, 'Bị động hiện tại đơn với chủ ngữ số ít → is cleaned.', 'passive', 'office'),
(214, 5, 'reading', 'He speaks ___ fluently that clients prefer dealing with him.', '["so", "such", "very", "too"]', 0, '"So + adv + that".', 'conjunctions', 'general'),
(215, 5, 'reading', 'The more competitive the market, ___ important customer service becomes.', '["the", "a", "an", "—"]', 0, 'So sánh kép "the more..., the...".', 'comparatives', 'sales'),
(216, 5, 'reading', 'She was hired ___ her experience in international trade.', '["because of", "despite", "unless", "without"]', 0, '"Because of + cụm danh từ" chỉ lý do.', 'conjunctions', 'hr'),
(217, 5, 'reading', 'The IT team resolved the issue ___ than expected.', '["faster", "fast", "fastest", "more fast"]', 0, 'So sánh hơn với "than" → faster.', 'comparatives', 'it'),
(218, 5, 'reading', '___ in customer service is our top priority.', '["Excellence", "Excellent", "Excellently", "Excel"]', 0, 'Cần danh từ làm chủ ngữ → Excellence.', 'word-forms', 'support'),
(219, 5, 'reading', 'The report, ___ was submitted late, contained several errors.', '["which", "who", "whose", "whom"]', 0, 'Mệnh đề quan hệ chỉ vật → which.', 'relative-clauses', 'office'),
(220, 5, 'reading', 'The successful candidate ___ speak both English and Spanish.', '["must", "musts", "musting", "to must"]', 0, 'Sau "must" dùng V nguyên mẫu; must không chia.', 'vocabulary', 'hr'),
(221, 5, 'reading', 'The delivery was delayed ___ heavy traffic at the port.', '["due to", "despite", "unless", "without"]', 0, '"Due to + nguyên nhân" (do kẹt xe).', 'conjunctions', 'logistics'),
(222, 5, 'reading', 'She decided ___ the advanced Excel course.', '["to take", "taking", "take", "taken"]', 0, '"Decide to + V" (quyết định học).', 'gerunds', 'hr'),
(223, 5, 'reading', 'He enjoys ___ with international partners.', '["working", "work", "worked", "works"]', 0, '"Enjoy + V-ing".', 'gerunds', 'general'),
(224, 5, 'reading', 'The new policy will come ___ effect in January.', '["into", "to", "for", "on"]', 0, '"Come into effect" (có hiệu lực).', 'prepositions', 'general'),
(225, 5, 'reading', 'Prices are expected to remain ___ through the holiday season.', '["stable", "stabilize", "stability", "stably"]', 0, '"Remain + tính từ" → stable (ổn định).', 'word-forms', 'sales'),
(226, 5, 'reading', 'The auditor found no ___ in the financial statements.', '["discrepancies", "discrepant", "discrepantly", "discrepate"]', 0, 'Cần danh từ số nhiều sau "no" → discrepancies (sai lệch).', 'word-forms', 'finance'),
(227, 5, 'reading', '___ the meeting, please turn off your mobile phones.', '["During", "For", "Since", "Without"]', 0, '"During + sự kiện" (trong cuộc họp).', 'prepositions', 'meetings'),
(228, 5, 'reading', 'The company has ___ 200 new employees this year.', '["hired", "been hired", "hire", "hiring"]', 0, 'Hiện tại hoàn thành chủ động: has + V3.', 'tenses', 'hr'),
(229, 5, 'reading', 'She ___ for the company since 2018 and loves her job.', '["has worked", "worked", "works", "will work"]', 0, '"Since 2018" + vẫn còn làm → has worked.', 'tenses', 'hr'),
(230, 5, 'reading', 'The seminar ___ by over 300 participants.', '["was attended", "attended", "has attend", "attends"]', 0, 'Bị động quá khứ: was + V3.', 'passive', 'general'),
(231, 5, 'reading', 'If the supplier ___ the price, we will switch vendors.', '["raises", "will raise", "raised", "raising"]', 0, 'Điều kiện loại 1: If + hiện tại đơn.', 'conditionals', 'sales'),
(232, 5, 'reading', 'He asked ___ the quarterly sales figures were ready.', '["whether", "if", "and", "that"]', 0, 'Câu hỏi gián tiếp Yes/No dùng "whether" (whether... or not).', 'conjunctions', 'sales'),
(233, 5, 'reading', 'The marketing team launched the campaign ___ schedule.', '["ahead of", "on", "at", "in"]', 0, '"Ahead of schedule" (trước tiến độ).', 'vocabulary', 'marketing'),
(234, 5, 'reading', 'Product quality has improved ___ since the new manager arrived.', '["significantly", "significant", "signify", "significance"]', 0, 'Cần trạng từ bổ nghĩa động từ "improved" → significantly.', 'word-forms', 'manufacturing'),
(235, 5, 'reading', 'The CEO, ___ vision transformed the startup, retired yesterday.', '["whose", "who", "which", "whom"]', 0, 'Quan hệ sở hữu (tầm nhìn của ông ấy) → whose.', 'relative-clauses', 'general'),
(236, 5, 'reading', 'Staff ___ wear ID badges at all times.', '["must", "should wearing", "can wears", "may to wear"]', 0, 'Must + V nguyên mẫu (bắt buộc đeo thẻ).', 'vocabulary', 'office'),
(237, 5, 'reading', 'The contract signing was postponed ___ the lawyer''s absence.', '["due to", "despite", "unless", "without"]', 0, '"Due to + lý do" (do luật sư vắng mặt).', 'conjunctions', 'contracts'),
(238, 5, 'reading', 'Our new software runs twice ___ the previous version.', '["as fast as", "fast", "fastest", "more fast"]', 0, 'So sánh bằng: "twice as fast as" (nhanh gấp đôi).', 'comparatives', 'it'),
(239, 5, 'reading', 'She suggested ___ the meeting to Thursday.', '["moving", "move", "moved", "moves"]', 0, '"Suggest + V-ing" (đề nghị dời họp).', 'gerunds', 'meetings')
ON CONFLICT (id) DO NOTHING;
