-- TOEIC bank expansion 2/5: +2 Part 6 texts (ids 240-247) + 6 Part 7 passages (ids 250-267).

-- Part 6, Text C: shipment email (passage 501)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(240, 6, 'reading', 'Your order ___ shipped yesterday afternoon.', '["was", "is", "has", "will"]', 0, 'Bị động quá khứ ("yesterday afternoon") → was shipped.', 'passive', 'logistics', 501, 'Dear customer,\n\nYour order ___ (240) shipped yesterday afternoon. You can track it ___ (241) our website. Delivery usually takes three to five ___ (242) days. ___ (243) you are not home, the driver will leave the package with a neighbor.\n\nThank you,\nFastShip'),
(241, 6, 'reading', 'You can track it ___ our website.', '["on", "at", "in", "to"]', 0, '"Track on a website" — theo dõi trên web.', 'prepositions', 'logistics', 501, 'Dear customer,\n\nYour order ___ (240) shipped yesterday afternoon. You can track it ___ (241) our website. Delivery usually takes three to five ___ (242) days. ___ (243) you are not home, the driver will leave the package with a neighbor.\n\nThank you,\nFastShip'),
(242, 6, 'reading', 'Delivery usually takes three to five ___ days.', '["business", "businesses", "businesslike", "busily"]', 0, 'Cụm "business days" (ngày làm việc) — business làm tính từ.', 'word-forms', 'logistics', 501, 'Dear customer,\n\nYour order ___ (240) shipped yesterday afternoon. You can track it ___ (241) our website. Delivery usually takes three to five ___ (242) days. ___ (243) you are not home, the driver will leave the package with a neighbor.\n\nThank you,\nFastShip'),
(243, 6, 'reading', '___ you are not home, the driver will leave the package with a neighbor.', '["If", "Unless", "Despite", "Without"]', 0, 'Điều kiện "If you are not home..." (nếu vắng nhà).', 'conjunctions', 'logistics', 501, 'Dear customer,\n\nYour order ___ (240) shipped yesterday afternoon. You can track it ___ (241) our website. Delivery usually takes three to five ___ (242) days. ___ (243) you are not home, the driver will leave the package with a neighbor.\n\nThank you,\nFastShip'),
-- Part 6, Text D: training invite (passage 502)
(244, 6, 'reading', 'We are pleased to invite you to a workshop ___ effective presentations.', '["on", "at", "to", "for"]', 0, '"Workshop on + chủ đề" (hội thảo về...).', 'prepositions', 'hr', 502, 'Dear colleagues,\n\nWe are pleased to invite you to a workshop ___ (244) effective presentations. The session ___ (245) place on Friday morning. Participants should bring ___ (246) laptops. Lunch ___ (247) provided at noon.\n\nPlease register by Wednesday.\nHR Department'),
(245, 6, 'reading', 'The session ___ place on Friday morning.', '["will take", "took", "taken", "taking"]', 0, '"Take place" (diễn ra) chia tương lai → will take place.', 'tenses', 'hr', 502, 'Dear colleagues,\n\nWe are pleased to invite you to a workshop ___ (244) effective presentations. The session ___ (245) place on Friday morning. Participants should bring ___ (246) laptops. Lunch ___ (247) provided at noon.\n\nPlease register by Wednesday.\nHR Department'),
(246, 6, 'reading', 'Participants should bring ___ laptops.', '["their", "they", "them", "theirs"]', 0, 'Cần tính từ sở hữu trước danh từ → their.', 'vocabulary', 'hr', 502, 'Dear colleagues,\n\nWe are pleased to invite you to a workshop ___ (244) effective presentations. The session ___ (245) place on Friday morning. Participants should bring ___ (246) laptops. Lunch ___ (247) provided at noon.\n\nPlease register by Wednesday.\nHR Department'),
(247, 6, 'reading', 'Lunch ___ provided at noon.', '["will be", "is", "was", "has"]', 0, 'Bị động tương lai (bữa trưa sẽ được phục vụ) → will be provided.', 'passive', 'hr', 502, 'Dear colleagues,\n\nWe are pleased to invite you to a workshop ___ (244) effective presentations. The session ___ (245) place on Friday morning. Participants should bring ___ (246) laptops. Lunch ___ (247) provided at noon.\n\nPlease register by Wednesday.\nHR Department')
ON CONFLICT (id) DO NOTHING;

-- Part 7, Passage 503: refund policy (ids 250-252)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(250, 7, 'reading', 'What is the notice about?', '["Returns and refunds", "New arrivals", "Job openings", "Holiday hours"]', 0, 'Thông báo quy định đổi/trả hàng.', 'comprehension', 'sales', 503, 'RETURN POLICY\n\nUnwanted items can be returned within 30 days with a receipt for a full refund. Clearance items are final sale. To start a return, visit our customer service counter with the item and receipt.'),
(251, 7, 'reading', 'How many days do customers have to return items?', '["30 days", "7 days", "14 days", "60 days"]', 0, '"...returned within 30 days...".', 'comprehension', 'sales', 503, 'RETURN POLICY\n\nUnwanted items can be returned within 30 days with a receipt for a full refund. Clearance items are final sale. To start a return, visit our customer service counter with the item and receipt.'),
(252, 7, 'reading', 'According to the notice, which items cannot be returned?', '["Clearance items", "Defective items", "Unwanted gifts", "Online orders"]', 0, '"Clearance items are final sale" (hàng xả kho không đổi trả).', 'comprehension', 'sales', 503, 'RETURN POLICY\n\nUnwanted items can be returned within 30 days with a receipt for a full refund. Clearance items are final sale. To start a return, visit our customer service counter with the item and receipt.'),
-- Part 7, Passage 504: interview invite (ids 253-255)
(253, 7, 'reading', 'What is the purpose of the email?', '["To invite someone to an interview", "To reject an application", "To announce a promotion", "To request documents"]', 0, 'Email mời phỏng vấn vị trí kế toán.', 'comprehension', 'hr', 504, 'Dear Ms. Nguyen,\n\nThank you for applying for the accountant position. We would like to invite you to an interview on Tuesday at 2 p.m. in Room 301. Please bring your ID and certificates. Reply to this email to confirm.\n\nBest regards,\nHR Team'),
(254, 7, 'reading', 'When is the interview?', '["Tuesday at 2 p.m.", "Monday at 9 a.m.", "Friday at 10 a.m.", "Wednesday at 3 p.m."]', 0, '"...interview on Tuesday at 2 p.m. in Room 301".', 'comprehension', 'hr', 504, 'Dear Ms. Nguyen,\n\nThank you for applying for the accountant position. We would like to invite you to an interview on Tuesday at 2 p.m. in Room 301. Please bring your ID and certificates. Reply to this email to confirm.\n\nBest regards,\nHR Team'),
(255, 7, 'reading', 'What should Ms. Nguyen bring?', '["ID and certificates", "A laptop", "Lunch", "A reference letter"]', 0, '"Please bring your ID and certificates".', 'comprehension', 'hr', 504, 'Dear Ms. Nguyen,\n\nThank you for applying for the accountant position. We would like to invite you to an interview on Tuesday at 2 p.m. in Room 301. Please bring your ID and certificates. Reply to this email to confirm.\n\nBest regards,\nHR Team'),
-- Part 7, Passage 505: sale flyer (ids 256-258)
(256, 7, 'reading', 'What is on sale this weekend?', '["Office furniture", "Laptops", "Winter coats", "Plane tickets"]', 0, 'Xả kho nội thất văn phòng giảm đến 40%.', 'comprehension', 'sales', 505, 'WEEKEND SALE\nOfficePlus\n\nThis Saturday and Sunday only: up to 40% off all office furniture. Desks, chairs, and cabinets at unbeatable prices. Free delivery for purchases over $200. Store opens at 8 a.m.'),
(257, 7, 'reading', 'When does the sale take place?', '["Saturday and Sunday", "Monday to Friday", "The whole month", "Friday evening"]', 0, '"This Saturday and Sunday only".', 'comprehension', 'sales', 505, 'WEEKEND SALE\nOfficePlus\n\nThis Saturday and Sunday only: up to 40% off all office furniture. Desks, chairs, and cabinets at unbeatable prices. Free delivery for purchases over $200. Store opens at 8 a.m.'),
(258, 7, 'reading', 'What must customers spend for free delivery?', '["Over $200", "Over $50", "Over $100", "Over $500"]', 0, '"Free delivery for purchases over $200".', 'comprehension', 'sales', 505, 'WEEKEND SALE\nOfficePlus\n\nThis Saturday and Sunday only: up to 40% off all office furniture. Desks, chairs, and cabinets at unbeatable prices. Free delivery for purchases over $200. Store opens at 8 a.m.'),
-- Part 7, Passage 506: safety memo (ids 259-261)
(259, 7, 'reading', 'What is the memo about?', '["Fire drill procedures", "New salaries", "Holiday schedule", "Canteen menu"]', 0, 'Memo hướng dẫn diễn tập phòng cháy.', 'comprehension', 'office', 506, 'SAFETY MEMO\n\nA fire drill will be held this Thursday at 10 a.m. When the alarm sounds, leave your belongings and use the stairs — never the elevator. Gather at the parking lot and wait for instructions from the safety team.'),
(260, 7, 'reading', 'What should staff NOT do during the drill?', '["Use the elevator", "Leave belongings", "Use the stairs", "Gather outside"]', 0, '"...use the stairs — never the elevator".', 'comprehension', 'office', 506, 'SAFETY MEMO\n\nA fire drill will be held this Thursday at 10 a.m. When the alarm sounds, leave your belongings and use the stairs — never the elevator. Gather at the parking lot and wait for instructions from the safety team.'),
(261, 7, 'reading', 'Where should staff gather?', '["At the parking lot", "In the lobby", "On the roof", "At the gate"]', 0, '"Gather at the parking lot...".', 'comprehension', 'office', 506, 'SAFETY MEMO\n\nA fire drill will be held this Thursday at 10 a.m. When the alarm sounds, leave your belongings and use the stairs — never the elevator. Gather at the parking lot and wait for instructions from the safety team.'),
-- Part 7, Passage 507: recall notice (ids 262-264)
(262, 7, 'reading', 'Which product is being recalled?', '["TK-200 electric kettles", "TK-200 toasters", "TK-500 kettles", "All kitchen appliances"]', 0, 'Thu hồi ấm điện mẫu TK-200 do lỗi công tắc.', 'comprehension', 'manufacturing', 507, 'PRODUCT RECALL\n\nBrightHome is recalling TK-200 electric kettles sold between January and March due to a faulty switch. Customers should stop using the kettle immediately and return it to any store for a full refund. For questions, call 1-800-555-0199.'),
(263, 7, 'reading', 'What should customers do?', '["Stop using it and return it", "Repair it themselves", "Throw it away", "Wait for a letter"]', 0, '"...stop using the kettle immediately and return it...".', 'comprehension', 'manufacturing', 507, 'PRODUCT RECALL\n\nBrightHome is recalling TK-200 electric kettles sold between January and March due to a faulty switch. Customers should stop using the kettle immediately and return it to any store for a full refund. For questions, call 1-800-555-0199.'),
(264, 7, 'reading', 'Why was the product recalled?', '["A faulty switch", "A broken handle", "Missing parts", "Wrong color"]', 0, '"...due to a faulty switch".', 'comprehension', 'manufacturing', 507, 'PRODUCT RECALL\n\nBrightHome is recalling TK-200 electric kettles sold between January and March due to a faulty switch. Customers should stop using the kettle immediately and return it to any store for a full refund. For questions, call 1-800-555-0199.'),
-- Part 7, Passage 508: conference agenda (ids 265-267)
(265, 7, 'reading', 'What event is described?', '["A business conference", "A wedding", "A football match", "A cooking class"]', 0, 'Chương trình hội nghị kinh doanh 2 ngày.', 'comprehension', 'meetings', 508, 'ASIA BUSINESS CONFERENCE — DAY 1\n\n9:00 Opening speech by CEO Tran\n10:30 Panel: Digital Marketing Trends\n12:00 Lunch at Riverside Restaurant\n2:00 Workshop: Negotiation Skills\nRegistration: $150, includes lunch and materials.'),
(266, 7, 'reading', 'What happens at 10:30?', '["A panel on marketing trends", "Lunch", "A workshop", "An opening speech"]', 0, '"10:30 Panel: Digital Marketing Trends".', 'comprehension', 'meetings', 508, 'ASIA BUSINESS CONFERENCE — DAY 1\n\n9:00 Opening speech by CEO Tran\n10:30 Panel: Digital Marketing Trends\n12:00 Lunch at Riverside Restaurant\n2:00 Workshop: Negotiation Skills\nRegistration: $150, includes lunch and materials.'),
(267, 7, 'reading', 'How much is registration?', '["$150", "$100", "$200", "Free"]', 0, '"Registration: $150, includes lunch and materials".', 'comprehension', 'meetings', 508, 'ASIA BUSINESS CONFERENCE — DAY 1\n\n9:00 Opening speech by CEO Tran\n10:30 Panel: Digital Marketing Trends\n12:00 Lunch at Riverside Restaurant\n2:00 Workshop: Negotiation Skills\nRegistration: $150, includes lunch and materials.')
ON CONFLICT (id) DO NOTHING;
