-- TOEIC bank expansion 3/5: +10 Part 1 photos (ids 270-279) + 20 Part 2 Q-R (ids 280-299).

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, transcript, audio_text) VALUES
(270, 1, 'listening', 'Bức ảnh: đầu bếp đang thái rau trong bếp nhà hàng.', '["A chef is chopping vegetables.", "A chef is driving.", "A chef is sleeping.", "A chef is swimming."]', 0, 'Thái rau trong bếp → chopping vegetables.', 'photo', 'general', 'A chef is chopping vegetables.', 'A. A chef is chopping vegetables. B. A chef is driving. C. A chef is sleeping. D. A chef is swimming.'),
(271, 1, 'listening', 'Bức ảnh: hai người đang bắt tay trước tòa nhà văn phòng.', '["They are shaking hands.", "They are fighting.", "They are running.", "They are crying."]', 0, 'Bắt tay → shaking hands.', 'photo', 'office', 'They are shaking hands.', 'A. They are shaking hands. B. They are fighting. C. They are running. D. They are crying.'),
(272, 1, 'listening', 'Bức ảnh: máy bay đang cất cánh khỏi đường băng lúc hoàng hôn.', '["A plane is taking off.", "A plane is landing on water.", "A plane is parking.", "A plane is sinking."]', 0, 'Cất cánh → taking off.', 'photo', 'travel', 'A plane is taking off.', 'A. A plane is taking off. B. A plane is landing on water. C. A plane is parking. D. A plane is sinking.'),
(273, 1, 'listening', 'Bức ảnh: khách hàng đang xếp hàng trước quầy thu ngân siêu thị.', '["Customers are waiting in line.", "Customers are dancing.", "Customers are leaving.", "Customers are cooking."]', 0, 'Xếp hàng chờ thanh toán → waiting in line.', 'photo', 'sales', 'Customers are waiting in line.', 'A. Customers are waiting in line. B. Customers are dancing. C. Customers are leaving. D. Customers are cooking.'),
(274, 1, 'listening', 'Bức ảnh: kỹ sư đội mũ bảo hộ đang kiểm tra máy móc trong nhà xưởng.', '["An engineer is inspecting equipment.", "An engineer is sleeping.", "An engineer is swimming.", "An engineer is singing."]', 0, 'Kiểm tra thiết bị → inspecting equipment.', 'photo', 'manufacturing', 'An engineer is inspecting equipment.', 'A. An engineer is inspecting equipment. B. An engineer is sleeping. C. An engineer is swimming. D. An engineer is singing.'),
(275, 1, 'listening', 'Bức ảnh: mọi người đang lên xe buýt ở bến xe.', '["People are boarding a bus.", "People are exiting a plane.", "People are riding bikes.", "People are entering a shop."]', 0, 'Lên xe buýt → boarding a bus.', 'photo', 'travel', 'People are boarding a bus.', 'A. People are boarding a bus. B. People are exiting a plane. C. People are riding bikes. D. People are entering a shop.'),
(276, 1, 'listening', 'Bức ảnh: nhân viên đang sắp xếp tài liệu lên kệ.', '["She is filing documents.", "She is watering plants.", "She is painting a wall.", "She is fixing a car."]', 0, 'Sắp xếp hồ sơ → filing documents.', 'photo', 'office', 'She is filing documents.', 'A. She is filing documents. B. She is watering plants. C. She is painting a wall. D. She is fixing a car.'),
(277, 1, 'listening', 'Bức ảnh: xe tải giao hàng đang đỗ trước kho.', '["A truck is parked outside.", "A truck is moving fast.", "A truck is on fire.", "A truck is flying."]', 0, 'Đỗ trước kho → parked outside.', 'photo', 'logistics', 'A truck is parked outside.', 'A. A truck is parked outside. B. A truck is moving fast. C. A truck is on fire. D. A truck is flying.'),
(278, 1, 'listening', 'Bức ảnh: diễn giả đang thuyết trình trước khán phòng đông người.', '["A speaker is giving a presentation.", "A speaker is cleaning.", "A speaker is eating.", "A speaker is leaving."]', 0, 'Thuyết trình → giving a presentation.', 'photo', 'meetings', 'A speaker is giving a presentation.', 'A. A speaker is sleeping. B. A speaker is sleeping. C. A speaker is eating. D. A speaker is leaving.'),
(279, 1, 'listening', 'Bức ảnh: khách du lịch đang chụp ảnh trước tháp đồng hồ.', '["Tourists are taking photos.", "Tourists are working.", "Tourists are studying.", "Tourists are cooking."]', 0, 'Chụp ảnh → taking photos.', 'photo', 'travel', 'Tourists are taking photos.', 'A. Tourists are taking photos. B. Tourists are working. C. Tourists are studying. D. Tourists are cooking.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, transcript, audio_text) VALUES
(280, 2, 'listening', 'When does the bank open?', '["At 8 a.m.", "On Main Street.", "Two tellers."]', 0, 'Hỏi when → đáp án giờ giấc.', 'wh-question', 'finance', 'When does the bank open? At 8 a.m.', 'When does the bank open? A. At 8 a.m. B. On Main Street. C. Two tellers.'),
(281, 2, 'listening', 'Who approved the travel request?', '["Mr. Davis did.", "Next Monday.", "By email."]', 0, 'Hỏi who → đáp án chỉ người.', 'wh-question', 'travel', 'Who approved the travel request? Mr. Davis did.', 'Who approved the travel request? A. Mr. Davis did. B. Next Monday. C. By email.'),
(282, 2, 'listening', 'The copier on the third floor is broken again.', '["I''ll call maintenance.", "Yes, it copies well.", "The third floor is nice."]', 0, 'Báo sự cố → đề nghị gọi bảo trì.', 'statement', 'office', 'The copier on the third floor is broken again. I will call maintenance.', 'The copier on the third floor is broken again. A. I will call maintenance. B. Yes, it copies well. C. The third floor is nice.'),
(283, 2, 'listening', 'How much is the registration fee?', '["Fifty dollars.", "Two days.", "In cash."]', 0, 'Hỏi how much → đáp án số tiền.', 'wh-question', 'meetings', 'How much is the registration fee? Fifty dollars.', 'How much is the registration fee? A. Fifty dollars. B. Two days. C. In cash.'),
(284, 2, 'listening', 'Have you met our new designer?', '["Not yet, please introduce us.", "No, I hate design.", "The designer is tall."]', 0, 'Hỏi Yes/No → "Not yet" + đề nghị giới thiệu.', 'yes-no', 'hr', 'Have you met our new designer? Not yet, please introduce us.', 'Have you met our new designer? A. Not yet, please introduce us. B. No, I hate design. C. The designer is tall.'),
(285, 2, 'listening', 'Why don''t we order lunch for the team?', '["Good idea, I''m hungry.", "At noon.", "The team is big."]', 0, 'Đề xuất → đồng tình "Good idea".', 'suggestion', 'office', 'Why don''t we order lunch for the team? Good idea, I am hungry.', 'Why don''t we order lunch for the team? A. Good idea, I am hungry. B. At noon. C. The team is big.'),
(286, 2, 'listening', 'Where did you put the contract copies?', '["In the top drawer.", "Yesterday.", "Three copies."]', 0, 'Hỏi where → đáp án vị trí.', 'wh-question', 'contracts', 'Where did you put the contract copies? In the top drawer.', 'Where did you put the contract copies? A. In the top drawer. B. Yesterday. C. Three copies.'),
(287, 2, 'listening', 'The elevators will be serviced this weekend.', '["Thanks for letting me know.", "No, they are new.", "The weekend is short."]', 0, 'Thông báo → cảm ơn + ghi nhận.', 'statement', 'office', 'The elevators will be serviced this weekend. Thanks for letting me know.', 'The elevators will be serviced this weekend. A. Thanks for letting me know. B. No, they are new. C. The weekend is short.'),
(288, 2, 'listening', 'Should I confirm the booking by phone?', '["Yes, that would be best.", "No, I booked yesterday.", "The phone is ringing."]', 0, 'Xin lời khuyên → "Yes, that would be best".', 'offer', 'travel', 'Should I confirm the booking by phone? Yes, that would be best.', 'Should I confirm the booking by phone? A. Yes, that would be best. B. No, I booked yesterday. C. The phone is ringing.'),
(289, 2, 'listening', 'How often do inventory checks happen?', '["Once a month.", "For a week.", "Very carefully."]', 0, 'Hỏi how often → tần suất "Once a month".', 'wh-question', 'logistics', 'How often do inventory checks happen? Once a month.', 'How often do inventory checks happen? A. Once a month. B. For a week. C. Very carefully.'),
(290, 2, 'listening', 'Ms. Park can''t attend the workshop, can she?', '["No, she has another meeting.", "Yes, she loves workshops.", "The workshop is useful."]', 0, 'Câu hỏi đuôi phủ định → xác nhận "No, she has...".', 'tag-question', 'hr', 'Ms. Park can not attend the workshop, can she? No, she has another meeting.', 'Ms. Park can not attend the workshop, can she? A. No, she has another meeting. B. Yes, she loves workshops. C. The workshop is useful.'),
(291, 2, 'listening', 'Would you mind closing the window?', '["Not at all.", "Yes, I mind it.", "The window is clean."]', 0, 'Nhờ vả lịch sự → "Not at all" (sẵn lòng).', 'request', 'office', 'Would you mind closing the window? Not at all.', 'Would you mind closing the window? A. Not at all. B. Yes, I mind it. C. The window is clean.'),
(292, 2, 'listening', 'Our biggest client just renewed the contract.', '["That''s great news!", "No, they canceled.", "Contracts are long."]', 0, 'Tin tốt → chúc mừng "That''s great news!".', 'statement', 'sales', 'Our biggest client just renewed the contract. That is great news!', 'Our biggest client just renewed the contract. A. That is great news! B. No, they canceled. C. Contracts are long.'),
(293, 2, 'listening', 'Which platform should we use for the webinar?', '["Zoom works best for us.", "Next Thursday.", "Fifty people."]', 0, 'Hỏi which → chọn 1 trong các lựa chọn.', 'wh-question', 'it', 'Which platform should we use for the webinar? Zoom works best for us.', 'Which platform should we use for the webinar? A. Zoom works best for us. B. Next Thursday. C. Fifty people.'),
(294, 2, 'listening', 'Don''t forget to lock the storage room.', '["I won''t, thanks.", "No, it is open.", "The room is big."]', 0, 'Nhắc nhở → hứa "I won''t (forget)".', 'request', 'logistics', 'Do not forget to lock the storage room. I will not, thanks.', 'Do not forget to lock the storage room. A. I will not, thanks. B. No, it is open. C. The room is big.'),
(295, 2, 'listening', 'How was your business trip to Hanoi?', '["Productive, thanks.", "By plane.", "For three days."]', 0, 'Hỏi cảm nhận → "Productive, thanks".', 'wh-question', 'travel', 'How was your business trip to Hanoi? Productive, thanks.', 'How was your business trip to Hanoi? A. Productive, thanks. B. By plane. C. For three days.'),
(296, 2, 'listening', 'Let''s review the agenda before we start.', '["Good idea.", "No, I disagree strongly.", "The agenda is paper."]', 0, 'Đề xuất Let''s → đồng tình "Good idea".', 'suggestion', 'meetings', 'Let us review the agenda before we start. Good idea.', 'Let us review the agenda before we start. A. Good idea. B. No, I disagree strongly. C. The agenda is paper.'),
(297, 2, 'listening', 'When is the deadline for expense claims?', '["The end of the month.", "At headquarters.", "My manager."]', 0, 'Hỏi when → mốc thời gian.', 'wh-question', 'finance', 'When is the deadline for expense claims? The end of the month.', 'When is the deadline for expense claims? A. The end of the month. B. At headquarters. C. My manager.'),
(298, 2, 'listening', 'I left my badge at home this morning.', '["You can get a temporary one.", "No, badges are free.", "Home is far."]', 0, 'Kể sự cố → giải pháp "temporary one".', 'statement', 'office', 'I left my badge at home this morning. You can get a temporary one.', 'I left my badge at home this morning. A. You can get a temporary one. B. No, badges are free. C. Home is far.'),
(299, 2, 'listening', 'Shall we schedule a follow-up call?', '["Thursday works for me.", "No, I called yesterday.", "Calls are short."]', 0, 'Đề xuất Shall we → chọn thời gian "Thursday works".', 'suggestion', 'meetings', 'Shall we schedule a follow-up call? Thursday works for me.', 'Shall we schedule a follow-up call? A. Thursday works for me. B. No, I called yesterday. C. Calls are short.')
ON CONFLICT (id) DO NOTHING;
