-- TOEIC bank expansion 4/5: +4 Part 3 conversations (ids 300-311, passages 601-604)
-- + 4 Part 4 talks (ids 312-323, passages 605-608).

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, transcript) VALUES
(300, 3, 'listening', 'What does the woman want?', '["To change her flight", "To cancel a hotel", "To rent a car", "To buy a ticket"]', 0, 'Cô ấy muốn đổi chuyến bay sang sáng mai.', 'main-idea', 'travel', 601, 'Woman: Hi, I need to change my flight to an earlier one.\nMan: Let me check. There is a seat on the 8 a.m. flight tomorrow.\nWoman: Perfect. Is there an extra charge?\nMan: No, your ticket is flexible.'),
(301, 3, 'listening', 'What flight does the man offer?', '["The 8 a.m. flight", "The 6 p.m. flight", "The midnight flight", "The noon flight"]', 0, '"...a seat on the 8 a.m. flight tomorrow".', 'detail', 'travel', 601, 'Woman: Hi, I need to change my flight to an earlier one.\nMan: Let me check. There is a seat on the 8 a.m. flight tomorrow.\nWoman: Perfect. Is there an extra charge?\nMan: No, your ticket is flexible.'),
(302, 3, 'listening', 'What does the man say about the charge?', '["There is none", "It is fifty dollars", "It is very high", "He does not know"]', 0, '"No, your ticket is flexible" (không mất phí).', 'detail', 'travel', 601, 'Woman: Hi, I need to change my flight to an earlier one.\nMan: Let me check. There is a seat on the 8 a.m. flight tomorrow.\nWoman: Perfect. Is there an extra charge?\nMan: No, your ticket is flexible.'),
(303, 3, 'listening', 'What are they planning?', '["A farewell party", "A product launch", "A training course", "A business trip"]', 0, 'Họ bàn tiệc chia tay cho đồng nghiệp nghỉ hưu.', 'main-idea', 'office', 602, 'Man: Lisa is retiring next Friday. Shall we organize something?\nWoman: A farewell party sounds nice. How about the meeting room after work?\nMan: Great. I will order food and drinks.\nWoman: And I will prepare a card for everyone to sign.'),
(304, 3, 'listening', 'Where will the event be held?', '["In the meeting room", "At a restaurant", "At home", "In the lobby"]', 0, '"...the meeting room after work".', 'detail', 'office', 602, 'Man: Lisa is retiring next Friday. Shall we organize something?\nWoman: A farewell party sounds nice. How about the meeting room after work?\nMan: Great. I will order food and drinks.\nWoman: And I will prepare a card for everyone to sign.'),
(305, 3, 'listening', 'What will the woman do?', '["Prepare a card", "Order food", "Book a room", "Send invitations"]', 0, '"...prepare a card for everyone to sign".', 'detail', 'office', 602, 'Man: Lisa is retiring next Friday. Shall we organize something?\nWoman: A farewell party sounds nice. How about the meeting room after work?\nMan: Great. I will order food and drinks.\nWoman: And I will prepare a card for everyone to sign.'),
(306, 3, 'listening', 'Why is the woman calling?', '["To report a broken printer", "To order paper", "To ask for a refund", "To apply for a job"]', 0, 'Cô ấy báo máy in tầng 2 bị kẹt giấy.', 'main-idea', 'support', 603, 'Woman: Hello, the printer on the second floor is jammed again.\nMan: I am sorry. A technician will come this afternoon.\nWoman: Could you also bring extra paper?\nMan: Of course. Anything else?'),
(307, 3, 'listening', 'What will the man do?', '["Send a technician", "Bring a new printer", "Call the manager", "Cancel the order"]', 0, '"A technician will come this afternoon".', 'detail', 'support', 603, 'Woman: Hello, the printer on the second floor is jammed again.\nMan: I am sorry. A technician will come this afternoon.\nWoman: Could you also bring extra paper?\nMan: Of course. Anything else?'),
(308, 3, 'listening', 'What else does the woman request?', '["Extra paper", "A new cable", "A refund", "Training"]', 0, '"Could you also bring extra paper?"', 'detail', 'support', 603, 'Woman: Hello, the printer on the second floor is jammed again.\nMan: I am sorry. A technician will come this afternoon.\nWoman: Could you also bring extra paper?\nMan: Of course. Anything else?'),
(309, 3, 'listening', 'What did the man buy?', '["A new laptop", "A new phone", "A new car", "A new desk"]', 0, 'Anh ấy vừa mua laptop mới giảm giá.', 'main-idea', 'it', 604, 'Man: I just bought a new laptop. It was on sale.\nWoman: Nice! Which brand did you choose?\nMan: A ZenBook. It is light and fast.\nWoman: Good choice. I have the same one.'),
(310, 3, 'listening', 'Which brand did he choose?', '["ZenBook", "ThinkPad", "MacBook", "Dell"]', 0, '"A ZenBook. It is light and fast".', 'detail', 'it', 604, 'Man: I just bought a new laptop. It was on sale.\nWoman: Nice! Which brand did you choose?\nMan: A ZenBook. It is light and fast.\nWoman: Good choice. I have the same one.'),
(311, 3, 'listening', 'What does the woman think?', '["It is a good choice", "It is too expensive", "It is too heavy", "It is outdated"]', 0, '"Good choice. I have the same one".', 'detail', 'it', 604, 'Man: I just bought a new laptop. It was on sale.\nWoman: Nice! Which brand did you choose?\nMan: A ZenBook. It is light and fast.\nWoman: Good choice. I have the same one.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, transcript) VALUES
(312, 4, 'listening', 'Who is speaking?', '["A store manager", "A pilot", "A teacher", "A doctor"]', 0, 'Quản lý cửa hàng thông báo giờ mở cửa mới.', 'main-idea', 'sales', 605, 'Hello everyone, this is Karen, the store manager. Starting Monday, our store will open one hour earlier, at 8 a.m. Evening hours stay the same. Thank you for your attention!'),
(313, 4, 'listening', 'What is changing?', '["Opening hours", "Prices", "Staff uniforms", "The location"]', 0, 'Cửa hàng mở sớm hơn 1 tiếng từ thứ Hai.', 'detail', 'sales', 605, 'Hello everyone, this is Karen, the store manager. Starting Monday, our store will open one hour earlier, at 8 a.m. Evening hours stay the same. Thank you for your attention!'),
(314, 4, 'listening', 'What time will the store open?', '["8 a.m.", "9 a.m.", "7 a.m.", "10 a.m."]', 0, '"...open one hour earlier, at 8 a.m.".', 'detail', 'sales', 605, 'Hello everyone, this is Karen, the store manager. Starting Monday, our store will open one hour earlier, at 8 a.m. Evening hours stay the same. Thank you for your attention!'),
(315, 4, 'listening', 'What delayed the train?', '["Heavy snow", "A strike", "An accident", "Road works"]', 0, 'Tuyết lớn làm tàu trễ 30 phút.', 'main-idea', 'travel', 606, 'Dear passengers, due to heavy snow, the 7:30 express to Kyoto is delayed by about 30 minutes. Please stay behind the yellow line. We apologize for the inconvenience and thank you for your patience.'),
(316, 4, 'listening', 'How long is the delay?', '["About 30 minutes", "About 10 minutes", "About an hour", "About 2 hours"]', 0, '"...delayed by about 30 minutes".', 'detail', 'travel', 606, 'Dear passengers, due to heavy snow, the 7:30 express to Kyoto is delayed by about 30 minutes. Please stay behind the yellow line. We apologize for the inconvenience and thank you for your patience.'),
(317, 4, 'listening', 'What are passengers asked to do?', '["Stay behind the yellow line", "Leave the platform", "Show tickets", "Move to another train"]', 0, '"Please stay behind the yellow line".', 'detail', 'travel', 606, 'Dear passengers, due to heavy snow, the 7:30 express to Kyoto is delayed by about 30 minutes. Please stay behind the yellow line. We apologize for the inconvenience and thank you for your patience.'),
(318, 4, 'listening', 'What is the call about?', '["A job offer", "A wrong number", "A sales call", "A survey"]', 0, 'Gọi báo trúng tuyển vị trí trợ lý.', 'main-idea', 'hr', 607, 'Hello, this is Maria from Bright HR. I am calling to offer you the assistant position starting June 1st. Your monthly salary will be $2,500. Please reply by Friday if you accept. Congratulations!'),
(319, 4, 'listening', 'When does the job start?', '["June 1st", "May 1st", "July 1st", "Immediately"]', 0, '"...starting June 1st".', 'detail', 'hr', 607, 'Hello, this is Maria from Bright HR. I am calling to offer you the assistant position starting June 1st. Your monthly salary will be $2,500. Please reply by Friday if you accept. Congratulations!'),
(320, 4, 'listening', 'What must the listener do by Friday?', '["Reply to accept", "Send documents", "Attend training", "Pay a fee"]', 0, '"Please reply by Friday if you accept".', 'detail', 'hr', 607, 'Hello, this is Maria from Bright HR. I am calling to offer you the assistant position starting June 1st. Your monthly salary will be $2,500. Please reply by Friday if you accept. Congratulations!'),
(321, 4, 'listening', 'What is being advertised?', '["A gym membership", "A new phone", "A car", "A course"]', 0, 'Quảng cáo gói tập gym giảm 30% tháng đầu.', 'main-idea', 'general', 608, 'Are you looking to get fit? Join FitLife Gym this month and get 30 percent off your first three months. Our new branch on Park Street has a swimming pool, yoga classes, and personal trainers. Sign up online today!'),
(322, 4, 'listening', 'What is the discount?', '["30 percent off three months", "50 percent off one month", "Free one year", "10 percent off"]', 0, '"...30 percent off your first three months".', 'detail', 'general', 608, 'Are you looking to get fit? Join FitLife Gym this month and get 30 percent off your first three months. Our new branch on Park Street has a swimming pool, yoga classes, and personal trainers. Sign up online today!'),
(323, 4, 'listening', 'How can listeners sign up?', '["Online", "By phone", "In person only", "By mail"]', 0, '"Sign up online today!".', 'detail', 'general', 608, 'Are you looking to get fit? Join FitLife Gym this month and get 30 percent off your first three months. Our new branch on Park Street has a swimming pool, yoga classes, and personal trainers. Sign up online today!')
ON CONFLICT (id) DO NOTHING;

UPDATE toeic_questions SET audio_text = transcript WHERE id BETWEEN 300 AND 323 AND audio_text IS NULL;
