-- TOEIC bank expansion 6/6: +7 Part 3 convs (ids 400-420), +4 Part 4 talks
-- (ids 421-432), +2 Part 7 passages (ids 433-438). audio_text = transcript.

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, transcript) VALUES
(400, 3, 'listening', 'What does the man want to book?', '["A hotel room", "A flight", "A taxi", "A table"]', 0, 'Anh ấy muốn đặt phòng khách sạn 2 đêm.', 'main-idea', 'travel', 620, 'Man: Hello, I would like to book a room for two nights.\nWoman: Certainly. When will you arrive?\nMan: This Friday. Do you have free Wi-Fi?\nWoman: Yes, and breakfast is included.'),
(401, 3, 'listening', 'What does the woman ask?', '["The arrival date", "His name", "His passport", "His age"]', 0, '"When will you arrive?"', 'detail', 'travel', 620, 'Man: Hello, I would like to book a room for two nights.\nWoman: Certainly. When will you arrive?\nMan: This Friday. Do you have free Wi-Fi?\nWoman: Yes, and breakfast is included.'),
(402, 3, 'listening', 'What is included?', '["Breakfast and Wi-Fi", "Lunch", "Airport pickup", "Spa access"]', 0, '"...free Wi-Fi... breakfast is included".', 'detail', 'travel', 620, 'Man: Hello, I would like to book a room for two nights.\nWoman: Certainly. When will you arrive?\nMan: This Friday. Do you have free Wi-Fi?\nWoman: Yes, and breakfast is included.'),
(403, 3, 'listening', 'Why is the woman calling the technician?', '["The AC is broken", "The lights are off", "The door is stuck", "The computer crashed"]', 0, 'Điều hòa phòng họp bị hỏng.', 'main-idea', 'office', 621, 'Woman: Hi, the air conditioner in the meeting room is not working.\nMan: I will send someone within an hour.\nWoman: Thanks. The meeting starts at two.\nMan: We will fix it in time, I promise.'),
(404, 3, 'listening', 'When does the meeting start?', '["At two", "At three", "At noon", "At ten"]', 0, '"The meeting starts at two".', 'detail', 'office', 621, 'Woman: Hi, the air conditioner in the meeting room is not working.\nMan: I will send someone within an hour.\nWoman: Thanks. The meeting starts at two.\nMan: We will fix it in time, I promise.'),
(405, 3, 'listening', 'What does the man promise?', '["To fix it in time", "A new AC", "A discount", "To cancel"]', 0, '"We will fix it in time, I promise".', 'detail', 'office', 621, 'Woman: Hi, the air conditioner in the meeting room is not working.\nMan: I will send someone within an hour.\nWoman: Thanks. The meeting starts at two.\nMan: We will fix it in time, I promise.'),
(406, 3, 'listening', 'What are they discussing?', '["A restaurant reservation", "A flight delay", "A lost wallet", "A broken phone"]', 0, 'Họ đặt bàn nhà hàng cho 6 người.', 'main-idea', 'general', 622, 'Woman: I would like to reserve a table for six tonight.\nMan: Certainly. What time would you prefer?\nWoman: Around seven. Do you have a quiet corner?\nMan: Yes, I will save the table by the window.'),
(407, 3, 'listening', 'What time do they want?', '["Around seven", "At noon", "At nine", "At six"]', 0, '"Around seven".', 'detail', 'general', 622, 'Woman: I would like to reserve a table for six tonight.\nMan: Certainly. What time would you prefer?\nWoman: Around seven. Do you have a quiet corner?\nMan: Yes, I will save the table by the window.'),
(408, 3, 'listening', 'Where will they sit?', '["By the window", "Outside", "Near the bar", "Upstairs"]', 0, '"...save the table by the window".', 'detail', 'general', 622, 'Woman: I would like to reserve a table for six tonight.\nMan: Certainly. What time would you prefer?\nWoman: Around seven. Do you have a quiet corner?\nMan: Yes, I will save the table by the window.'),
(409, 3, 'listening', 'What is the man worried about?', '["Learning new software", "Losing his job", "A presentation", "A business trip"]', 0, 'Anh ấy lo phải học phần mềm mới trước thứ Hai.', 'main-idea', 'it', 623, 'Man: I have to learn the new accounting software by Monday.\nWoman: Don''t worry. There is a training video online.\nMan: How long is it?\nWoman: Only thirty minutes, and you can pause anytime.'),
(410, 3, 'listening', 'What does the woman suggest?', '["An online training video", "A book", "A course abroad", "Asking the boss"]', 0, '"There is a training video online".', 'detail', 'it', 623, 'Man: I have to learn the new accounting software by Monday.\nWoman: Don''t worry. There is a training video online.\nMan: How long is it?\nWoman: Only thirty minutes, and you can pause anytime.'),
(411, 3, 'listening', 'How long is the video?', '["Thirty minutes", "One hour", "Ten minutes", "Two hours"]', 0, '"Only thirty minutes...".', 'detail', 'it', 623, 'Man: I have to learn the new accounting software by Monday.\nWoman: Don''t worry. There is a training video online.\nMan: How long is it?\nWoman: Only thirty minutes, and you can pause anytime.'),
(412, 3, 'listening', 'What does the woman want to rent?', '["A car", "A bike", "A boat", "A house"]', 0, 'Cô ấy muốn thuê xe 3 ngày.', 'main-idea', 'travel', 624, 'Woman: I need to rent a car for three days.\nMan: We have a compact car available. Do you need GPS?\nWoman: Yes, please. How much is it per day?\nMan: Forty dollars, including insurance.'),
(413, 3, 'listening', 'How long does she need it?', '["Three days", "One day", "A week", "One month"]', 0, '"...for three days".', 'detail', 'travel', 624, 'Woman: I need to rent a car for three days.\nMan: We have a compact car available. Do you need GPS?\nWoman: Yes, please. How much is it per day?\nMan: Forty dollars, including insurance.'),
(414, 3, 'listening', 'How much per day?', '["Forty dollars", "Thirty dollars", "Fifty dollars", "Twenty dollars"]', 0, '"Forty dollars, including insurance".', 'detail', 'travel', 624, 'Woman: I need to rent a car for three days.\nMan: We have a compact car available. Do you need GPS?\nWoman: Yes, please. How much is it per day?\nMan: Forty dollars, including insurance.'),
(415, 3, 'listening', 'What are they talking about?', '["A conference", "A wedding", "A concert", "A match"]', 0, 'Họ bàn việc đăng ký hội nghị công nghệ.', 'main-idea', 'meetings', 625, 'Man: Have you registered for the tech conference yet?\nWoman: Not yet. When is the deadline?\nMan: This Friday. The early fee is much cheaper.\nWoman: Then I will sign up today.'),
(416, 3, 'listening', 'When is the deadline?', '["This Friday", "Next Monday", "Tomorrow", "Next month"]', 0, '"When is the deadline? ... This Friday".', 'detail', 'meetings', 625, 'Man: Have you registered for the tech conference yet?\nWoman: Not yet. When is the deadline?\nMan: This Friday. The early fee is much cheaper.\nWoman: Then I will sign up today.'),
(417, 3, 'listening', 'What will the woman do?', '["Sign up today", "Wait a month", "Ask her boss", "Skip it"]', 0, '"Then I will sign up today".', 'detail', 'meetings', 625, 'Man: Have you registered for the tech conference yet?\nWoman: Not yet. When is the deadline?\nMan: This Friday. The early fee is much cheaper.\nWoman: Then I will sign up today.'),
(418, 3, 'listening', 'What does the man invite her to?', '["A product demo", "A dinner", "A movie", "A sports game"]', 0, 'Mời xem demo sản phẩm mới chiều mai.', 'main-idea', 'sales', 626, 'Man: Would you like to see a demo of our new product tomorrow afternoon?\nWoman: Sure. What time works for you?\nMan: How about three o''clock at our office?\nWoman: Perfect. See you then.'),
(419, 3, 'listening', 'When is the demo?', '["Tomorrow at three", "Today at five", "Next week", "Tonight"]', 0, '"...tomorrow afternoon... three o''clock".', 'detail', 'sales', 626, 'Man: Would you like to see a demo of our new product tomorrow afternoon?\nWoman: Sure. What time works for you?\nMan: How about three o''clock at our office?\nWoman: Perfect. See you then.'),
(420, 3, 'listening', 'Where will they meet?', '["At his office", "At her home", "At a cafe", "Online"]', 0, '"...at our office".', 'detail', 'sales', 626, 'Man: Would you like to see a demo of our new product tomorrow afternoon?\nWoman: Sure. What time works for you?\nMan: How about three o''clock at our office?\nWoman: Perfect. See you then.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, transcript) VALUES
(421, 4, 'listening', 'What is closed today?', '["The swimming pool", "The gym", "The library", "The cafe"]', 0, 'Hồ bơi đóng để bảo trì.', 'main-idea', 'general', 627, 'Attention, members! Our swimming pool is closed today for maintenance. It will reopen tomorrow morning. The gym and all classes continue as normal. Thank you for your understanding!'),
(422, 4, 'listening', 'When will it reopen?', '["Tomorrow morning", "Tonight", "Next week", "In an hour"]', 0, '"It will reopen tomorrow morning".', 'detail', 'general', 627, 'Attention, members! Our swimming pool is closed today for maintenance. It will reopen tomorrow morning. The gym and all classes continue as normal. Thank you for your understanding!'),
(423, 4, 'listening', 'What continues normally?', '["Gym and classes", "Swimming lessons", "The sauna", "The shop"]', 0, '"The gym and all classes continue as normal".', 'detail', 'general', 627, 'Attention, members! Our swimming pool is closed today for maintenance. It will reopen tomorrow morning. The gym and all classes continue as normal. Thank you for your understanding!'),
(424, 4, 'listening', 'Who is the message from?', '["A dentist", "A teacher", "A pilot", "A chef"]', 0, 'Phòng khám nha khoa nhắc lịch hẹn.', 'detail', 'general', 628, 'Hello, this is Bright Dental Clinic reminding you of your appointment tomorrow at 10 a.m. with Dr. Smith. Please arrive fifteen minutes early and bring your insurance card. To reschedule, call us today.'),
(425, 4, 'listening', 'When is the appointment?', '["Tomorrow at 10 a.m.", "Today at 2 p.m.", "Friday at 9 a.m.", "Next Monday"]', 0, '"...your appointment tomorrow at 10 a.m.".', 'detail', 'general', 628, 'Hello, this is Bright Dental Clinic reminding you of your appointment tomorrow at 10 a.m. with Dr. Smith. Please arrive fifteen minutes early and bring your insurance card. To reschedule, call us today.'),
(426, 4, 'listening', 'What should the listener bring?', '["An insurance card", "Cash", "An X-ray", "A friend"]', 0, '"...bring your insurance card".', 'detail', 'general', 628, 'Hello, this is Bright Dental Clinic reminding you of your appointment tomorrow at 10 a.m. with Dr. Smith. Please arrive fifteen minutes early and bring your insurance card. To reschedule, call us today.'),
(427, 4, 'listening', 'What is the main topic?', '["A webinar invitation", "A job ad", "A sale", "A warning"]', 0, 'Mời tham gia hội thảo online miễn phí.', 'main-idea', 'it', 631, 'You are invited to a free webinar on cybersecurity this Thursday at 3 p.m. Our expert will share five simple tips to protect your data. The session lasts forty-five minutes, including questions. Register on our website today!'),
(428, 4, 'listening', 'How long is the session?', '["45 minutes", "30 minutes", "One hour", "Two hours"]', 0, '"...lasts forty-five minutes...".', 'detail', 'it', 631, 'You are invited to a free webinar on cybersecurity this Thursday at 3 p.m. Our expert will share five simple tips to protect your data. The session lasts forty-five minutes, including questions. Register on our website today!'),
(429, 4, 'listening', 'How can people register?', '["On the website", "By phone", "By mail", "In person"]', 0, '"Register on our website today!".', 'detail', 'it', 631, 'You are invited to a free webinar on cybersecurity this Thursday at 3 p.m. Our expert will share five simple tips to protect your data. The session lasts forty-five minutes, including questions. Register on our website today!'),
(430, 4, 'listening', 'Where should cars NOT park?', '["In front of the gate", "In the lot", "On the street", "In the garage"]', 0, 'Cấm đỗ trước cổng kho vì xe tải ra vào.', 'main-idea', 'logistics', 632, 'Attention, drivers! Please do not park in front of the warehouse gate. Delivery trucks need space to enter all day. Violators will be towed. Please use the staff parking lot behind the building. Thank you!'),
(431, 4, 'listening', 'Why is parking banned there?', '["Trucks need space", "It is broken", "It is reserved", "It is too small"]', 0, '"Delivery trucks need space to enter all day".', 'detail', 'logistics', 632, 'Attention, drivers! Please do not park in front of the warehouse gate. Delivery trucks need space to enter all day. Violators will be towed. Please use the staff parking lot behind the building. Thank you!'),
(432, 4, 'listening', 'Where should staff park?', '["Behind the building", "Across the street", "Next door", "Anywhere"]', 0, '"...staff parking lot behind the building".', 'detail', 'logistics', 632, 'Attention, drivers! Please do not park in front of the warehouse gate. Delivery trucks need space to enter all day. Violators will be towed. Please use the staff parking lot behind the building. Thank you!')
ON CONFLICT (id) DO NOTHING;

INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(433, 7, 'reading', 'What is the bank changing?', '["Its weekend hours", "Its fees", "Its name", "Its location"]', 0, 'Ngân hàng đổi giờ mở cửa cuối tuần.', 'comprehension', 'finance', 629, 'CITYBANK NOTICE\n\nStarting next month, our branches will open on Saturday mornings from 8 a.m. to noon. Sunday hours remain unchanged. Our mobile app is available 24 hours for transfers and bill payments. Thank you for banking with us!'),
(434, 7, 'reading', 'When is the bank open on Saturdays?', '["8 a.m. to noon", "9 a.m. to 5 p.m.", "Closed", "All day"]', 0, '"...on Saturday mornings from 8 a.m. to noon".', 'comprehension', 'finance', 629, 'CITYBANK NOTICE\n\nStarting next month, our branches will open on Saturday mornings from 8 a.m. to noon. Sunday hours remain unchanged. Our mobile app is available 24 hours for transfers and bill payments. Thank you for banking with us!'),
(435, 7, 'reading', 'What is available 24 hours?', '["The mobile app", "The branches", "Phone support", "The ATM"]', 0, '"Our mobile app is available 24 hours...".', 'comprehension', 'finance', 629, 'CITYBANK NOTICE\n\nStarting next month, our branches will open on Saturday mornings from 8 a.m. to noon. Sunday hours remain unchanged. Our mobile app is available 24 hours for transfers and bill payments. Thank you for banking with us!'),
(436, 7, 'reading', 'What is for rent?', '["A second-floor office", "A house", "A car", "A warehouse"]', 0, 'Cho thuê văn phòng tầng 2, 80m².', 'comprehension', 'office', 630, 'OFFICE FOR RENT\n\nBright second-floor office, 80 square meters, in the city center. Monthly rent $1,200 including electricity and cleaning. Available from September 1st. Contact Mr. Nam at 091-234-5678 for a viewing.'),
(437, 7, 'reading', 'How much is the monthly rent?', '["$1,200", "$800", "$2,000", "$1,000"]', 0, '"Monthly rent $1,200...".', 'comprehension', 'office', 630, 'OFFICE FOR RENT\n\nBright second-floor office, 80 square meters, in the city center. Monthly rent $1,200 including electricity and cleaning. Available from September 1st. Contact Mr. Nam at 091-234-5678 for a viewing.'),
(438, 7, 'reading', 'When is it available?', '["September 1st", "August 1st", "Immediately", "Next year"]', 0, '"Available from September 1st".', 'comprehension', 'office', 630, 'OFFICE FOR RENT\n\nBright second-floor office, 80 square meters, in the city center. Monthly rent $1,200 including electricity and cleaning. Available from September 1st. Contact Mr. Nam at 091-234-5678 for a viewing.')
ON CONFLICT (id) DO NOTHING;

UPDATE toeic_questions SET audio_text = transcript WHERE id BETWEEN 400 AND 432 AND audio_text IS NULL;
