-- TOEIC Reading Part 6 batch 3 (ids 720-759): 10 doan x 4 cho trong, format de that.
-- Giai thich song ngu Viet-Anh. passage_text lap lai toan van voi moc ___ (id).

-- Part 6, Text 1: product launch email (ids 720-723, passage 720)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(720, 6, 'reading', 'We are excited to ___ our new line of eco-friendly packaging.', '["announce", "announcement", "announced", "announcing"]', 0, 'Sau "to" dung dong tu nguyen mau: to announce. EN: After "to", use the base verb: to announce.', 'tenses', 'marketing', 720, 'To: Valued Customers\nSubject: New Eco-Friendly Packaging\n\nWe are excited to ___ (720) our new line of eco-friendly packaging. Made entirely from recycled materials, these boxes are both sturdy ___ (721) affordable. Orders placed before Friday will receive a 10 percent ___ (722). ___ (723), visit our website to browse the full catalog.\n\nThank you for supporting green business,\nMs. Rivera'),
(721, 6, 'reading', 'These boxes are both sturdy ___ affordable.', '["but", "or", "and", "nor"]', 2, 'Cap song song "both... and...". EN: "Both" pairs with "and".', 'conjunctions', 'marketing', 720, 'To: Valued Customers\nSubject: New Eco-Friendly Packaging\n\nWe are excited to ___ (720) our new line of eco-friendly packaging. Made entirely from recycled materials, these boxes are both sturdy ___ (721) affordable. Orders placed before Friday will receive a 10 percent ___ (722). ___ (723), visit our website to browse the full catalog.\n\nThank you for supporting green business,\nMs. Rivera'),
(722, 6, 'reading', 'Orders placed before Friday will receive a 10 percent ___.', '["discount", "discounted", "discounting", "discounts"]', 0, 'Can danh tu so it sau "a 10 percent": discount. EN: After "a 10 percent", use the singular noun: discount.', 'word-forms', 'marketing', 720, 'To: Valued Customers\nSubject: New Eco-Friendly Packaging\n\nWe are excited to ___ (720) our new line of eco-friendly packaging. Made entirely from recycled materials, these boxes are both sturdy ___ (721) affordable. Orders placed before Friday will receive a 10 percent ___ (722). ___ (723), visit our website to browse the full catalog.\n\nThank you for supporting green business,\nMs. Rivera'),
(723, 6, 'reading', '___ , visit our website to browse the full catalog.', '["For more details", "Despite more details", "Unless more details", "Without more details"]', 0, 'Cau dan sang hanh dong tiep theo: For more details, visit... EN: The sentence introducing the next action is "For more details".', 'vocabulary', 'marketing', 720, 'To: Valued Customers\nSubject: New Eco-Friendly Packaging\n\nWe are excited to ___ (720) our new line of eco-friendly packaging. Made entirely from recycled materials, these boxes are both sturdy ___ (721) affordable. Orders placed before Friday will receive a 10 percent ___ (722). ___ (723), visit our website to browse the full catalog.\n\nThank you for supporting green business,\nMs. Rivera'),
-- Part 6, Text 2: gym membership notice (ids 724-727, passage 721)
(724, 6, 'reading', 'FitLife Gym will be closed for renovation ___ January 10 to January 17.', '["from", "between", "among", "with"]', 0, 'Khoang thoi gian "from A to B". EN: A time range uses "from ... to".', 'prepositions', 'general', 721, 'NOTICE\nFitLife Gym Renovation\n\nFitLife Gym will be closed for renovation ___ (724) January 10 to January 17. During this period, members may use any of our three other ___ (725) at no extra charge. We apologize for the ___ (726) and thank you for your patience. ___ (727) you have questions about your membership, please call 555-0182.\n\nFitLife Management'),
(725, 6, 'reading', 'Members may use any of our three other ___ at no extra charge.', '["locations", "locate", "located", "locating"]', 0, 'Can danh tu so nhieu sau "three other": locations. EN: After "three other", use the plural noun: locations.', 'word-forms', 'general', 721, 'NOTICE\nFitLife Gym Renovation\n\nFitLife Gym will be closed for renovation ___ (724) January 10 to January 17. During this period, members may use any of our three other ___ (725) at no extra charge. We apologize for the ___ (726) and thank you for your patience. ___ (727) you have questions about your membership, please call 555-0182.\n\nFitLife Management'),
(726, 6, 'reading', 'We apologize for the ___ and thank you for your patience.', '["inconvenience", "inconvenient", "inconveniently", "convenience"]', 0, 'Sau "the" can danh tu: inconvenience (su bat tien). EN: After "the", use the noun: inconvenience.', 'word-forms', 'general', 721, 'NOTICE\nFitLife Gym Renovation\n\nFitLife Gym will be closed for renovation ___ (724) January 10 to January 17. During this period, members may use any of our three other ___ (725) at no extra charge. We apologize for the ___ (726) and thank you for your patience. ___ (727) you have questions about your membership, please call 555-0182.\n\nFitLife Management'),
(727, 6, 'reading', '___ you have questions about your membership, please call 555-0182.', '["Should", "Unless", "Despite", "Without"]', 0, 'Dao ngu dieu kien loai 1 (If -> Should): Should you have... EN: Inverted first conditional uses "Should + subject + verb".', 'conditionals', 'general', 721, 'NOTICE\nFitLife Gym Renovation\n\nFitLife Gym will be closed for renovation ___ (724) January 10 to January 17. During this period, members may use any of our three other ___ (725) at no extra charge. We apologize for the ___ (726) and thank you for your patience. ___ (727) you have questions about your membership, please call 555-0182.\n\nFitLife Management'),
-- Part 6, Text 3: job advertisement (ids 728-731, passage 722)
(728, 6, 'reading', 'BrightCook Appliances is seeking a full-time customer service ___.', '["representative", "represent", "represented", "representation"]', 0, 'Chuc danh can danh tu chi nguoi: representative. EN: A job title needs the person noun: representative.', 'word-forms', 'hr', 722, 'JOIN OUR TEAM\nBrightCook Appliances is seeking a full-time customer service ___ (728). The ideal candidate is patient, organized, and fluent ___ (729) English. Previous call-center experience is preferred but not ___ (730). To apply, send your resume by June 30 ___ (731) jobs@brightcook.example.com.\n\nBrightCook HR Department'),
(729, 6, 'reading', 'The ideal candidate is patient, organized, and fluent ___ English.', '["at", "with", "in", "for"]', 2, '"Fluent in + ngon ngu" la cum co dinh. EN: "Fluent in + a language" is the fixed collocation.', 'prepositions', 'hr', 722, 'JOIN OUR TEAM\nBrightCook Appliances is seeking a full-time customer service ___ (728). The ideal candidate is patient, organized, and fluent ___ (729) English. Previous call-center experience is preferred but not ___ (730). To apply, send your resume by June 30 ___ (731) jobs@brightcook.example.com.\n\nBrightCook HR Department'),
(730, 6, 'reading', 'Previous call-center experience is preferred but not ___.', '["required", "require", "requirement", "requires"]', 0, 'Can tinh tu (past participle) sau "not": required. EN: An adjective is needed after "not": required.', 'word-forms', 'hr', 722, 'JOIN OUR TEAM\nBrightCook Appliances is seeking a full-time customer service ___ (728). The ideal candidate is patient, organized, and fluent ___ (729) English. Previous call-center experience is preferred but not ___ (730). To apply, send your resume by June 30 ___ (731) jobs@brightcook.example.com.\n\nBrightCook HR Department'),
(731, 6, 'reading', 'To apply, send your resume by June 30 ___ jobs@brightcook.example.com.', '["for", "to", "at", "with"]', 1, 'Gui ho so den mot dia chi: send... to... EN: Sending something to an address uses "to".', 'prepositions', 'hr', 722, 'JOIN OUR TEAM\nBrightCook Appliances is seeking a full-time customer service ___ (728). The ideal candidate is patient, organized, and fluent ___ (729) English. Previous call-center experience is preferred but not ___ (730). To apply, send your resume by June 30 ___ (731) jobs@brightcook.example.com.\n\nBrightCook HR Department'),
-- Part 6, Text 4: flight delay announcement (ids 732-735, passage 723)
(732, 6, 'reading', 'Flight VN184 to Bangkok has been delayed ___ approximately two hours.', '["by", "with", "in", "for"]', 0, 'Tre mot khoang thoi gian: delayed by two hours. EN: The length of a delay uses "by".', 'prepositions', 'travel', 723, 'ANNOUNCEMENT\nFlight VN184 to Bangkok has been delayed ___ (732) approximately two hours. Passengers are requested to remain in the departure lounge until further ___ (733). Meal vouchers are available at the information desk for all ___ (734) travelers. We sincerely apologize for any disruption ___ (735) your travel plans.\n\nAirport Authority'),
(733, 6, 'reading', 'Passengers are requested to remain in the departure lounge until further ___.', '["notice", "noticed", "notices", "noticing"]', 0, 'Cum co dinh "until further notice" (cho den khi co thong bao moi). EN: "Until further notice" is the fixed phrase for an open-ended wait.', 'vocabulary', 'travel', 723, 'ANNOUNCEMENT\nFlight VN184 to Bangkok has been delayed ___ (732) approximately two hours. Passengers are requested to remain in the departure lounge until further ___ (733). Meal vouchers are available at the information desk for all ___ (734) travelers. We sincerely apologize for any disruption ___ (735) your travel plans.\n\nAirport Authority'),
(734, 6, 'reading', 'Meal vouchers are available for all ___ travelers.', '["affecting", "affects", "affected", "affect"]', 2, 'Rut gon menh de quan he: travelers affected (= who are affected). EN: A reduced relative clause uses the past participle: affected.', 'passive', 'travel', 723, 'ANNOUNCEMENT\nFlight VN184 to Bangkok has been delayed ___ (732) approximately two hours. Passengers are requested to remain in the departure lounge until further ___ (733). Meal vouchers are available at the information desk for all ___ (734) travelers. We sincerely apologize for any disruption ___ (735) your travel plans.\n\nAirport Authority'),
(735, 6, 'reading', 'We sincerely apologize for any disruption ___ your travel plans.', '["for", "to", "with", "on"]', 1, '"Disruption to + ke hoach" (gian doan doi voi...). EN: "Disruption" pairs with "to".', 'prepositions', 'travel', 723, 'ANNOUNCEMENT\nFlight VN184 to Bangkok has been delayed ___ (732) approximately two hours. Passengers are requested to remain in the departure lounge until further ___ (733). Meal vouchers are available at the information desk for all ___ (734) travelers. We sincerely apologize for any disruption ___ (735) your travel plans.\n\nAirport Authority'),
-- Part 6, Text 5: bank letter (ids 736-739, passage 724)
(736, 6, 'reading', 'We are writing to inform you ___ a change to your savings account.', '["about", "with", "of", "at"]', 0, '"Inform you about + noi dung" (thong bao ve...). EN: "Inform someone about something" is the fixed pattern.', 'prepositions', 'finance', 724, 'Dear Ms. Nguyen,\n\nWe are writing to inform you ___ (736) a change to your savings account. Starting August 1, the monthly maintenance fee will be ___ (737). This change will not affect customers ___ (738) maintain a balance above $1,000. ___ (739) you have any concerns, please visit any branch office.\n\nSincerely,\nCityTrust Bank'),
(737, 6, 'reading', 'Starting August 1, the monthly maintenance fee will be ___.', '["waived", "waive", "waiver", "waiving"]', 0, 'Bi dong tuong lai "will be + V3": will be waived (duoc mien). EN: Future passive "will be + past participle": will be waived.', 'passive', 'finance', 724, 'Dear Ms. Nguyen,\n\nWe are writing to inform you ___ (736) a change to your savings account. Starting August 1, the monthly maintenance fee will be ___ (737). This change will not affect customers ___ (738) maintain a balance above $1,000. ___ (739) you have any concerns, please visit any branch office.\n\nSincerely,\nCityTrust Bank'),
(738, 6, 'reading', 'This change will not affect customers ___ maintain a balance above $1,000.', '["who", "which", "whose", "whom"]', 0, 'Menh de quan he chi nguoi lam chu ngu: who. EN: People as subject of the clause need "who".', 'relative-clauses', 'finance', 724, 'Dear Ms. Nguyen,\n\nWe are writing to inform you ___ (736) a change to your savings account. Starting August 1, the monthly maintenance fee will be ___ (737). This change will not affect customers ___ (738) maintain a balance above $1,000. ___ (739) you have any concerns, please visit any branch office.\n\nSincerely,\nCityTrust Bank'),
(739, 6, 'reading', '___ you have any concerns, please visit any branch office.', '["Should", "Unless", "Despite", "Without"]', 0, 'Dao ngu dieu kien loai 1: Should you have... EN: Inverted first conditional: "Should + subject + verb".', 'conditionals', 'finance', 724, 'Dear Ms. Nguyen,\n\nWe are writing to inform you ___ (736) a change to your savings account. Starting August 1, the monthly maintenance fee will be ___ (737). This change will not affect customers ___ (738) maintain a balance above $1,000. ___ (739) you have any concerns, please visit any branch office.\n\nSincerely,\nCityTrust Bank'),
-- Part 6, Text 6: conference invitation (ids 740-743, passage 725)
(740, 6, 'reading', 'You are cordially invited to attend the annual logistics ___.', '["summit", "summiting", "summited", "summarize"]', 0, 'Can danh tu chi su kien: summit (hoi nghi thuong dinh). EN: An event noun is needed: summit.', 'vocabulary', 'logistics', 725, 'INVITATION\nYou are cordially invited to attend the annual logistics ___ (740). The two-day event will ___ (741) place at the Riverside Convention Center on September 12-13. Industry experts will share insights on supply chain ___ (742). Early registration ends August 20, so reserve your seat ___ (743).\n\nGlobal Logistics Association'),
(741, 6, 'reading', 'The two-day event will ___ place at the Riverside Convention Center.', '["take", "make", "do", "have"]', 0, 'Cum co dinh "take place" (dien ra). EN: "Take place" is the fixed phrase meaning to happen.', 'vocabulary', 'logistics', 725, 'INVITATION\nYou are cordially invited to attend the annual logistics ___ (740). The two-day event will ___ (741) place at the Riverside Convention Center on September 12-13. Industry experts will share insights on supply chain ___ (742). Early registration ends August 20, so reserve your seat ___ (743).\n\nGlobal Logistics Association'),
(742, 6, 'reading', 'Experts will share insights on supply chain ___.', '["management", "manage", "managed", "manager"]', 0, 'Can danh tu sau "supply chain": management (quan ly). EN: After "supply chain", use the noun: management.', 'word-forms', 'logistics', 725, 'INVITATION\nYou are cordially invited to attend the annual logistics ___ (740). The two-day event will ___ (741) place at the Riverside Convention Center on September 12-13. Industry experts will share insights on supply chain ___ (742). Early registration ends August 20, so reserve your seat ___ (743).\n\nGlobal Logistics Association'),
(743, 6, 'reading', 'Early registration ends August 20, so reserve your seat ___.', '["today", "yesterday", "late", "ago"]', 0, 'Keu goi hanh dong ngay: reserve your seat today. EN: An immediate call to action uses "today".', 'vocabulary', 'logistics', 725, 'INVITATION\nYou are cordially invited to attend the annual logistics ___ (740). The two-day event will ___ (741) place at the Riverside Convention Center on September 12-13. Industry experts will share insights on supply chain ___ (742). Early registration ends August 20, so reserve your seat ___ (743).\n\nGlobal Logistics Association'),
-- Part 6, Text 7: software instructions (ids 744-747, passage 726)
(744, 6, 'reading', 'To install the update, first ___ all running applications.', '["close", "closing", "closed", "closure"]', 0, 'Cau menh lenh bat dau bang dong tu nguyen mau: close. EN: An instruction starts with the base verb: close.', 'tenses', 'it', 726, 'INSTALLATION GUIDE\nTo install the update, first ___ (744) all running applications. The installation process usually takes less ___ (745) ten minutes. Do not turn off your computer ___ (746) the progress bar reaches 100 percent. If problems occur, restart the program and try ___ (747).\n\nSupport Team'),
(745, 6, 'reading', 'The installation process usually takes less ___ ten minutes.', '["than", "then", "that", "those"]', 0, '"Less... than..." (it hon...). EN: "Less" pairs with "than".', 'comparatives', 'it', 726, 'INSTALLATION GUIDE\nTo install the update, first ___ (744) all running applications. The installation process usually takes less ___ (745) ten minutes. Do not turn off your computer ___ (746) the progress bar reaches 100 percent. If problems occur, restart the program and try ___ (747).\n\nSupport Team'),
(746, 6, 'reading', 'Do not turn off your computer ___ the progress bar reaches 100 percent.', '["until", "by", "since", "during"]', 0, 'Khong tat may cho den khi xong: until... reaches. EN: Waiting up to a point uses "until".', 'prepositions', 'it', 726, 'INSTALLATION GUIDE\nTo install the update, first ___ (744) all running applications. The installation process usually takes less ___ (745) ten minutes. Do not turn off your computer ___ (746) the progress bar reaches 100 percent. If problems occur, restart the program and try ___ (747).\n\nSupport Team'),
(747, 6, 'reading', 'If problems occur, restart the program and try ___.', '["again", "ago", "ever", "once"]', 0, 'Thu lai mot lan nua: try again. EN: Repeating an attempt uses "again".', 'vocabulary', 'it', 726, 'INSTALLATION GUIDE\nTo install the update, first ___ (744) all running applications. The installation process usually takes less ___ (745) ten minutes. Do not turn off your computer ___ (746) the progress bar reaches 100 percent. If problems occur, restart the program and try ___ (747).\n\nSupport Team'),
-- Part 6, Text 8: restaurant review reply (ids 748-751, passage 727)
(748, 6, 'reading', 'Thank you for dining with us and for sharing your ___.', '["feedback", "feed", "feeding", "fed"]', 0, 'Can danh tu sau "your": feedback (phan hoi). EN: After "your", use the noun: feedback.', 'word-forms', 'support', 727, 'Dear Mr. Harris,\n\nThank you for dining with us and for sharing your ___ (748). We are delighted that you enjoyed the seafood platter, ___ (749) is prepared fresh daily. As a token of appreciation, we would like to offer you a complimentary dessert ___ (750) your next visit. We look forward to ___ (751) you again soon.\n\nThe Harbor Restaurant'),
(749, 6, 'reading', 'You enjoyed the seafood platter, ___ is prepared fresh daily.', '["which", "who", "whose", "whom"]', 0, 'Menh de quan he chi mon an (vat): which. EN: A relative clause for a thing uses "which".', 'relative-clauses', 'support', 727, 'Dear Mr. Harris,\n\nThank you for dining with us and for sharing your ___ (748). We are delighted that you enjoyed the seafood platter, ___ (749) is prepared fresh daily. As a token of appreciation, we would like to offer you a complimentary dessert ___ (750) your next visit. We look forward to ___ (751) you again soon.\n\nThe Harbor Restaurant'),
(750, 6, 'reading', 'We would like to offer you a complimentary dessert ___ your next visit.', '["during", "while", "until", "since"]', 0, 'Trong chuyen ghe tham toi: during your next visit. EN: Throughout a visit takes "during".', 'prepositions', 'support', 727, 'Dear Mr. Harris,\n\nThank you for dining with us and for sharing your ___ (748). We are delighted that you enjoyed the seafood platter, ___ (749) is prepared fresh daily. As a token of appreciation, we would like to offer you a complimentary dessert ___ (750) your next visit. We look forward to ___ (751) you again soon.\n\nThe Harbor Restaurant'),
(751, 6, 'reading', 'We look forward to ___ you again soon.', '["serve", "serving", "served", "service"]', 1, '"Look forward to + V-ing" (mong duoc...). EN: "Look forward to" is followed by a gerund.', 'gerunds', 'support', 727, 'Dear Mr. Harris,\n\nThank you for dining with us and for sharing your ___ (748). We are delighted that you enjoyed the seafood platter, ___ (749) is prepared fresh daily. As a token of appreciation, we would like to offer you a complimentary dessert ___ (750) your next visit. We look forward to ___ (751) you again soon.\n\nThe Harbor Restaurant'),
-- Part 6, Text 9: warehouse memo (ids 752-755, passage 728)
(752, 6, 'reading', 'Effective Monday, all deliveries must be scheduled ___ advance.', '["at", "in", "on", "from"]', 1, 'Cum co dinh "in advance" (dat truoc). EN: "In advance" is the fixed phrase meaning beforehand.', 'prepositions', 'logistics', 728, 'MEMO\nEffective Monday, all deliveries must be scheduled ___ (752) advance. Drivers should report to Gate B, where security staff will verify ___ (753) identities. Any vehicle without an appointment will be ___ (754) entry. These measures help us keep operations running ___ (755).\n\nWarehouse Manager'),
(753, 6, 'reading', 'Security staff will verify ___ identities.', '["their", "theirs", "they", "them"]', 0, 'Tinh tu so huu truoc danh tu: their identities. EN: A possessive adjective comes before the noun: their.', 'pronouns', 'logistics', 728, 'MEMO\nEffective Monday, all deliveries must be scheduled ___ (752) advance. Drivers should report to Gate B, where security staff will verify ___ (753) identities. Any vehicle without an appointment will be ___ (754) entry. These measures help us keep operations running ___ (755).\n\nWarehouse Manager'),
(754, 6, 'reading', 'Any vehicle without an appointment will be ___ entry.', '["denied", "deny", "denies", "denying"]', 0, 'Bi dong tuong lai "will be + V3": will be denied. EN: Future passive needs the past participle: denied.', 'passive', 'logistics', 728, 'MEMO\nEffective Monday, all deliveries must be scheduled ___ (752) advance. Drivers should report to Gate B, where security staff will verify ___ (753) identities. Any vehicle without an appointment will be ___ (754) entry. These measures help us keep operations running ___ (755).\n\nWarehouse Manager'),
(755, 6, 'reading', 'These measures help us keep operations running ___.', '["smoothly", "smooth", "smoothness", "smoothed"]', 0, 'Trang tu bo nghia cum "keep... running": smoothly. EN: An adverb must modify "keep operations running": smoothly.', 'word-forms', 'logistics', 728, 'MEMO\nEffective Monday, all deliveries must be scheduled ___ (752) advance. Drivers should report to Gate B, where security staff will verify ___ (753) identities. Any vehicle without an appointment will be ___ (754) entry. These measures help us keep operations running ___ (755).\n\nWarehouse Manager'),
-- Part 6, Text 10: newsletter subscription (ids 756-759, passage 729)
(756, 6, 'reading', 'Stay informed with our weekly business ___.', '["newsletter", "news", "newspaper", "newly"]', 0, 'Ban tin hang tuan: newsletter. EN: A weekly business publication is a "newsletter".', 'vocabulary', 'marketing', 729, 'SUBSCRIBE TODAY\nStay informed with our weekly business ___ (756). Each edition covers market trends, and subscribers receive ___ (757) access to our webinar archive. Signing up takes less than two minutes; simply enter your email address ___ (758). Join over 50,000 readers ___ (759) trust MarketWatch Weekly.\n\nMarketWatch Weekly'),
(757, 6, 'reading', 'Subscribers receive ___ access to our webinar archive.', '["exclusive", "exclude", "exclusion", "excluded"]', 0, 'Can tinh tu bo nghia "access": exclusive. EN: An adjective must modify "access": exclusive.', 'word-forms', 'marketing', 729, 'SUBSCRIBE TODAY\nStay informed with our weekly business ___ (756). Each edition covers market trends, and subscribers receive ___ (757) access to our webinar archive. Signing up takes less than two minutes; simply enter your email address ___ (758). Join over 50,000 readers ___ (759) trust MarketWatch Weekly.\n\nMarketWatch Weekly'),
(758, 6, 'reading', 'Simply enter your email address ___.', '["below", "above", "behind", "ahead"]', 0, 'Nhap dia chi vao o ben duoi: enter... below. EN: Typing into a field shown underneath uses "below".', 'vocabulary', 'marketing', 729, 'SUBSCRIBE TODAY\nStay informed with our weekly business ___ (756). Each edition covers market trends, and subscribers receive ___ (757) access to our webinar archive. Signing up takes less than two minutes; simply enter your email address ___ (758). Join over 50,000 readers ___ (759) trust MarketWatch Weekly.\n\nMarketWatch Weekly'),
(759, 6, 'reading', 'Join over 50,000 readers ___ trust MarketWatch Weekly.', '["who", "which", "whose", "whom"]', 0, 'Menh de quan he chi nguoi lam chu ngu: who. EN: People as subject of the clause need "who".', 'relative-clauses', 'marketing', 729, 'SUBSCRIBE TODAY\nStay informed with our weekly business ___ (756). Each edition covers market trends, and subscribers receive ___ (757) access to our webinar archive. Signing up takes less than two minutes; simply enter your email address ___ (758). Join over 50,000 readers ___ (759) trust MarketWatch Weekly.\n\nMarketWatch Weekly')
ON CONFLICT (id) DO NOTHING;
