-- TOEIC Reading Part 6 batch 4 (ids 760-799): 10 doan x 4 cho trong, format de that.
-- Giai thich song ngu Viet-Anh. passage_text lap lai toan van voi moc ___ (id).

-- Part 6, Text 11: hotel renovation letter (ids 760-763, passage 730)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(760, 6, 'reading', 'We are pleased to announce the ___ of our newly renovated lobby.', '["opening", "open", "opened", "opens"]', 0, 'Can danh tu sau "the": opening (le khai truong). EN: After "the", use the noun: opening.', 'word-forms', 'travel', 730, 'Dear Guests,\n\nWe are pleased to announce the ___ (760) of our newly renovated lobby. The space now features elegant lighting and comfortable seating ___ (761) all visitors. Renovations were completed two weeks ahead of ___ (762). We invite you to experience the improvements ___ (763) your next stay.\n\nThe Grand Hotel'),
(761, 6, 'reading', 'The space now features comfortable seating ___ all visitors.', '["for", "to", "with", "at"]', 0, 'Ghe ngoi danh cho khach: seating for visitors. EN: The beneficiary takes "for".', 'prepositions', 'travel', 730, 'Dear Guests,\n\nWe are pleased to announce the ___ (760) of our newly renovated lobby. The space now features elegant lighting and comfortable seating ___ (761) all visitors. Renovations were completed two weeks ahead of ___ (762). We invite you to experience the improvements ___ (763) your next stay.\n\nThe Grand Hotel'),
(762, 6, 'reading', 'Renovations were completed two weeks ahead of ___.', '["schedule", "scheduled", "scheduling", "schedules"]', 0, 'Cum co dinh "ahead of schedule" (som hon ke hoach). EN: "Ahead of schedule" is the fixed phrase for early completion.', 'vocabulary', 'travel', 730, 'Dear Guests,\n\nWe are pleased to announce the ___ (760) of our newly renovated lobby. The space now features elegant lighting and comfortable seating ___ (761) all visitors. Renovations were completed two weeks ahead of ___ (762). We invite you to experience the improvements ___ (763) your next stay.\n\nThe Grand Hotel'),
(763, 6, 'reading', 'We invite you to experience the improvements ___ your next stay.', '["during", "while", "until", "since"]', 0, 'Trong lan luu tru toi: during your next stay. EN: Throughout a stay takes "during".', 'prepositions', 'travel', 730, 'Dear Guests,\n\nWe are pleased to announce the ___ (760) of our newly renovated lobby. The space now features elegant lighting and comfortable seating ___ (761) all visitors. Renovations were completed two weeks ahead of ___ (762). We invite you to experience the improvements ___ (763) your next stay.\n\nThe Grand Hotel'),
-- Part 6, Text 12: library announcement (ids 764-767, passage 731)
(764, 6, 'reading', 'The downtown library will extend its opening hours ___ next Monday.', '["effective", "effect", "effectively", "effects"]', 0, 'Can tinh tu dau cau (co hieu luc tu...): Effective next Monday. EN: A sentence-opening adjective is needed: Effective.', 'word-forms', 'general', 731, 'ANNOUNCEMENT\nThe downtown library will extend its opening hours ___ (764) next Monday. The new schedule runs ___ (765) 7 a.m. to 11 p.m. daily. This change comes in response ___ (766) requests from evening readers. Weekend workshops will continue ___ (767) usual.\n\nCity Library Board'),
(765, 6, 'reading', 'The new schedule runs ___ 7 a.m. to 11 p.m. daily.', '["from", "between", "among", "with"]', 0, 'Khoang gio "from A to B". EN: A time range uses "from ... to".', 'prepositions', 'general', 731, 'ANNOUNCEMENT\nThe downtown library will extend its opening hours ___ (764) next Monday. The new schedule runs ___ (765) 7 a.m. to 11 p.m. daily. This change comes in response ___ (766) requests from evening readers. Weekend workshops will continue ___ (767) usual.\n\nCity Library Board'),
(766, 6, 'reading', 'This change comes in response ___ requests from evening readers.', '["to", "for", "with", "of"]', 0, '"In response to + yeu cau" (dap ung...). EN: "In response" pairs with "to".', 'prepositions', 'general', 731, 'ANNOUNCEMENT\nThe downtown library will extend its opening hours ___ (764) next Monday. The new schedule runs ___ (765) 7 a.m. to 11 p.m. daily. This change comes in response ___ (766) requests from evening readers. Weekend workshops will continue ___ (767) usual.\n\nCity Library Board'),
(767, 6, 'reading', 'Weekend workshops will continue ___ usual.', '["like", "as", "same", "likely"]', 1, 'Cum co dinh "as usual" (nhu thuong le). EN: "As usual" is the fixed phrase meaning normally.', 'vocabulary', 'general', 731, 'ANNOUNCEMENT\nThe downtown library will extend its opening hours ___ (764) next Monday. The new schedule runs ___ (765) 7 a.m. to 11 p.m. daily. This change comes in response ___ (766) requests from evening readers. Weekend workshops will continue ___ (767) usual.\n\nCity Library Board'),
-- Part 6, Text 13: supplier email (ids 768-771, passage 732)
(768, 6, 'reading', 'Thank you for your order, ___ was shipped this morning.', '["which", "who", "whose", "whom"]', 0, 'Menh de quan he chi don hang (vat): which. EN: A relative clause for a thing uses "which".', 'relative-clauses', 'sales', 732, 'Dear Mr. Baker,\n\nThank you for your order, ___ (768) was shipped this morning. The tracking number has been sent to you in a ___ (769) email. Please inspect the goods upon arrival and report any damage ___ (770) 48 hours. We appreciate your continued ___ (771).\n\nFastShip Sales Team'),
(769, 6, 'reading', 'The tracking number has been sent in a ___ email.', '["separate", "separately", "separation", "separates"]', 0, 'Can tinh tu bo nghia "email": separate (rieng). EN: An adjective must modify "email": separate.', 'word-forms', 'sales', 732, 'Dear Mr. Baker,\n\nThank you for your order, ___ (768) was shipped this morning. The tracking number has been sent to you in a ___ (769) email. Please inspect the goods upon arrival and report any damage ___ (770) 48 hours. We appreciate your continued ___ (771).\n\nFastShip Sales Team'),
(770, 6, 'reading', 'Please report any damage ___ 48 hours.', '["within", "among", "between", "along"]', 0, 'Bao cao trong vong 48 gio: within 48 hours. EN: A reporting deadline uses "within".', 'prepositions', 'sales', 732, 'Dear Mr. Baker,\n\nThank you for your order, ___ (768) was shipped this morning. The tracking number has been sent to you in a ___ (769) email. Please inspect the goods upon arrival and report any damage ___ (770) 48 hours. We appreciate your continued ___ (771).\n\nFastShip Sales Team'),
(771, 6, 'reading', 'We appreciate your continued ___.', '["support", "supportive", "supported", "supports"]', 0, 'Can danh tu sau "your continued": support. EN: After "your continued", use the noun: support.', 'word-forms', 'sales', 732, 'Dear Mr. Baker,\n\nThank you for your order, ___ (768) was shipped this morning. The tracking number has been sent to you in a ___ (769) email. Please inspect the goods upon arrival and report any damage ___ (770) 48 hours. We appreciate your continued ___ (771).\n\nFastShip Sales Team'),
-- Part 6, Text 14: office party memo (ids 772-775, passage 733)
(772, 6, 'reading', 'Our annual year-end party will be held ___ December 20.', '["in", "at", "on", "for"]', 2, 'Ngay cu the (December 20) dung "on". EN: A specific date takes "on".', 'prepositions', 'office', 733, 'MEMO\nOur annual year-end party will be held ___ (772) December 20. The event begins at 6 p.m. in the main hall, and dinner will be ___ (773) at 7 p.m. Employees are welcome to bring one guest, but please confirm attendance ___ (774) Friday. ___ (775) to entertainment, a live band will perform after dinner.\n\nHR Office'),
(773, 6, 'reading', 'Dinner will be ___ at 7 p.m.', '["served", "serve", "serves", "serving"]', 0, 'Bi dong tuong lai "will be + V3": will be served. EN: Future passive needs the past participle: served.', 'passive', 'office', 733, 'MEMO\nOur annual year-end party will be held ___ (772) December 20. The event begins at 6 p.m. in the main hall, and dinner will be ___ (773) at 7 p.m. Employees are welcome to bring one guest, but please confirm attendance ___ (774) Friday. ___ (775) to entertainment, a live band will perform after dinner.\n\nHR Office'),
(774, 6, 'reading', 'Please confirm attendance ___ Friday.', '["by", "until", "since", "during"]', 0, 'Xac nhan cham nhat vao thu 6: by Friday. EN: A confirmation deadline uses "by".', 'prepositions', 'office', 733, 'MEMO\nOur annual year-end party will be held ___ (772) December 20. The event begins at 6 p.m. in the main hall, and dinner will be ___ (773) at 7 p.m. Employees are welcome to bring one guest, but please confirm attendance ___ (774) Friday. ___ (775) to entertainment, a live band will perform after dinner.\n\nHR Office'),
(775, 6, 'reading', '___ to entertainment, a live band will perform after dinner.', '["With regard", "Despite", "Unless", "Without"]', 0, 'Chuyen sang chu de giai tri: With regard to entertainment. EN: Shifting to a topic uses "With regard to".', 'vocabulary', 'office', 733, 'MEMO\nOur annual year-end party will be held ___ (772) December 20. The event begins at 6 p.m. in the main hall, and dinner will be ___ (773) at 7 p.m. Employees are welcome to bring one guest, but please confirm attendance ___ (774) Friday. ___ (775) to entertainment, a live band will perform after dinner.\n\nHR Office'),
-- Part 6, Text 15: phone plan ad (ids 776-779, passage 734)
(776, 6, 'reading', 'Switch to FlexMobile and save up to 40 ___ on your monthly bill.', '["percent", "percentage", "percentages", "percentile"]', 0, 'Sau so "40" can danh tu: percent. EN: After "40", use the noun: percent.', 'word-forms', 'marketing', 734, 'SAVE MORE\nSwitch to FlexMobile and save up to 40 ___ (776) on your monthly bill. New customers also get a free phone when they sign a two-year ___ (777). There are no hidden fees, and you can cancel ___ (778) any time. Visit any FlexMobile store ___ (779) to learn more.\n\nFlexMobile'),
(777, 6, 'reading', 'Customers get a free phone with a two-year ___.', '["contract", "contact", "contrast", "content"]', 0, 'Hop dong 2 nam: two-year contract. EN: A two-year service agreement is a "contract".', 'vocabulary', 'marketing', 734, 'SAVE MORE\nSwitch to FlexMobile and save up to 40 ___ (776) on your monthly bill. New customers also get a free phone when they sign a two-year ___ (777). There are no hidden fees, and you can cancel ___ (778) any time. Visit any FlexMobile store ___ (779) to learn more.\n\nFlexMobile'),
(778, 6, 'reading', 'You can cancel ___ any time.', '["at", "in", "on", "for"]', 0, 'Cum co dinh "at any time" (bat cu luc nao). EN: "At any time" is the fixed phrase meaning whenever.', 'prepositions', 'marketing', 734, 'SAVE MORE\nSwitch to FlexMobile and save up to 40 ___ (776) on your monthly bill. New customers also get a free phone when they sign a two-year ___ (777). There are no hidden fees, and you can cancel ___ (778) any time. Visit any FlexMobile store ___ (779) to learn more.\n\nFlexMobile'),
(779, 6, 'reading', 'Visit any FlexMobile store ___ to learn more.', '["today", "yesterday", "ago", "late"]', 0, 'Keu goi hanh dong ngay: visit... today. EN: An immediate call to action uses "today".', 'vocabulary', 'marketing', 734, 'SAVE MORE\nSwitch to FlexMobile and save up to 40 ___ (776) on your monthly bill. New customers also get a free phone when they sign a two-year ___ (777). There are no hidden fees, and you can cancel ___ (778) any time. Visit any FlexMobile store ___ (779) to learn more.\n\nFlexMobile'),
-- Part 6, Text 16: train service notice (ids 780-783, passage 735)
(780, 6, 'reading', 'Additional trains will run ___ weekends during the holiday season.', '["in", "at", "on", "for"]', 2, 'Cac ngay cuoi tuan lap lai dung "on weekends". EN: Repeated weekend days take "on".', 'prepositions', 'travel', 735, 'SERVICE UPDATE\nAdditional trains will run ___ (780) weekends during the holiday season. The extra departures are intended to reduce ___ (781) on regular services. Passengers holding monthly passes may use any departure ___ (782) extra charge. We thank you for choosing MetroRail and wish you a pleasant ___ (783).\n\nMetroRail'),
(781, 6, 'reading', 'The extra departures reduce ___ on regular services.', '["crowding", "crowd", "crowded", "crowds"]', 0, 'Can danh tu (gerund) sau "reduce": crowding (tinh trang dong duc). EN: After "reduce", use the noun/gerund: crowding.', 'word-forms', 'travel', 735, 'SERVICE UPDATE\nAdditional trains will run ___ (780) weekends during the holiday season. The extra departures are intended to reduce ___ (781) on regular services. Passengers holding monthly passes may use any departure ___ (782) extra charge. We thank you for choosing MetroRail and wish you a pleasant ___ (783).\n\nMetroRail'),
(782, 6, 'reading', 'Passengers may use any departure ___ extra charge.', '["without", "unless", "except", "beside"]', 0, 'Khong mat them phi: without extra charge. EN: No additional fee uses "without".', 'prepositions', 'travel', 735, 'SERVICE UPDATE\nAdditional trains will run ___ (780) weekends during the holiday season. The extra departures are intended to reduce ___ (781) on regular services. Passengers holding monthly passes may use any departure ___ (782) extra charge. We thank you for choosing MetroRail and wish you a pleasant ___ (783).\n\nMetroRail'),
(783, 6, 'reading', 'We wish you a pleasant ___.', '["journey", "journal", "adjourn", "junior"]', 0, 'Chuc chuyen di vui ve: a pleasant journey. EN: A pleasant trip is a "journey".', 'vocabulary', 'travel', 735, 'SERVICE UPDATE\nAdditional trains will run ___ (780) weekends during the holiday season. The extra departures are intended to reduce ___ (781) on regular services. Passengers holding monthly passes may use any departure ___ (782) extra charge. We thank you for choosing MetroRail and wish you a pleasant ___ (783).\n\nMetroRail'),
-- Part 6, Text 17: accounting workshop email (ids 784-787, passage 736)
(784, 6, 'reading', 'We are writing to remind you ___ the tax workshop on July 8.', '["about", "with", "of", "at"]', 0, '"Remind you about + su kien" (nhac ve...). EN: "Remind someone about something" is the fixed pattern.', 'prepositions', 'finance', 736, 'Dear Client,\n\nWe are writing to remind you ___ (784) the tax workshop on July 8. The session will cover recent changes in corporate tax ___ (785). Attendance is free for all retainer clients, but seats are ___ (786). Please register online, as walk-in guests cannot be ___ (787).\n\nBrightTax Advisors'),
(785, 6, 'reading', 'The session will cover changes in corporate tax ___.', '["regulations", "regulate", "regulated", "regulating"]', 0, 'Can danh tu so nhieu: tax regulations (quy dinh thue). EN: Rules use the plural noun "regulations".', 'word-forms', 'finance', 736, 'Dear Client,\n\nWe are writing to remind you ___ (784) the tax workshop on July 8. The session will cover recent changes in corporate tax ___ (785). Attendance is free for all retainer clients, but seats are ___ (786). Please register online, as walk-in guests cannot be ___ (787).\n\nBrightTax Advisors'),
(786, 6, 'reading', 'Seats are ___.', '["limited", "limit", "limits", "limiting"]', 0, 'So ghe co han (tinh tu): seats are limited. EN: Restricted availability uses the adjective "limited".', 'word-forms', 'finance', 736, 'Dear Client,\n\nWe are writing to remind you ___ (784) the tax workshop on July 8. The session will cover recent changes in corporate tax ___ (785). Attendance is free for all retainer clients, but seats are ___ (786). Please register online, as walk-in guests cannot be ___ (787).\n\nBrightTax Advisors'),
(787, 6, 'reading', 'Walk-in guests cannot be ___.', '["accommodated", "accommodate", "accommodates", "accommodation"]', 0, 'Bi dong "cannot be + V3": cannot be accommodated. EN: Passive "cannot be + past participle": accommodated.', 'passive', 'finance', 736, 'Dear Client,\n\nWe are writing to remind you ___ (784) the tax workshop on July 8. The session will cover recent changes in corporate tax ___ (785). Attendance is free for all retainer clients, but seats are ___ (786). Please register online, as walk-in guests cannot be ___ (787).\n\nBrightTax Advisors'),
-- Part 6, Text 18: parking instructions (ids 788-791, passage 737)
(788, 6, 'reading', 'Visitors should park in Lot C, ___ is located behind the main building.', '["which", "who", "whose", "whom"]', 0, 'Menh de quan he chi bai do (dia diem): which. EN: A relative clause for a place uses "which".', 'relative-clauses', 'office', 737, 'PARKING GUIDE\nVisitors should park in Lot C, ___ (788) is located behind the main building. Please display your visitor pass clearly on the dashboard ___ (789) all times. Vehicles parked in reserved spots will be towed at the ___ (790) expense. Thank you for your ___ (791).\n\nFacilities Office'),
(789, 6, 'reading', 'Please display your pass clearly on the dashboard ___ all times.', '["at", "in", "on", "for"]', 0, 'Cum co dinh "at all times" (moi luc). EN: "At all times" is the fixed phrase meaning always.', 'prepositions', 'office', 737, 'PARKING GUIDE\nVisitors should park in Lot C, ___ (788) is located behind the main building. Please display your visitor pass clearly on the dashboard ___ (789) all times. Vehicles parked in reserved spots will be towed at the ___ (790) expense. Thank you for your ___ (791).\n\nFacilities Office'),
(790, 6, 'reading', 'Vehicles in reserved spots will be towed at the ___ expense.', '["owner''s", "owners", "owns", "owned"]', 0, 'Chi phi cua chu xe: the owner''s expense. EN: The cost borne by the owner uses the possessive: owner''s.', 'word-forms', 'office', 737, 'PARKING GUIDE\nVisitors should park in Lot C, ___ (788) is located behind the main building. Please display your visitor pass clearly on the dashboard ___ (789) all times. Vehicles parked in reserved spots will be towed at the ___ (790) expense. Thank you for your ___ (791).\n\nFacilities Office'),
(791, 6, 'reading', 'Thank you for your ___.', '["cooperation", "cooperate", "cooperated", "cooperative"]', 0, 'Can danh tu sau "your": cooperation (su hop tac). EN: After "your", use the noun: cooperation.', 'word-forms', 'office', 737, 'PARKING GUIDE\nVisitors should park in Lot C, ___ (788) is located behind the main building. Please display your visitor pass clearly on the dashboard ___ (789) all times. Vehicles parked in reserved spots will be towed at the ___ (790) expense. Thank you for your ___ (791).\n\nFacilities Office'),
-- Part 6, Text 19: online course ad (ids 792-795, passage 738)
(792, 6, 'reading', 'Learn business English ___ your own pace with TalkPro Online.', '["in", "at", "on", "for"]', 1, 'Cum co dinh "at your own pace" (theo nhip rieng). EN: "At your own pace" is the fixed phrase for self-paced learning.', 'prepositions', 'hr', 738, 'STUDY ANYWHERE\nLearn business English ___ (792) your own pace with TalkPro Online. Our courses feature live classes, interactive quizzes, and personal feedback from certified ___ (793). New learners can try the first week ___ (794) of charge. Enroll now and join 20,000 professionals ___ (795) upgraded their skills with us.\n\nTalkPro Online'),
(793, 6, 'reading', 'Personal feedback from certified ___.', '["instructors", "instruct", "instruction", "instructed"]', 0, 'Can danh tu chi nguoi so nhieu: instructors. EN: People need the plural person noun: instructors.', 'word-forms', 'hr', 738, 'STUDY ANYWHERE\nLearn business English ___ (792) your own pace with TalkPro Online. Our courses feature live classes, interactive quizzes, and personal feedback from certified ___ (793). New learners can try the first week ___ (794) of charge. Enroll now and join 20,000 professionals ___ (795) upgraded their skills with us.\n\nTalkPro Online'),
(794, 6, 'reading', 'New learners can try the first week ___ of charge.', '["free", "freely", "freedom", "freed"]', 0, 'Cum co dinh "free of charge" (mien phi). EN: "Free of charge" is the fixed phrase meaning at no cost.', 'vocabulary', 'hr', 738, 'STUDY ANYWHERE\nLearn business English ___ (792) your own pace with TalkPro Online. Our courses feature live classes, interactive quizzes, and personal feedback from certified ___ (793). New learners can try the first week ___ (794) of charge. Enroll now and join 20,000 professionals ___ (795) upgraded their skills with us.\n\nTalkPro Online'),
(795, 6, 'reading', 'Join 20,000 professionals ___ upgraded their skills with us.', '["who have", "which have", "whose have", "whom have"]', 0, 'Menh de quan he chi nguoi + hien tai hoan thanh: who have upgraded. EN: People as subject with present perfect need "who have".', 'relative-clauses', 'hr', 738, 'STUDY ANYWHERE\nLearn business English ___ (792) your own pace with TalkPro Online. Our courses feature live classes, interactive quizzes, and personal feedback from certified ___ (793). New learners can try the first week ___ (794) of charge. Enroll now and join 20,000 professionals ___ (795) upgraded their skills with us.\n\nTalkPro Online'),
-- Part 6, Text 20: maintenance request reply (ids 796-799, passage 739)
(796, 6, 'reading', 'Your maintenance request ___ received and logged as ticket 4471.', '["has been", "have been", "is being", "was being"]', 0, 'Hien tai hoan thanh bi dong (yeu cau vua duoc ghi nhan): has been received. EN: Present perfect passive for a just-logged request: has been received.', 'passive', 'support', 739, 'Dear Tenant,\n\nYour maintenance request ___ (796) received and logged as ticket 4471. A technician will visit your unit ___ (797) Thursday afternoon. Please ensure someone is present to provide ___ (798) to the equipment. We apologize for the delay and appreciate your ___ (799).\n\nBuilding Maintenance'),
(797, 6, 'reading', 'A technician will visit your unit ___ Thursday afternoon.', '["in", "at", "on", "for"]', 2, 'Buoi cu the trong tuan (Thursday afternoon) dung "on". EN: A specific weekday part takes "on".', 'prepositions', 'support', 739, 'Dear Tenant,\n\nYour maintenance request ___ (796) received and logged as ticket 4471. A technician will visit your unit ___ (797) Thursday afternoon. Please ensure someone is present to provide ___ (798) to the equipment. We apologize for the delay and appreciate your ___ (799).\n\nBuilding Maintenance'),
(798, 6, 'reading', 'Please provide ___ to the equipment.', '["access", "accessible", "accessing", "accessed"]', 0, '"Provide access to" (cho phep tiep can). EN: "Provide access to" is the fixed collocation.', 'vocabulary', 'support', 739, 'Dear Tenant,\n\nYour maintenance request ___ (796) received and logged as ticket 4471. A technician will visit your unit ___ (797) Thursday afternoon. Please ensure someone is present to provide ___ (798) to the equipment. We apologize for the delay and appreciate your ___ (799).\n\nBuilding Maintenance'),
(799, 6, 'reading', 'We appreciate your ___.', '["patience", "patient", "patiently", "patients"]', 0, 'Can danh tu sau "your": patience. EN: After "your", use the noun: patience.', 'word-forms', 'support', 739, 'Dear Tenant,\n\nYour maintenance request ___ (796) received and logged as ticket 4471. A technician will visit your unit ___ (797) Thursday afternoon. Please ensure someone is present to provide ___ (798) to the equipment. We apologize for the delay and appreciate your ___ (799).\n\nBuilding Maintenance')
ON CONFLICT (id) DO NOTHING;
