-- TOEIC Reading Part 7 batch 3 (ids 800-849): 14 doan don + 1 doan kep (50 cau), format de that.
-- Giai thich song ngu Viet-Anh. Cau hoi tron main-idea / detail / inference / vocabulary.

-- P7 single 1: store notice (ids 800-802, passage 800)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(800, 7, 'reading', 'What is the purpose of the notice?', '["To announce new weekend opening hours", "To advertise a clearance sale", "To hire weekend cashiers", "To close a store branch"]', 0, 'Thong bao gio mo cua moi cuoi tuan (Sat-Sun 9-9). EN: The notice announces new weekend hours.', 'comprehension', 'sales', 800, 'NOTICE\nGreenMart Supermarket\n\nStarting July 1, we will open every Saturday and Sunday from 9 a.m. to 9 p.m. Weekday hours remain 8 a.m. to 10 p.m. Thank you for shopping with us.'),
(801, 7, 'reading', 'According to the notice, when will the store open on Sundays?', '["At 9 a.m.", "At 8 a.m.", "At 10 a.m.", "At 7 a.m."]', 0, 'Cuoi tuan mo cua 9 gio sang. EN: Weekend opening time is 9 a.m.', 'comprehension', 'sales', 800, 'NOTICE\nGreenMart Supermarket\n\nStarting July 1, we will open every Saturday and Sunday from 9 a.m. to 9 p.m. Weekday hours remain 8 a.m. to 10 p.m. Thank you for shopping with us.'),
(802, 7, 'reading', 'What can be inferred about weekday hours?', '["They stay the same", "They are shortened", "They are extended", "They are not mentioned"]', 0, 'Ghi ro "Weekday hours remain..." (giu nguyen). EN: "Weekday hours remain..." means unchanged.', 'comprehension', 'sales', 800, 'NOTICE\nGreenMart Supermarket\n\nStarting July 1, we will open every Saturday and Sunday from 9 a.m. to 9 p.m. Weekday hours remain 8 a.m. to 10 p.m. Thank you for shopping with us.'),
-- P7 single 2: recruitment email (ids 803-805, passage 801)
(803, 7, 'reading', 'Why was this email sent?', '["To schedule a second interview", "To reject an application", "To offer a salary raise", "To cancel a meeting"]', 0, 'Email moi phong van vong 2 (thu 4, 2 gio, gap Mr. Fox). EN: The email invites the reader to a second interview.', 'comprehension', 'hr', 801, 'Dear Ms. Tran,\n\nThank you for interviewing for the accountant position last week. We would like to invite you to a second interview on Wednesday at 2 p.m. with our finance director, Mr. Fox. Please bring your degree certificates.\n\nBest regards,\nMs. Hill, HR'),
(804, 7, 'reading', 'Who will Ms. Tran meet on Wednesday?', '["Mr. Fox", "Ms. Hill", "The CEO", "A client"]', 0, 'Phong van voi giam doc tai chinh Mr. Fox. EN: The second interview is with finance director Mr. Fox.', 'comprehension', 'hr', 801, 'Dear Ms. Tran,\n\nThank you for interviewing for the accountant position last week. We would like to invite you to a second interview on Wednesday at 2 p.m. with our finance director, Mr. Fox. Please bring your degree certificates.\n\nBest regards,\nMs. Hill, HR'),
(805, 7, 'reading', 'What is Ms. Tran asked to bring?', '["Her degree certificates", "Her passport", "A laptop", "A reference letter"]', 0, 'Email dan "Please bring your degree certificates". EN: "Please bring your degree certificates" is explicit.', 'comprehension', 'hr', 801, 'Dear Ms. Tran,\n\nThank you for interviewing for the accountant position last week. We would like to invite you to a second interview on Wednesday at 2 p.m. with our finance director, Mr. Fox. Please bring your degree certificates.\n\nBest regards,\nMs. Hill, HR'),
-- P7 single 3: product review (ids 806-808, passage 802)
(806, 7, 'reading', 'What does the reviewer like most about the headphones?', '["The battery life", "The low price", "The bright colors", "The free case"]', 0, 'Nguoi viet khen pin 40 gio la diem manh nhat. EN: The 40-hour battery is praised as the strongest point.', 'comprehension', 'marketing', 802, 'SoundMax Headphones - Customer Review\n\nI bought these headphones three months ago. The battery lasts 40 hours, which is the best part. The sound is clear, though the ear cushions feel a bit tight at first. Shipping was fast, arriving in two days. Overall, great value for $89.'),
(807, 7, 'reading', 'What minor problem does the reviewer mention?', '["Tight ear cushions", "Broken buttons", "Late delivery", "Poor packaging"]', 0, 'Miem lot tai hoi chat luc dau ("a bit tight at first"). EN: "A bit tight at first" is the only complaint.', 'comprehension', 'marketing', 802, 'SoundMax Headphones - Customer Review\n\nI bought these headphones three months ago. The battery lasts 40 hours, which is the best part. The sound is clear, though the ear cushions feel a bit tight at first. Shipping was fast, arriving in two days. Overall, great value for $89.'),
(808, 7, 'reading', 'The word "value" in the review is closest in meaning to ___.', '["worth for the price", "moral principle", "loud sound", "expensive gift"]', 0, '"Great value for $89" = dang tien. EN: "Great value" means worth the price.', 'vocabulary', 'marketing', 802, 'SoundMax Headphones - Customer Review\n\nI bought these headphones three months ago. The battery lasts 40 hours, which is the best part. The sound is clear, though the ear cushions feel a bit tight at first. Shipping was fast, arriving in two days. Overall, great value for $89.'),
-- P7 single 4: conference agenda (ids 809-812, passage 803)
(809, 7, 'reading', 'What event is described?', '["A one-day sales conference", "A product launch party", "A job fair", "A charity dinner"]', 0, 'Chuong trinh hoi nghi ban hang 1 ngay (9h-17h). EN: A one-day sales conference program is shown.', 'comprehension', 'meetings', 803, 'Annual Sales Conference - October 5\n\n9:00 Opening speech by CEO\n10:30 New product showcase\n12:00 Lunch (provided)\n13:30 Regional team workshops\n15:30 Awards ceremony\n17:00 Closing remarks\n\nVenue: Riverside Hall. All sales staff must attend.'),
(810, 7, 'reading', 'According to the agenda, what happens at 12:00?', '["Lunch is served", "The awards begin", "Workshops start", "The CEO speaks"]', 0, '12:00 Lunch (provided). EN: Lunch is listed at 12:00.', 'comprehension', 'meetings', 803, 'Annual Sales Conference - October 5\n\n9:00 Opening speech by CEO\n10:30 New product showcase\n12:00 Lunch (provided)\n13:30 Regional team workshops\n15:30 Awards ceremony\n17:00 Closing remarks\n\nVenue: Riverside Hall. All sales staff must attend.'),
(811, 7, 'reading', 'Who is required to attend?', '["All sales staff", "Only managers", "All customers", "New interns"]', 0, 'Ghi ro "All sales staff must attend". EN: "All sales staff must attend" is explicit.', 'comprehension', 'meetings', 803, 'Annual Sales Conference - October 5\n\n9:00 Opening speech by CEO\n10:30 New product showcase\n12:00 Lunch (provided)\n13:30 Regional team workshops\n15:30 Awards ceremony\n17:00 Closing remarks\n\nVenue: Riverside Hall. All sales staff must attend.'),
(812, 7, 'reading', 'Where will the event take place?', '["At Riverside Hall", "At the head office", "At a hotel", "Online"]', 0, 'Dia diem: Riverside Hall. EN: The venue line names Riverside Hall.', 'comprehension', 'meetings', 803, 'Annual Sales Conference - October 5\n\n9:00 Opening speech by CEO\n10:30 New product showcase\n12:00 Lunch (provided)\n13:30 Regional team workshops\n15:30 Awards ceremony\n17:00 Closing remarks\n\nVenue: Riverside Hall. All sales staff must attend.'),
-- P7 single 5: bank fee schedule (ids 813-815, passage 804)
(813, 7, 'reading', 'What is the document about?', '["Monthly account fees and how to avoid them", "New loan interest rates", "Branch holiday hours", "Currency exchange rules"]', 0, 'Bang phi tai khoan hang thang + cach mien phi. EN: Monthly fees and waiver conditions are listed.', 'comprehension', 'finance', 804, 'CityTrust Bank - Fee Schedule (from Sept 1)\n\nBasic account: $5/month, waived with balance over $500.\nPremium account: $12/month, waived with balance over $2,000.\nPaper statements: $2 each; e-statements are free.'),
(814, 7, 'reading', 'How can a Basic account holder avoid the monthly fee?', '["By keeping over $500 in the account", "By visiting a branch", "By using e-statements only", "By opening a second account"]', 0, 'Mien phi khi so du tren $500. EN: A balance over $500 waives the Basic fee.', 'comprehension', 'finance', 804, 'CityTrust Bank - Fee Schedule (from Sept 1)\n\nBasic account: $5/month, waived with balance over $500.\nPremium account: $12/month, waived with balance over $2,000.\nPaper statements: $2 each; e-statements are free.'),
(815, 7, 'reading', 'The word "waived" in the schedule is closest in meaning to ___.', '["removed", "increased", "delayed", "doubled"]', 0, '"Waived" (duoc mien) gan nghia removed (duoc bo). EN: "Waived" means cancelled or removed.', 'vocabulary', 'finance', 804, 'CityTrust Bank - Fee Schedule (from Sept 1)\n\nBasic account: $5/month, waived with balance over $500.\nPremium account: $12/month, waived with balance over $2,000.\nPaper statements: $2 each; e-statements are free.'),
-- P7 single 6: job ad (ids 816-818, passage 805)
(816, 7, 'reading', 'What position is being advertised?', '["A full-time delivery driver", "A part-time cashier", "A warehouse manager", "An office cleaner"]', 0, 'Tuyen lai xe giao hang full-time. EN: A full-time delivery driver is advertised.', 'comprehension', 'hr', 805, 'HIRING: Delivery Driver (full-time)\n\nCityFresh Groceries needs a full-time delivery driver. Requirements: valid license, 1 year experience. Salary: $18/hour plus fuel allowance. Apply in person at 88 Market Street before July 20.'),
(817, 7, 'reading', 'What is required for the job?', '["A valid license and 1 year of experience", "A college degree", "English fluency", "Night-shift availability"]', 0, 'Yeu cau: bang lai hop le + 1 nam kinh nghiem. EN: A valid license and 1 year of experience are required.', 'comprehension', 'hr', 805, 'HIRING: Delivery Driver (full-time)\n\nCityFresh Groceries needs a full-time delivery driver. Requirements: valid license, 1 year experience. Salary: $18/hour plus fuel allowance. Apply in person at 88 Market Street before July 20.'),
(818, 7, 'reading', 'How should candidates apply?', '["In person at 88 Market Street", "By email", "By phone call", "Through a website"]', 0, 'Nop don truc tiep tai 88 Market Street. EN: "Apply in person" is explicit.', 'comprehension', 'hr', 805, 'HIRING: Delivery Driver (full-time)\n\nCityFresh Groceries needs a full-time delivery driver. Requirements: valid license, 1 year experience. Salary: $18/hour plus fuel allowance. Apply in person at 88 Market Street before July 20.'),
-- P7 single 7: museum announcement (ids 819-821, passage 806)
(819, 7, 'reading', 'What is special about the photography exhibit?', '["It offers free entry on opening day", "It shows only local artists", "It runs for one week", "It requires booking a year ahead"]', 0, 'Mien phi ve ngay khai mac (June 3). EN: Free entry on opening day is the special offer.', 'comprehension', 'general', 806, 'City Museum - Photography Exhibit "Light and Streets"\n\nJune 3 - August 30. Over 120 photos from 15 countries. Opening day (June 3): free entry for all visitors. Guided tours in English every Saturday at 11 a.m. Audio guides available in 4 languages.'),
(820, 7, 'reading', 'When are English guided tours held?', '["Saturdays at 11 a.m.", "Sundays at 2 p.m.", "Daily at 9 a.m.", "Fridays at 3 p.m."]', 0, 'Tour tieng Anh thu 7 luc 11 gio sang. EN: English tours run Saturdays at 11 a.m.', 'comprehension', 'general', 806, 'City Museum - Photography Exhibit "Light and Streets"\n\nJune 3 - August 30. Over 120 photos from 15 countries. Opening day (June 3): free entry for all visitors. Guided tours in English every Saturday at 11 a.m. Audio guides available in 4 languages.'),
(821, 7, 'reading', 'What can be inferred about the exhibit?', '["It features international works", "It is only for members", "It has no photographs", "It closes in winter"]', 0, '120 anh tu 15 nuoc -> mang tinh quoc te. EN: Photos from 15 countries imply international scope.', 'comprehension', 'general', 806, 'City Museum - Photography Exhibit "Light and Streets"\n\nJune 3 - August 30. Over 120 photos from 15 countries. Opening day (June 3): free entry for all visitors. Guided tours in English every Saturday at 11 a.m. Audio guides available in 4 languages.'),
-- P7 single 8: shipping memo (ids 822-825, passage 807)
(822, 7, 'reading', 'What change is announced?', '["A new cutoff time for same-day shipping", "A new warehouse location", "Lower shipping fees", "Free weekend delivery"]', 0, 'Gio cat don hang trong ngay doi sang 2 gio chieu. EN: Same-day orders now need placement by 2 p.m.', 'comprehension', 'logistics', 807, 'MEMO: Shipping Cutoff Change\n\nFrom Monday, orders must be placed by 2 p.m. (previously 4 p.m.) to qualify for same-day shipping. Orders after 2 p.m. ship the next business day. Please update the website banner today. Questions: contact Logistics, ext. 441.'),
(823, 7, 'reading', 'What happens to orders placed at 3 p.m.?', '["They ship the next business day", "They ship the same day", "They are canceled", "They cost extra"]', 0, 'Sau 2 gio -> giao ngay lam viec hom sau. EN: After 2 p.m., shipment moves to the next business day.', 'comprehension', 'logistics', 807, 'MEMO: Shipping Cutoff Change\n\nFrom Monday, orders must be placed by 2 p.m. (previously 4 p.m.) to qualify for same-day shipping. Orders after 2 p.m. ship the next business day. Please update the website banner today. Questions: contact Logistics, ext. 441.'),
(824, 7, 'reading', 'What are employees asked to do today?', '["Update the website banner", "Call all customers", "Close the warehouse", "Print new labels"]', 0, 'Yeu cau cap nhat banner website ngay hom nay. EN: "Please update the website banner today" is explicit.', 'comprehension', 'logistics', 807, 'MEMO: Shipping Cutoff Change\n\nFrom Monday, orders must be placed by 2 p.m. (previously 4 p.m.) to qualify for same-day shipping. Orders after 2 p.m. ship the next business day. Please update the website banner today. Questions: contact Logistics, ext. 441.'),
(825, 7, 'reading', 'Who should employees contact with questions?', '["The Logistics team at ext. 441", "The IT helpdesk", "The warehouse guard", "Ms. Rivera"]', 0, 'Lien he Logistics, so noi bo 441. EN: "Contact Logistics, ext. 441" is explicit.', 'comprehension', 'logistics', 807, 'MEMO: Shipping Cutoff Change\n\nFrom Monday, orders must be placed by 2 p.m. (previously 4 p.m.) to qualify for same-day shipping. Orders after 2 p.m. ship the next business day. Please update the website banner today. Questions: contact Logistics, ext. 441.'),
-- P7 single 9: course schedule (ids 826-828, passage 808)
(826, 7, 'reading', 'What course is described?', '["An evening business writing course", "A morning cooking class", "A weekend photography tour", "An online driving course"]', 0, 'Khoa viet kinh doanh buoi toi (Tue-Thu 7-9pm). EN: An evening business writing course is described.', 'comprehension', 'hr', 808, 'Evening Course: Business Writing Basics\n\nTuesdays and Thursdays, 7-9 p.m., Room 402. Six weeks starting May 6. Fee: $120 (materials included). Instructor: Mr. Owen. Register at the front desk by May 1.'),
(827, 7, 'reading', 'How much does the course cost?', '["$120 including materials", "$90 plus materials", "$150 in total", "$60 per week"]', 0, 'Hoc phi $120 da gom tai lieu. EN: "$120 (materials included)" is explicit.', 'comprehension', 'hr', 808, 'Evening Course: Business Writing Basics\n\nTuesdays and Thursdays, 7-9 p.m., Room 402. Six weeks starting May 6. Fee: $120 (materials included). Instructor: Mr. Owen. Register at the front desk by May 1.'),
(828, 7, 'reading', 'When is the registration deadline?', '["May 1", "May 6", "June 1", "April 20"]', 0, 'Dang ky truoc ngay 1 thang 5. EN: "Register ... by May 1" is explicit.', 'comprehension', 'hr', 808, 'Evening Course: Business Writing Basics\n\nTuesdays and Thursdays, 7-9 p.m., Room 402. Six weeks starting May 6. Fee: $120 (materials included). Instructor: Mr. Owen. Register at the front desk by May 1.'),
-- P7 single 10: warranty card (ids 829-831, passage 809)
(829, 7, 'reading', 'How long is the warranty period?', '["Two years for parts and labor", "One year for parts only", "Three years for labor only", "Lifetime for parts"]', 0, 'Bao hanh 2 nam linh kien + nhan cong. EN: Two years for parts and labor is stated.', 'comprehension', 'support', 809, 'WARRANTY CARD - HomeCool Air Conditioner\n\nTwo-year warranty on parts and labor from the purchase date. To claim service, present this card and the original receipt. Damage from misuse is not covered. Call 1800-2266 for appointments.'),
(830, 7, 'reading', 'What must customers present to claim service?', '["The card and the original receipt", "A photo ID only", "The product box", "A bank statement"]', 0, 'Can xuat the + hoa don goc. EN: "This card and the original receipt" are required.', 'comprehension', 'support', 809, 'WARRANTY CARD - HomeCool Air Conditioner\n\nTwo-year warranty on parts and labor from the purchase date. To claim service, present this card and the original receipt. Damage from misuse is not covered. Call 1800-2266 for appointments.'),
(831, 7, 'reading', 'What is NOT covered by the warranty?', '["Damage from misuse", "Faulty parts", "Labor costs", "Electrical failures"]', 0, 'Hu hong do dung sai khong duoc bao hanh. EN: "Damage from misuse is not covered" is explicit.', 'comprehension', 'support', 809, 'WARRANTY CARD - HomeCool Air Conditioner\n\nTwo-year warranty on parts and labor from the purchase date. To claim service, present this card and the original receipt. Damage from misuse is not covered. Call 1800-2266 for appointments.'),
-- P7 single 11: restaurant coupon (ids 832-834, passage 810)
(832, 7, 'reading', 'What does the coupon offer?', '["20% off dinner bills over $40", "Free lunch every day", "50% off all drinks", "A free birthday cake"]', 0, 'Giam 20% hoa don toi tren $40. EN: 20% off dinner bills over $40 is offered.', 'comprehension', 'marketing', 810, 'Harbor Restaurant - Dinner Coupon\n\nEnjoy 20% off your dinner bill over $40, Sunday to Thursday. One coupon per table. Not valid with other promotions. Present this coupon before ordering. Valid until Dec 31.'),
(833, 7, 'reading', 'On which days can the coupon be used?', '["Sunday to Thursday", "Friday and Saturday", "Every day", "Holidays only"]', 0, 'Ap dung Chu nhat den Thu 5. EN: "Sunday to Thursday" is stated.', 'comprehension', 'marketing', 810, 'Harbor Restaurant - Dinner Coupon\n\nEnjoy 20% off your dinner bill over $40, Sunday to Thursday. One coupon per table. Not valid with other promotions. Present this coupon before ordering. Valid until Dec 31.'),
(834, 7, 'reading', 'The word "present" in the coupon is closest in meaning to ___.', '["show", "gift", "introduce", "attend"]', 0, '"Present this coupon" = xuat/trinh coupon. EN: "Present" here means to show.', 'vocabulary', 'marketing', 810, 'Harbor Restaurant - Dinner Coupon\n\nEnjoy 20% off your dinner bill over $40, Sunday to Thursday. One coupon per table. Not valid with other promotions. Present this coupon before ordering. Valid until Dec 31.'),
-- P7 single 12: flight e-ticket (ids 835-838, passage 811)
(835, 7, 'reading', 'What type of document is shown?', '["An electronic flight ticket", "A hotel booking", "A visa approval", "A bus timetable"]', 0, 'Ve may bay dien tu (e-ticket). EN: Flight number, gate, and boarding time mark an e-ticket.', 'comprehension', 'travel', 811, 'E-TICKET - VN Airlines\nFlight VN612, Hanoi to Tokyo. Date: Aug 12. Boarding: 9:10 a.m., Gate 7. Seat 24A. Baggage allowance: 23 kg checked + 7 kg carry-on. Please arrive 2 hours early.'),
(836, 7, 'reading', 'What time does boarding begin?', '["9:10 a.m.", "9:40 a.m.", "8:00 a.m.", "10:10 a.m."]', 0, 'Len may bay luc 9:10 sang. EN: "Boarding: 9:10 a.m." is explicit.', 'comprehension', 'travel', 811, 'E-TICKET - VN Airlines\nFlight VN612, Hanoi to Tokyo. Date: Aug 12. Boarding: 9:10 a.m., Gate 7. Seat 24A. Baggage allowance: 23 kg checked + 7 kg carry-on. Please arrive 2 hours early.'),
(837, 7, 'reading', 'How much checked baggage is allowed?', '["23 kg", "7 kg", "30 kg", "15 kg"]', 0, 'Hanh ly ky gui 23 kg (xach tay 7 kg). EN: 23 kg checked baggage is allowed.', 'comprehension', 'travel', 811, 'E-TICKET - VN Airlines\nFlight VN612, Hanoi to Tokyo. Date: Aug 12. Boarding: 9:10 a.m., Gate 7. Seat 24A. Baggage allowance: 23 kg checked + 7 kg carry-on. Please arrive 2 hours early.'),
(838, 7, 'reading', 'What are passengers advised to do?', '["Arrive 2 hours early", "Print the ticket twice", "Call the airline", "Change seats"]', 0, 'Khuyen den som 2 tieng. EN: "Please arrive 2 hours early" is explicit.', 'comprehension', 'travel', 811, 'E-TICKET - VN Airlines\nFlight VN612, Hanoi to Tokyo. Date: Aug 12. Boarding: 9:10 a.m., Gate 7. Seat 24A. Baggage allowance: 23 kg checked + 7 kg carry-on. Please arrive 2 hours early.'),
-- P7 single 13: office supply order (ids 839-841, passage 812)
(839, 7, 'reading', 'What is the main topic of the order?', '["Restocking office stationery", "Hiring new assistants", "Repairing printers", "Planning a party"]', 0, 'Don dat van phong pham (giay, muc, but). EN: Paper, ink, and pens mark a stationery order.', 'comprehension', 'office', 812, 'Order #5521 - Office Stationery\n\n20 reams A4 paper, 10 black ink cartridges, 30 ballpoint pens. Total: $486. Delivery to Room 301 by Friday. Contact: Ms. Vy, ext. 220.'),
(840, 7, 'reading', 'What is the total amount of the order?', '["$486", "$468", "$846", "$4860"]', 0, 'Tong cong $486. EN: "Total: $486" is explicit.', 'comprehension', 'office', 812, 'Order #5521 - Office Stationery\n\n20 reams A4 paper, 10 black ink cartridges, 30 ballpoint pens. Total: $486. Delivery to Room 301 by Friday. Contact: Ms. Vy, ext. 220.'),
(841, 7, 'reading', 'Where should the items be delivered?', '["Room 301", "Room 103", "The lobby", "The warehouse"]', 0, 'Giao den phong 301. EN: "Delivery to Room 301" is explicit.', 'comprehension', 'office', 812, 'Order #5521 - Office Stationery\n\n20 reams A4 paper, 10 black ink cartridges, 30 ballpoint pens. Total: $486. Delivery to Room 301 by Friday. Contact: Ms. Vy, ext. 220.'),
-- P7 double 1: complaint email + reply (ids 842-845, passage 813)
(842, 7, 'reading', 'What problem does Mr. Cole report?', '["A scratched conference table", "A missing chair", "A broken lamp", "A late delivery"]', 0, 'Ban hop bi xuoc mat (email 1). EN: A scratched table surface is reported.', 'comprehension', 'support', 813, 'Email 1 - From: Mr. Cole\nThe conference table delivered yesterday has a long scratch on its surface. Please arrange a replacement this week.\n\nEmail 2 - From: BrightOffice Furniture\nWe are sorry about the scratched table. A replacement will arrive Thursday morning, and our team will take away the damaged one. As an apology, we include a free desk organizer.'),
(843, 7, 'reading', 'When will the replacement arrive?', '["Thursday morning", "Friday evening", "Monday noon", "Wednesday night"]', 0, 'Hang thay the den sang thu 5 (email 2). EN: "Arrive Thursday morning" is stated in the reply.', 'comprehension', 'support', 813, 'Email 1 - From: Mr. Cole\nThe conference table delivered yesterday has a long scratch on its surface. Please arrange a replacement this week.\n\nEmail 2 - From: BrightOffice Furniture\nWe are sorry about the scratched table. A replacement will arrive Thursday morning, and our team will take away the damaged one. As an apology, we include a free desk organizer.'),
(844, 7, 'reading', 'What does the furniture company offer as an apology?', '["A free desk organizer", "A full refund", "A discount coupon", "Free delivery forever"]', 0, 'Tang kem hop dung do mien phi. EN: "A free desk organizer" is offered.', 'comprehension', 'support', 813, 'Email 1 - From: Mr. Cole\nThe conference table delivered yesterday has a long scratch on its surface. Please arrange a replacement this week.\n\nEmail 2 - From: BrightOffice Furniture\nWe are sorry about the scratched table. A replacement will arrive Thursday morning, and our team will take away the damaged one. As an apology, we include a free desk organizer.'),
(845, 7, 'reading', 'What will the delivery team do with the damaged table?', '["Take it away", "Repair it on-site", "Leave it there", "Sell it cheaply"]', 0, 'Doi giao hang se mang ban hong di. EN: "Take away the damaged one" is stated.', 'comprehension', 'support', 813, 'Email 1 - From: Mr. Cole\nThe conference table delivered yesterday has a long scratch on its surface. Please arrange a replacement this week.\n\nEmail 2 - From: BrightOffice Furniture\nWe are sorry about the scratched table. A replacement will arrive Thursday morning, and our team will take away the damaged one. As an apology, we include a free desk organizer.'),
-- P7 single 14: company outing email (ids 846-849, passage 839)
(846, 7, 'reading', 'What event is being planned?', '["A company outing to Ba Na Hills", "A client meeting downtown", "A training workshop", "A farewell lunch"]', 0, 'Chuyen di choi cong ty den Ba Na Hills. EN: A company outing to Ba Na Hills is planned.', 'comprehension', 'office', 839, 'Dear All,\n\nOur annual company outing will be to Ba Na Hills on Saturday, June 28. Buses leave the office at 7:00 a.m. sharp. Lunch and cable-car tickets are covered by the company. Please register with Ms. Thao by June 20.'),
(847, 7, 'reading', 'What time do the buses leave?', '["At 7:00 a.m. sharp", "At 8:00 a.m.", "At 6:30 a.m.", "At 9:00 a.m."]', 0, 'Xe khoi hanh dung 7 gio sang. EN: "Buses leave ... at 7:00 a.m. sharp" is stated.', 'comprehension', 'office', 839, 'Dear All,\n\nOur annual company outing will be to Ba Na Hills on Saturday, June 28. Buses leave the office at 7:00 a.m. sharp. Lunch and cable-car tickets are covered by the company. Please register with Ms. Thao by June 20.'),
(848, 7, 'reading', 'What does the company pay for?', '["Lunch and cable-car tickets", "Hotel rooms", "Souvenirs", "Dinner and drinks"]', 0, 'Cong ty tra bua trua + ve cap treo. EN: "Lunch and cable-car tickets are covered" is stated.', 'comprehension', 'office', 839, 'Dear All,\n\nOur annual company outing will be to Ba Na Hills on Saturday, June 28. Buses leave the office at 7:00 a.m. sharp. Lunch and cable-car tickets are covered by the company. Please register with Ms. Thao by June 20.'),
(849, 7, 'reading', 'The word "sharp" in the email is closest in meaning to ___.', '["exactly", "quickly", "loudly", "safely"]', 0, '"7:00 sharp" = dung 7 gio. EN: "Sharp" with time means exactly.', 'vocabulary', 'office', 839, 'Dear All,\n\nOur annual company outing will be to Ba Na Hills on Saturday, June 28. Buses leave the office at 7:00 a.m. sharp. Lunch and cable-car tickets are covered by the company. Please register with Ms. Thao by June 20.')
ON CONFLICT (id) DO NOTHING;
