-- TOEIC Reading Part 7 batch 4 (ids 850-899): 8 doan don + 2 doan kep (50 cau).
-- Giai thich song ngu Viet-Anh.

-- P7 single 14: seminar flyer (ids 850-852, passage 814)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(850, 7, 'reading', 'What is the seminar about?', '["Time management skills", "Cooking techniques", "Car maintenance", "Photography basics"]', 0, 'Hoi thao ky nang quan ly thoi gian. EN: A time management seminar is advertised.', 'comprehension', 'hr', 814, 'FREE SEMINAR: Master Your Time\n\nSaturday, June 14, 9 a.m.-12 p.m., Central Library Hall. Learn to plan your week, cut wasted meetings, and meet deadlines calmly. Seats limited to 80. Register online by June 10.'),
(851, 7, 'reading', 'How many seats are available?', '["80", "60", "100", "50"]', 0, 'Gioi han 80 ghe. EN: "Seats limited to 80" is explicit.', 'comprehension', 'hr', 814, 'FREE SEMINAR: Master Your Time\n\nSaturday, June 14, 9 a.m.-12 p.m., Central Library Hall. Learn to plan your week, cut wasted meetings, and meet deadlines calmly. Seats limited to 80. Register online by June 10.'),
(852, 7, 'reading', 'What is the registration deadline?', '["June 10", "June 14", "July 10", "May 30"]', 0, 'Dang ky truoc ngay 10 thang 6. EN: "Register online by June 10" is explicit.', 'comprehension', 'hr', 814, 'FREE SEMINAR: Master Your Time\n\nSaturday, June 14, 9 a.m.-12 p.m., Central Library Hall. Learn to plan your week, cut wasted meetings, and meet deadlines calmly. Seats limited to 80. Register online by June 10.'),
-- P7 single 15: hotel bill (ids 853-855, passage 815)
(853, 7, 'reading', 'How many nights did the guest stay?', '["Three nights", "Two nights", "Four nights", "One night"]', 0, 'Luu tru 3 dem (May 3-6 checkout → 3 dem, $150x3=$450). EN: Three nights at $150 total $450.', 'comprehension', 'travel', 815, 'Seaside Hotel - Guest Bill\nGuest: Mr. Alan. Check-in May 3, check-out May 6.\nRoom charges: $150 x 3 nights = $450. Breakfast included. Parking: $20. Total: $470.'),
(854, 7, 'reading', 'What is the total amount?', '["$470", "$450", "$500", "$490"]', 0, 'Tong $470 (phong $450 + do xe $20). EN: $450 room plus $20 parking totals $470.', 'comprehension', 'travel', 815, 'Seaside Hotel - Guest Bill\nGuest: Mr. Alan. Check-in May 3, check-out May 6.\nRoom charges: $150 x 3 nights = $450. Breakfast included. Parking: $20. Total: $470.'),
(855, 7, 'reading', 'Which service was free?', '["Breakfast", "Parking", "Wi-Fi", "Laundry"]', 0, 'An sang mien phi (Breakfast included); do xe $20. EN: "Breakfast included" means free; parking costs $20.', 'comprehension', 'travel', 815, 'Seaside Hotel - Guest Bill\nGuest: Mr. Alan. Check-in May 3, check-out May 6.\nRoom charges: $150 x 3 nights = $450. Breakfast included. Parking: $20. Total: $470.'),
-- P7 single 16: weather advisory (ids 856-858, passage 816)
(856, 7, 'reading', 'What weather event is warned about?', '["A typhoon approaching the coast", "A heat wave inland", "Heavy snow in the mountains", "A long drought"]', 0, 'Canh bao bao bien sap do bo. EN: A typhoon nearing the coast is warned about.', 'comprehension', 'general', 816, 'WEATHER ADVISORY\nTyphoon Noru is approaching the central coast and will make landfall Friday evening. Residents should secure outdoor items and avoid beaches. Schools in Da Nang and Hue will close Friday.'),
(857, 7, 'reading', 'What are residents advised to do?', '["Secure outdoor items and avoid beaches", "Drive to the mountains", "Stock a month of food", "Leave the country"]', 0, 'Co dinh do dac ngoai troi + tranh bai bien. EN: Securing outdoor items and avoiding beaches are advised.', 'comprehension', 'general', 816, 'WEATHER ADVISORY\nTyphoon Noru is approaching the central coast and will make landfall Friday evening. Residents should secure outdoor items and avoid beaches. Schools in Da Nang and Hue will close Friday.'),
(858, 7, 'reading', 'Which schools will close on Friday?', '["Schools in Da Nang and Hue", "All schools nationwide", "Only private schools", "Schools in Hanoi"]', 0, 'Truong o Da Nang va Hue nghi thu 6. EN: Da Nang and Hue schools close Friday.', 'comprehension', 'general', 816, 'WEATHER ADVISORY\nTyphoon Noru is approaching the central coast and will make landfall Friday evening. Residents should secure outdoor items and avoid beaches. Schools in Da Nang and Hue will close Friday.'),
-- P7 single 17: phone message (ids 859-861, passage 817)
(859, 7, 'reading', 'Why did Ms. Dana call?', '["To reschedule Thursday''s delivery", "To cancel a contract", "To apply for a job", "To praise the service"]', 0, 'Goi de doi lich giao hang thu 5 sang thu 6. EN: Rescheduling Thursday delivery is the reason.', 'comprehension', 'logistics', 817, 'Phone message from Ms. Dana (Tue 4:15 p.m.): Please move Thursday''s delivery to Friday morning; our warehouse is closed Thursday for inventory. The driver can call me at 555-7741 on arrival. Thanks!'),
(860, 7, 'reading', 'Why is the warehouse closed on Thursday?', '["For inventory counting", "For repairs", "For a holiday", "For staff training"]', 0, 'Kho dong cua kiem ke (inventory). EN: "Closed Thursday for inventory" is explicit.', 'comprehension', 'logistics', 817, 'Phone message from Ms. Dana (Tue 4:15 p.m.): Please move Thursday''s delivery to Friday morning; our warehouse is closed Thursday for inventory. The driver can call me at 555-7741 on arrival. Thanks!'),
(861, 7, 'reading', 'What should the driver do on arrival?', '["Call Ms. Dana at 555-7741", "Wait two hours", "Unload alone", "Return the goods"]', 0, 'Tai xe goi so 555-7741 khi den. EN: "Call me at 555-7741 on arrival" is explicit.', 'comprehension', 'logistics', 817, 'Phone message from Ms. Dana (Tue 4:15 p.m.): Please move Thursday''s delivery to Friday morning; our warehouse is closed Thursday for inventory. The driver can call me at 555-7741 on arrival. Thanks!'),
-- P7 single 18: menu (ids 862-864, passage 818)
(862, 7, 'reading', 'What is the cheapest main dish on the menu?', '["Grilled chicken at $12", "Beef steak at $19", "Salmon at $17", "Pasta at $14"]', 0, 'Ga nuong $12 re nhat (bo $19, ca hoi $17, my Y $14). EN: $12 grilled chicken is the cheapest main.', 'comprehension', 'general', 818, 'Sunny Cafe - Lunch Menu\nGrilled chicken $12, Pasta $14, Salmon $17, Beef steak $19. All mains come with soup and iced tea. Dessert of the day: mango pudding $5.'),
(863, 7, 'reading', 'What comes with every main dish?', '["Soup and iced tea", "Salad and coffee", "Bread and juice", "Rice and cake"]', 0, 'Moi mon chinh kem sup + tra da. EN: "All mains come with soup and iced tea" is explicit.', 'comprehension', 'general', 818, 'Sunny Cafe - Lunch Menu\nGrilled chicken $12, Pasta $14, Salmon $17, Beef steak $19. All mains come with soup and iced tea. Dessert of the day: mango pudding $5.'),
(864, 7, 'reading', 'How much is the dessert of the day?', '["$5", "$4", "$6", "$7"]', 0, 'Trang mieng hom nay $5. EN: "Mango pudding $5" is listed.', 'comprehension', 'general', 818, 'Sunny Cafe - Lunch Menu\nGrilled chicken $12, Pasta $14, Salmon $17, Beef steak $19. All mains come with soup and iced tea. Dessert of the day: mango pudding $5.'),
-- P7 single 19: gym review (ids 865-867, passage 819)
(865, 7, 'reading', 'What does the writer praise about the gym?', '["Clean equipment and helpful trainers", "Cheap monthly fees", "24-hour opening", "A large swimming pool"]', 0, 'Khen thiet bi sach + HLV tan tinh. EN: Clean equipment and helpful trainers are praised.', 'comprehension', 'general', 819, 'Member review - PowerGym\nI joined PowerGym in January. Machines are always clean, and trainers show me correct form. It gets crowded after 6 p.m., so I go in the morning. Parking is tight on weekends. Still, I renewed for a year.'),
(866, 7, 'reading', 'What problem is mentioned?', '["Crowds after 6 p.m.", "Rude staff", "Broken machines", "High prices"]', 0, 'Dong sau 6 gio toi. EN: "Crowded after 6 p.m." is the complaint.', 'comprehension', 'general', 819, 'Member review - PowerGym\nI joined PowerGym in January. Machines are always clean, and trainers show me correct form. It gets crowded after 6 p.m., so I go in the morning. Parking is tight on weekends. Still, I renewed for a year.'),
(867, 7, 'reading', 'What did the writer do at the end?', '["Renewed for another year", "Canceled the membership", "Asked for a refund", "Switched gyms"]', 0, 'Gia han them 1 nam. EN: "I renewed for a year" is stated.', 'comprehension', 'general', 819, 'Member review - PowerGym\nI joined PowerGym in January. Machines are always clean, and trainers show me correct form. It gets crowded after 6 p.m., so I go in the morning. Parking is tight on weekends. Still, I renewed for a year.'),
-- P7 single 20: sale notice (ids 868-870, passage 820)
(868, 7, 'reading', 'What is on sale?', '["Winter coats with 30-50% discounts", "Summer dresses", "Leather shoes", "Watches"]', 0, 'Ao khoac dong giam 30-50%. EN: Winter coats at 30-50% off are advertised.', 'comprehension', 'sales', 820, 'Fashion House - Winter Sale\nAll winter coats 30-50% off, this weekend only. Extra 10% off for members. Fitting rooms close 30 minutes before closing time. No returns on sale items.'),
(869, 7, 'reading', 'What extra benefit do members get?', '["An extra 10% off", "Free alterations", "A gift card", "Free shipping"]', 0, 'Thanh vien giam them 10%. EN: "Extra 10% off for members" is explicit.', 'comprehension', 'sales', 820, 'Fashion House - Winter Sale\nAll winter coats 30-50% off, this weekend only. Extra 10% off for members. Fitting rooms close 30 minutes before closing time. No returns on sale items.'),
(870, 7, 'reading', 'What is the policy on sale items?', '["No returns accepted", "Free exchanges", "Full refunds", "Store credit only"]', 0, 'Hang sale khong doi tra. EN: "No returns on sale items" is explicit.', 'comprehension', 'sales', 820, 'Fashion House - Winter Sale\nAll winter coats 30-50% off, this weekend only. Extra 10% off for members. Fitting rooms close 30 minutes before closing time. No returns on sale items.'),
-- P7 single 21: IT outage mail (ids 871-874, passage 821)
(871, 7, 'reading', 'What happened on Tuesday?', '["The email system was down for two hours", "The office lost power all day", "All data was deleted", "The website was hacked"]', 0, 'He thong email loi 2 tieng sang thu 3. EN: A two-hour Tuesday email outage is reported.', 'comprehension', 'it', 821, 'IT Notice\nOn Tuesday the email system was down from 9 to 11 a.m. during a server upgrade. No messages were lost; delayed emails arrived by noon. Please restart your email app to refresh the inbox. Sorry for the trouble.'),
(872, 7, 'reading', 'Were any emails lost?', '["No, all delayed emails arrived", "Yes, many were lost", "Unknown, still checking", "Only spam was lost"]', 0, 'Khong mat thu nao; thu tre den truoc buoi trua. EN: "No messages were lost" is explicit.', 'comprehension', 'it', 821, 'IT Notice\nOn Tuesday the email system was down from 9 to 11 a.m. during a server upgrade. No messages were lost; delayed emails arrived by noon. Please restart your email app to refresh the inbox. Sorry for the trouble.'),
(873, 7, 'reading', 'What are users asked to do?', '["Restart the email app", "Change passwords", "Delete old emails", "Buy new software"]', 0, 'Khoi dong lai ung dung email. EN: "Please restart your email app" is explicit.', 'comprehension', 'it', 821, 'IT Notice\nOn Tuesday the email system was down from 9 to 11 a.m. during a server upgrade. No messages were lost; delayed emails arrived by noon. Please restart your email app to refresh the inbox. Sorry for the trouble.'),
(874, 7, 'reading', 'The word "refresh" in the notice is closest in meaning to ___.', '["update", "delete", "close", "sell"]', 0, '"Refresh the inbox" = cap nhat hop thu. EN: "Refresh" here means to update.', 'vocabulary', 'it', 821, 'IT Notice\nOn Tuesday the email system was down from 9 to 11 a.m. during a server upgrade. No messages were lost; delayed emails arrived by noon. Please restart your email app to refresh the inbox. Sorry for the trouble.'),
-- P7 double 2: invoice + reminder (ids 875-879, passage 822)
(875, 7, 'reading', 'What is the invoice amount?', '["$1,250 due May 30", "$2,150 due June 30", "$1,520 due May 3", "$1,205 due April 30"]', 0, 'Hoa don $1,250 han 30 thang 5. EN: Invoice #3091 totals $1,250, due May 30.', 'comprehension', 'finance', 822, 'Invoice #3091 - PrintPro Services\nPrinting 5,000 brochures: $1,250. Payment due May 30. Late payments add 2% per month.\n\nReminder - June 5\nWe have not received payment for Invoice #3091. Please pay $1,250 plus a $25 late fee (2% of $1,250) this week to avoid service suspension.'),
(876, 7, 'reading', 'What extra charge appears in the reminder?', '["A $25 late fee", "A $50 delivery fee", "A $15 tax", "A $200 deposit"]', 0, 'Phi tre han $25. EN: A $25 late fee is added in the reminder.', 'comprehension', 'finance', 822, 'Invoice #3091 - PrintPro Services\nPrinting 5,000 brochures: $1,250. Payment due May 30. Late payments add 2% per month.\n\nReminder - June 5\nWe have not received payment for Invoice #3091. Please pay $1,250 plus a $25 late fee (2% of $1,250) this week to avoid service suspension.'),
(877, 7, 'reading', 'How is the $25 calculated?', '["As 2% of $1,250", "As a flat service fee", "As 5% of the total", "As postage cost"]', 0, '2% cua $1,250 = $25. EN: "(2% of $1,250)" is stated.', 'comprehension', 'finance', 822, 'Invoice #3091 - PrintPro Services\nPrinting 5,000 brochures: $1,250. Payment due May 30. Late payments add 2% per month.\n\nReminder - June 5\nWe have not received payment for Invoice #3091. Please pay $1,250 plus a $25 late fee (2% of $1,250) this week to avoid service suspension.'),
(878, 7, 'reading', 'What may happen if payment is not made this week?', '["Service suspension", "A court trial", "Account closure forever", "Higher brochure prices"]', 0, 'Co the bi ngung dich vu. EN: "To avoid service suspension" implies suspension.', 'comprehension', 'finance', 822, 'Invoice #3091 - PrintPro Services\nPrinting 5,000 brochures: $1,250. Payment due May 30. Late payments add 2% per month.\n\nReminder - June 5\nWe have not received payment for Invoice #3091. Please pay $1,250 plus a $25 late fee (2% of $1,250) this week to avoid service suspension.'),
(879, 7, 'reading', 'What service did PrintPro provide?', '["Printing 5,000 brochures", "Designing a website", "Delivering packages", "Repairing printers"]', 0, 'In 5.000 to roi. EN: "Printing 5,000 brochures" is on the invoice.', 'comprehension', 'finance', 822, 'Invoice #3091 - PrintPro Services\nPrinting 5,000 brochures: $1,250. Payment due May 30. Late payments add 2% per month.\n\nReminder - June 5\nWe have not received payment for Invoice #3091. Please pay $1,250 plus a $25 late fee (2% of $1,250) this week to avoid service suspension.'),
-- P7 double 3: ad + inquiry email (ids 880-884, passage 823)
(880, 7, 'reading', 'What does the advertisement offer?', '["A free trial week of office cleaning", "A free office relocation", "Discounted office furniture", "Free security cameras"]', 0, 'Quang cao tuan dung thu mien phi dich vu ve sinh. EN: A free trial week of cleaning is advertised.', 'comprehension', 'office', 823, 'Ad: SparkleClean Office Services\nOne free trial week of office cleaning for new business clients. Nightly service, eco-friendly products. Call 555-9020.\n\nEmail - From: Mr. Quang\nWe saw your ad and want the free trial week starting June 9 for our 3-floor office. Do your teams work after 8 p.m.? Please confirm availability.'),
(881, 7, 'reading', 'What does Mr. Quang request?', '["The trial week starting June 9", "A price quotation", "A daytime service", "A long-term contract"]', 0, 'Ong Quang muon tuan thu tu 9 thang 6. EN: The trial week starting June 9 is requested.', 'comprehension', 'office', 823, 'Ad: SparkleClean Office Services\nOne free trial week of office cleaning for new business clients. Nightly service, eco-friendly products. Call 555-9020.\n\nEmail - From: Mr. Quang\nWe saw your ad and want the free trial week starting June 9 for our 3-floor office. Do your teams work after 8 p.m.? Please confirm availability.'),
(882, 7, 'reading', 'What does Mr. Quang ask about the schedule?', '["Whether teams work after 8 p.m.", "Whether weekends cost extra", "How long each visit takes", "How many staff will come"]', 0, 'Hoi doi co lam sau 8 gio toi khong. EN: "Do your teams work after 8 p.m.?" is asked.', 'comprehension', 'office', 823, 'Ad: SparkleClean Office Services\nOne free trial week of office cleaning for new business clients. Nightly service, eco-friendly products. Call 555-9020.\n\nEmail - From: Mr. Quang\nWe saw your ad and want the free trial week starting June 9 for our 3-floor office. Do your teams work after 8 p.m.? Please confirm availability.'),
(883, 7, 'reading', 'How big is Mr. Quang''s office?', '["Three floors", "One floor", "Five rooms", "Two buildings"]', 0, 'Van phong 3 tang. EN: "Our 3-floor office" is stated.', 'comprehension', 'office', 823, 'Ad: SparkleClean Office Services\nOne free trial week of office cleaning for new business clients. Nightly service, eco-friendly products. Call 555-9020.\n\nEmail - From: Mr. Quang\nWe saw your ad and want the free trial week starting June 9 for our 3-floor office. Do your teams work after 8 p.m.? Please confirm availability.'),
(884, 7, 'reading', 'What products does the company use?', '["Eco-friendly products", "Imported chemicals", "Recycled paper only", "No products at all"]', 0, 'Dung san pham than thien moi truong. EN: "Eco-friendly products" is in the ad.', 'comprehension', 'office', 823, 'Ad: SparkleClean Office Services\nOne free trial week of office cleaning for new business clients. Nightly service, eco-friendly products. Call 555-9020.\n\nEmail - From: Mr. Quang\nWe saw your ad and want the free trial week starting June 9 for our 3-floor office. Do your teams work after 8 p.m.? Please confirm availability.'),
-- P7 double 4: job posting + application email (ids 885-889, passage 824)
(885, 7, 'reading', 'What job is advertised?', '["A weekend receptionist", "A night security guard", "A full-time chef", "A tour guide"]', 0, 'Tuyen le tan cuoi tuan. EN: A weekend receptionist is advertised.', 'comprehension', 'hr', 824, 'Job Posting - Weekend Receptionist\nSunny Hotel needs a weekend receptionist (Sat-Sun, 8 a.m.-4 p.m.). Requirements: friendly manner, basic English. Pay: $14/hour. Email resume to jobs@sunnyhotel.example.com.\n\nApplication Email - From: Ms. Nga\nI am applying for the weekend receptionist job. I speak English well and worked two summers at a resort front desk. My resume is attached. May I visit next Monday for a tour?'),
(886, 7, 'reading', 'What are the working hours?', '["Sat-Sun, 8 a.m.-4 p.m.", "Mon-Fri, 9 a.m.-5 p.m.", "Nights, 10 p.m.-6 a.m.", "Flexible hours"]', 0, 'Thu 7-Chu nhat 8h-16h. EN: "Sat-Sun, 8 a.m.-4 p.m." is listed.', 'comprehension', 'hr', 824, 'Job Posting - Weekend Receptionist\nSunny Hotel needs a weekend receptionist (Sat-Sun, 8 a.m.-4 p.m.). Requirements: friendly manner, basic English. Pay: $14/hour. Email resume to jobs@sunnyhotel.example.com.\n\nApplication Email - From: Ms. Nga\nI am applying for the weekend receptionist job. I speak English well and worked two summers at a resort front desk. My resume is attached. May I visit next Monday for a tour?'),
(887, 7, 'reading', 'What experience does Ms. Nga mention?', '["Two summers at a resort front desk", "Five years as a manager", "One year in accounting", "Internship at a bank"]', 0, '2 mua he lam le tan resort. EN: "Two summers at a resort front desk" is stated.', 'comprehension', 'hr', 824, 'Job Posting - Weekend Receptionist\nSunny Hotel needs a weekend receptionist (Sat-Sun, 8 a.m.-4 p.m.). Requirements: friendly manner, basic English. Pay: $14/hour. Email resume to jobs@sunnyhotel.example.com.\n\nApplication Email - From: Ms. Nga\nI am applying for the weekend receptionist job. I speak English well and worked two summers at a resort front desk. My resume is attached. May I visit next Monday for a tour?'),
(888, 7, 'reading', 'What does Ms. Nga ask to do?', '["Visit next Monday for a tour", "Start work tomorrow", "Meet the director today", "Call her tonight"]', 0, 'Xin ghe tham quan vao thu 2. EN: "May I visit next Monday for a tour?" is asked.', 'comprehension', 'hr', 824, 'Job Posting - Weekend Receptionist\nSunny Hotel needs a weekend receptionist (Sat-Sun, 8 a.m.-4 p.m.). Requirements: friendly manner, basic English. Pay: $14/hour. Email resume to jobs@sunnyhotel.example.com.\n\nApplication Email - From: Ms. Nga\nI am applying for the weekend receptionist job. I speak English well and worked two summers at a resort front desk. My resume is attached. May I visit next Monday for a tour?'),
(889, 7, 'reading', 'How should candidates send their resume?', '["By email to the hotel address", "By fax", "In person", "By post"]', 0, 'Gui email den dia chi khach san. EN: "Email resume to jobs@sunnyhotel.example.com" is instructed.', 'comprehension', 'hr', 824, 'Job Posting - Weekend Receptionist\nSunny Hotel needs a weekend receptionist (Sat-Sun, 8 a.m.-4 p.m.). Requirements: friendly manner, basic English. Pay: $14/hour. Email resume to jobs@sunnyhotel.example.com.\n\nApplication Email - From: Ms. Nga\nI am applying for the weekend receptionist job. I speak English well and worked two summers at a resort front desk. My resume is attached. May I visit next Monday for a tour?'),
-- P7 double 5: seminar notice + registration form (ids 890-894, passage 825)
(890, 7, 'reading', 'What is the seminar topic?', '["Negotiation skills for buyers", "Public speaking basics", "Accounting software", "First aid training"]', 0, 'Hoi thao ky nang dam phan cho nguoi mua hang. EN: Negotiation skills for buyers is the topic.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(891, 7, 'reading', 'When must registration be completed?', '["By July 15", "By July 22", "By August 1", "By June 30"]', 0, 'Dang ky truoc 15 thang 7. EN: "Register by July 15" is stated.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(892, 7, 'reading', 'What special request does Ms. Linh make?', '["A vegetarian lunch", "A front-row seat", "A printed certificate", "A parking voucher"]', 0, 'Yeu cau bua trua chay. EN: "Vegetarian lunch, please" is requested.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(893, 7, 'reading', 'How much did Ms. Linh pay?', '["$80", "$60", "$100", "$50"]', 0, 'Da nop $80. EN: "Payment: $80 enclosed" is stated.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(894, 7, 'reading', 'Where will the workshop be held?', '["Room 501", "Room 105", "The main hall", "Online"]', 0, 'Phong 501. EN: "Room 501" is listed.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(895, 7, 'reading', 'What time does the workshop run?', '["1-5 p.m.", "9 a.m.-12 p.m.", "6-9 p.m.", "10 a.m.-2 p.m."]', 0, 'Tu 1 gio den 5 gio chieu. EN: "1-5 p.m." is listed.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(896, 7, 'reading', 'Which company does Ms. Linh work for?', '["ABC Trading", "XYZ Foods", "Sunny Hotel", "PrintPro"]', 0, 'Ba Linh lam o ABC Trading. EN: "Ms. Linh, ABC Trading" is on the form.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(897, 7, 'reading', 'What is the workshop fee?', '["$80", "$60", "$100", "$120"]', 0, 'Phi $80. EN: "Fee $80" is stated.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(898, 7, 'reading', 'What can be inferred about Ms. Linh?', '["She will attend the July 22 workshop", "She organizes the workshop", "She canceled her registration", "She asked for a refund"]', 0, 'Da nop phi + dien form -> se tham du. EN: Payment plus a completed form implies attendance.', 'comprehension', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.'),
(899, 7, 'reading', 'The word "enclosed" in the form is closest in meaning to ___.', '["included", "lost", "copied", "folded"]', 0, '"Payment enclosed" = tien kem theo trong bi thu. EN: "Enclosed" means included with the form.', 'vocabulary', 'sales', 825, 'Notice: Buyers'' Negotiation Workshop, July 22, 1-5 p.m., Room 501. Fee $80. Register by July 15.\n\nRegistration Form - Ms. Linh, ABC Trading. Payment: $80 enclosed. Special request: vegetarian lunch, please.')
ON CONFLICT (id) DO NOTHING;
