-- TOEIC Reading Part 7 batch 5 (ids 900-949): 8 doan don + 2 doan bo sung + 2 doan kep (50 cau).
-- Giai thich song ngu Viet-Anh.

-- P7 single 22: office hours sign (ids 900-902, passage 826)
INSERT INTO toeic_questions (id, part, section, prompt, choices, answer, explanation, grammar_tag, topic, passage_id, passage_text) VALUES
(900, 7, 'reading', 'When is the office closed for lunch?', '["From 12:00 to 1:00 p.m.", "From 11:30 to 12:30", "From 1:00 to 2:00 p.m.", "All morning"]', 0, 'Nghi trua 12h-13h. EN: "Closed 12:00-1:00 p.m. for lunch" is stated.', 'comprehension', 'office', 826, 'PARKVIEW OFFICE - Hours\nOpen Mon-Fri 8:00 a.m.-6:00 p.m. Closed 12:00-1:00 p.m. for lunch. Saturdays by appointment only.'),
(901, 7, 'reading', 'How can visitors come on Saturday?', '["By appointment only", "Without an appointment", "Only with a member", "Only in the morning"]', 0, 'Thu 7 chi tiep theo hen. EN: "Saturdays by appointment only" is explicit.', 'comprehension', 'office', 826, 'PARKVIEW OFFICE - Hours\nOpen Mon-Fri 8:00 a.m.-6:00 p.m. Closed 12:00-1:00 p.m. for lunch. Saturdays by appointment only.'),
(902, 7, 'reading', 'What are the weekday opening hours?', '["8:00 a.m. to 6:00 p.m.", "9:00 a.m. to 5:00 p.m.", "7:00 a.m. to 7:00 p.m.", "8:00 a.m. to 12:00 p.m."]', 0, 'Ngay thuong 8h-18h. EN: "Mon-Fri 8:00 a.m.-6:00 p.m." is listed.', 'comprehension', 'office', 826, 'PARKVIEW OFFICE - Hours\nOpen Mon-Fri 8:00 a.m.-6:00 p.m. Closed 12:00-1:00 p.m. for lunch. Saturdays by appointment only.'),
-- P7 single 23: refund policy (ids 903-905, passage 827)
(903, 7, 'reading', 'How many days do customers have to request a refund?', '["30 days", "14 days", "60 days", "7 days"]', 0, 'Doi tra trong 30 ngay. EN: "Within 30 days of purchase" is stated.', 'comprehension', 'sales', 827, 'RETURN POLICY - ElectroWorld\nFull refunds within 30 days of purchase with receipt. Items must be unopened. Opened items can be exchanged only. Refunds go to the original payment method.'),
(904, 7, 'reading', 'What condition applies to refunds?', '["Items must be unopened", "Items must be used once", "No receipt is needed", "Only cash is refunded"]', 0, 'Hang phai con nguyen seal. EN: "Items must be unopened" is required.', 'comprehension', 'sales', 827, 'RETURN POLICY - ElectroWorld\nFull refunds within 30 days of purchase with receipt. Items must be unopened. Opened items can be exchanged only. Refunds go to the original payment method.'),
(905, 7, 'reading', 'What can be done with opened items?', '["They can be exchanged only", "They get full refunds", "They earn store credit", "Nothing at all"]', 0, 'Hang da mo chi duoc doi (khong hoan tien). EN: "Opened items can be exchanged only" is explicit.', 'comprehension', 'sales', 827, 'RETURN POLICY - ElectroWorld\nFull refunds within 30 days of purchase with receipt. Items must be unopened. Opened items can be exchanged only. Refunds go to the original payment method.'),
-- P7 single 24: workshop invitation (ids 906-908, passage 828)
(906, 7, 'reading', 'Who is the workshop intended for?', '["New team leaders", "Retired staff", "High-school students", "Foreign tourists"]', 0, 'Danh cho truong nhom moi. EN: "New team leaders" are the audience.', 'comprehension', 'hr', 828, 'Leadership Workshop Invitation\nNew team leaders are invited to a free half-day workshop on giving feedback, Friday, Aug 8, 1-5 p.m., Room 201. Trainer: Ms. Oanh. Please confirm by Aug 1.'),
(907, 7, 'reading', 'What will participants learn?', '["How to give feedback", "How to cook meals", "How to drive safely", "How to fix computers"]', 0, 'Hoc cach gop y (feedback). EN: "Giving feedback" is the workshop topic.', 'comprehension', 'hr', 828, 'Leadership Workshop Invitation\nNew team leaders are invited to a free half-day workshop on giving feedback, Friday, Aug 8, 1-5 p.m., Room 201. Trainer: Ms. Oanh. Please confirm by Aug 1.'),
(908, 7, 'reading', 'When must invitees confirm?', '["By August 1", "By August 8", "By July 1", "On Friday"]', 0, 'Xac nhan truoc 1 thang 8. EN: "Please confirm by Aug 1" is explicit.', 'comprehension', 'hr', 828, 'Leadership Workshop Invitation\nNew team leaders are invited to a free half-day workshop on giving feedback, Friday, Aug 8, 1-5 p.m., Room 201. Trainer: Ms. Oanh. Please confirm by Aug 1.'),
-- P7 single 25: bus timetable (ids 909-912, passage 829)
(909, 7, 'reading', 'How often do buses run on weekdays?', '["Every 15 minutes", "Every 30 minutes", "Every hour", "Every 10 minutes"]', 0, 'Ngay thuong 15 phut/chuyen. EN: "Weekdays: every 15 minutes" is listed.', 'comprehension', 'travel', 829, 'Airport Express Bus\nWeekdays: every 15 minutes, 5:30 a.m.-11:00 p.m. Weekends: every 30 minutes. Fare: $8 one-way. Tickets at the counter or by phone.'),
(910, 7, 'reading', 'What is the one-way fare?', '["$8", "$10", "$5", "$15"]', 0, 'Gia ve 1 luot $8. EN: "Fare: $8 one-way" is listed.', 'comprehension', 'travel', 829, 'Airport Express Bus\nWeekdays: every 15 minutes, 5:30 a.m.-11:00 p.m. Weekends: every 30 minutes. Fare: $8 one-way. Tickets at the counter or by phone.'),
(911, 7, 'reading', 'How can passengers buy tickets?', '["At the counter or by phone", "Only online", "From the driver only", "By mail"]', 0, 'Mua tai quay hoac qua dien thoai. EN: "At the counter or by phone" is stated.', 'comprehension', 'travel', 829, 'Airport Express Bus\nWeekdays: every 15 minutes, 5:30 a.m.-11:00 p.m. Weekends: every 30 minutes. Fare: $8 one-way. Tickets at the counter or by phone.'),
(912, 7, 'reading', 'What is true about weekend service?', '["Buses run every 30 minutes", "No buses run at all", "Buses run more often", "Service ends at noon"]', 0, 'Cuoi tuan 30 phut/chuyen (thua ngay thuong). EN: "Weekends: every 30 minutes" is less frequent.', 'comprehension', 'travel', 829, 'Airport Express Bus\nWeekdays: every 15 minutes, 5:30 a.m.-11:00 p.m. Weekends: every 30 minutes. Fare: $8 one-way. Tickets at the counter or by phone.'),
-- P7 single 26: product recall (ids 913-915, passage 830)
(913, 7, 'reading', 'Which product is recalled?', '["The KettlePro electric kettle", "The ToastMaster oven", "The BlendGo mixer", "The FryKing pan"]', 0, 'Thu hoi am sieu toc KettlePro. EN: The KettlePro electric kettle is recalled.', 'comprehension', 'support', 830, 'SAFETY RECALL - KettlePro Electric Kettle\nSome kettles overheat due to a faulty switch. Stop using it and call 1800-3399 for a free replacement. Have your model number (on the bottom) ready. No receipt is required.'),
(914, 7, 'reading', 'What should owners do?', '["Stop using it and call for a replacement", "Keep using it carefully", "Return it to any store", "Throw it away immediately"]', 0, 'Ngung dung + goi doi moi. EN: "Stop using it and call ... for a free replacement" is instructed.', 'comprehension', 'support', 830, 'SAFETY RECALL - KettlePro Electric Kettle\nSome kettles overheat due to a faulty switch. Stop using it and call 1800-3399 for a free replacement. Have your model number (on the bottom) ready. No receipt is required.'),
(915, 7, 'reading', 'What information should owners have ready?', '["The model number on the bottom", "The original receipt", "The store address", "A photo of the box"]', 0, 'Can so model duoi day am. EN: "Have your model number (on the bottom) ready" is stated; no receipt needed.', 'comprehension', 'support', 830, 'SAFETY RECALL - KettlePro Electric Kettle\nSome kettles overheat due to a faulty switch. Stop using it and call 1800-3399 for a free replacement. Have your model number (on the bottom) ready. No receipt is required.'),
-- P7 single 27: chat messages (ids 916-919, passage 831)
(916, 7, 'reading', 'What are the coworkers planning?', '["Friday team lunch at a new place", "A Monday meeting", "A business trip", "A farewell party"]', 0, 'Ru nhau an trua thu 6 (quan moi). EN: Friday team lunch is planned.', 'comprehension', 'office', 831, '[10:02] Linh: Anyone free for lunch Friday? New noodle place near the office!\n[10:05] Khoa: Count me in. What time?\n[10:07] Linh: 12:15 in the lobby. Mai, are you coming?\n[10:09] Mai: Yes! I will bring the new intern too.'),
(917, 7, 'reading', 'What time will they meet?', '["12:15", "12:00", "11:45", "1:00"]', 0, 'Gap luc 12:15 o sanh. EN: "12:15 in the lobby" is stated.', 'comprehension', 'office', 831, '[10:02] Linh: Anyone free for lunch Friday? New noodle place near the office!\n[10:05] Khoa: Count me in. What time?\n[10:07] Linh: 12:15 in the lobby. Mai, are you coming?\n[10:09] Mai: Yes! I will bring the new intern too.'),
(918, 7, 'reading', 'Who else is joining the lunch?', '["The new intern", "The director", "A client", "Nobody else"]', 0, 'Mai dan them thuc tap sinh moi. EN: "I will bring the new intern too" is stated.', 'comprehension', 'office', 831, '[10:02] Linh: Anyone free for lunch Friday? New noodle place near the office!\n[10:05] Khoa: Count me in. What time?\n[10:07] Linh: 12:15 in the lobby. Mai, are you coming?\n[10:09] Mai: Yes! I will bring the new intern too.'),
(919, 7, 'reading', 'Where will they eat?', '["At a new noodle place nearby", "At the office canteen", "At a pizza restaurant", "At home"]', 0, 'Quan mi moi gan van phong. EN: "New noodle place near the office" is suggested.', 'comprehension', 'office', 831, '[10:02] Linh: Anyone free for lunch Friday? New noodle place near the office!\n[10:05] Khoa: Count me in. What time?\n[10:07] Linh: 12:15 in the lobby. Mai, are you coming?\n[10:09] Mai: Yes! I will bring the new intern too.'),
-- P7 single 28: library fine notice (ids 920-922, passage 832)
(920, 7, 'reading', 'How much is the fine per day?', '["$0.50 per book per day", "$1 per book per day", "$5 per week", "$0.20 per hour"]', 0, 'Phat $0.5/sach/ngay. EN: "$0.50 per book per day" is listed.', 'comprehension', 'general', 832, 'Library Notice - Overdue Fines\nFrom October 1, overdue fines rise to $0.50 per book per day. Return books to the front desk, not the drop box, to stop the fine immediately. Students with unpaid fines cannot borrow new books.'),
(921, 7, 'reading', 'How can borrowers stop the fine immediately?', '["By returning books to the front desk", "By paying online first", "By calling the library", "By emailing staff"]', 0, 'Tra sach tai quay le tan (khong bo hop). EN: "Return books to the front desk ... to stop the fine immediately" is instructed.', 'comprehension', 'general', 832, 'Library Notice - Overdue Fines\nFrom October 1, overdue fines rise to $0.50 per book per day. Return books to the front desk, not the drop box, to stop the fine immediately. Students with unpaid fines cannot borrow new books.'),
(922, 7, 'reading', 'What happens to students with unpaid fines?', '["They cannot borrow new books", "They lose library cards forever", "They must pay double", "They are fined $50"]', 0, 'Khong duoc muon sach moi. EN: "Cannot borrow new books" is stated.', 'comprehension', 'general', 832, 'Library Notice - Overdue Fines\nFrom October 1, overdue fines rise to $0.50 per book per day. Return books to the front desk, not the drop box, to stop the fine immediately. Students with unpaid fines cannot borrow new books.'),
-- P7 single 29: sale email (ids 923-925, passage 833)
(923, 7, 'reading', 'What discount is offered?', '["15% off all office chairs", "25% off all desks", "Buy one get one free", "Free delivery only"]', 0, 'Giam 15% moi ghe van phong. EN: "15% off all office chairs" is offered.', 'comprehension', 'sales', 833, 'Deal of the Week - BrightOffice\nGet 15% off all office chairs, Monday to Wednesday. Use code CHAIR15 at checkout. The best-selling ErgoPlus chair is now only $170 (was $200). Offer ends Wednesday midnight.'),
(924, 7, 'reading', 'How can shoppers get the discount?', '["By using code CHAIR15", "By calling the store", "By paying in cash", "By joining a club"]', 0, 'Nhap ma CHAIR15 khi thanh toan. EN: "Use code CHAIR15 at checkout" is instructed.', 'comprehension', 'sales', 833, 'Deal of the Week - BrightOffice\nGet 15% off all office chairs, Monday to Wednesday. Use code CHAIR15 at checkout. The best-selling ErgoPlus chair is now only $170 (was $200). Offer ends Wednesday midnight.'),
(925, 7, 'reading', 'What is the sale price of the ErgoPlus chair?', '["$170", "$200", "$150", "$185"]', 0, 'Con $170 (gia goc $200). EN: "Now only $170 (was $200)" is listed.', 'comprehension', 'sales', 833, 'Deal of the Week - BrightOffice\nGet 15% off all office chairs, Monday to Wednesday. Use code CHAIR15 at checkout. The best-selling ErgoPlus chair is now only $170 (was $200). Offer ends Wednesday midnight.'),
-- P7 double 6: seminar ad + email question (ids 926-930, passage 834)
(926, 7, 'reading', 'What is the advertised event?', '["A free export seminar on May 20", "A paid import course", "A job fair", "A book launch"]', 0, 'Hoi thao xuat khau mien phi ngay 20 thang 5. EN: A free export seminar on May 20 is advertised.', 'comprehension', 'sales', 834, 'Ad: Export Success Seminar - Free! May 20, 9 a.m.-4 p.m., Trade Center Hall B. Topics: customs forms, shipping terms, finding buyers. Lunch included. Register at trade.example.com.\n\nEmail - From: Ms. Phuong\nI registered for the May 20 export seminar. I am vegetarian - will lunch be meat-free? Also, can I get the slides after the event?'),
(927, 7, 'reading', 'What is included with the seminar?', '["Lunch", "A hotel stay", "Free samples", "A certificate"]', 0, 'Bao gom bua trua. EN: "Lunch included" is in the ad.', 'comprehension', 'sales', 834, 'Ad: Export Success Seminar - Free! May 20, 9 a.m.-4 p.m., Trade Center Hall B. Topics: customs forms, shipping terms, finding buyers. Lunch included. Register at trade.example.com.\n\nEmail - From: Ms. Phuong\nI registered for the May 20 export seminar. I am vegetarian - will lunch be meat-free? Also, can I get the slides after the event?'),
(928, 7, 'reading', 'What does Ms. Phuong ask about lunch?', '["Whether it will be meat-free", "What time it starts", "Where it is served", "How much it costs"]', 0, 'Hoi bua trua co chay khong (an chay). EN: "Will lunch be meat-free?" is asked.', 'comprehension', 'sales', 834, 'Ad: Export Success Seminar - Free! May 20, 9 a.m.-4 p.m., Trade Center Hall B. Topics: customs forms, shipping terms, finding buyers. Lunch included. Register at trade.example.com.\n\nEmail - From: Ms. Phuong\nI registered for the May 20 export seminar. I am vegetarian - will lunch be meat-free? Also, can I get the slides after the event?'),
(929, 7, 'reading', 'What else does Ms. Phuong request?', '["The presentation slides", "A refund", "A different seat", "A certificate"]', 0, 'Xin slide sau su kien. EN: "Can I get the slides after the event?" is requested.', 'comprehension', 'sales', 834, 'Ad: Export Success Seminar - Free! May 20, 9 a.m.-4 p.m., Trade Center Hall B. Topics: customs forms, shipping terms, finding buyers. Lunch included. Register at trade.example.com.\n\nEmail - From: Ms. Phuong\nI registered for the May 20 export seminar. I am vegetarian - will lunch be meat-free? Also, can I get the slides after the event?'),
(930, 7, 'reading', 'Where should people register?', '["At trade.example.com", "By phone", "At the door", "By fax"]', 0, 'Dang ky tai trade.example.com. EN: "Register at trade.example.com" is instructed.', 'comprehension', 'sales', 834, 'Ad: Export Success Seminar - Free! May 20, 9 a.m.-4 p.m., Trade Center Hall B. Topics: customs forms, shipping terms, finding buyers. Lunch included. Register at trade.example.com.\n\nEmail - From: Ms. Phuong\nI registered for the May 20 export seminar. I am vegetarian - will lunch be meat-free? Also, can I get the slides after the event?'),
-- P7 double 7: notice + sign-up sheet (ids 931-935, passage 835)
(931, 7, 'reading', 'What activity is organized?', '["A Saturday beach cleanup", "A Sunday football match", "A charity auction", "A cooking contest"]', 0, 'Don rac bai bien thu 7. EN: A Saturday beach cleanup is organized.', 'comprehension', 'general', 835, 'Notice: Beach Cleanup Day\nJoin our beach cleanup this Saturday, 7-10 a.m. at Cua Lo Beach, Gate 2. Gloves and bags provided. Volunteers get free T-shirts.\n\nSign-up sheet (so far): 18 names. Latest: Mr. Binh (brings a first-aid kit), Ms. Sen (brings extra water).'),
(932, 7, 'reading', 'What do volunteers receive?', '["Free T-shirts", "Cash payment", "Free lunch", "Bus tickets"]', 0, 'Tinh nguyen vien duoc ao thun. EN: "Volunteers get free T-shirts" is stated.', 'comprehension', 'general', 835, 'Notice: Beach Cleanup Day\nJoin our beach cleanup this Saturday, 7-10 a.m. at Cua Lo Beach, Gate 2. Gloves and bags provided. Volunteers get free T-shirts.\n\nSign-up sheet (so far): 18 names. Latest: Mr. Binh (brings a first-aid kit), Ms. Sen (brings extra water).'),
(933, 7, 'reading', 'How many people have signed up so far?', '["18", "8", "28", "80"]', 0, 'Da co 18 nguoi dang ky. EN: "18 names" are on the sheet so far.', 'comprehension', 'general', 835, 'Notice: Beach Cleanup Day\nJoin our beach cleanup this Saturday, 7-10 a.m. at Cua Lo Beach, Gate 2. Gloves and bags provided. Volunteers get free T-shirts.\n\nSign-up sheet (so far): 18 names. Latest: Mr. Binh (brings a first-aid kit), Ms. Sen (brings extra water).'),
(934, 7, 'reading', 'What will Mr. Binh bring?', '["A first-aid kit", "Extra water", "Trash bags", "Lunch boxes"]', 0, 'Ong Binh mang hop so cuu. EN: "Mr. Binh (brings a first-aid kit)" is listed.', 'comprehension', 'general', 835, 'Notice: Beach Cleanup Day\nJoin our beach cleanup this Saturday, 7-10 a.m. at Cua Lo Beach, Gate 2. Gloves and bags provided. Volunteers get free T-shirts.\n\nSign-up sheet (so far): 18 names. Latest: Mr. Binh (brings a first-aid kit), Ms. Sen (brings extra water).'),
(935, 7, 'reading', 'What will Ms. Sen bring?', '["Extra water", "A first-aid kit", "Gloves", "T-shirts"]', 0, 'Ba Sen mang them nuoc. EN: "Ms. Sen (brings extra water)" is listed.', 'comprehension', 'general', 835, 'Notice: Beach Cleanup Day\nJoin our beach cleanup this Saturday, 7-10 a.m. at Cua Lo Beach, Gate 2. Gloves and bags provided. Volunteers get free T-shirts.\n\nSign-up sheet (so far): 18 names. Latest: Mr. Binh (brings a first-aid kit), Ms. Sen (brings extra water).'),
-- P7 double 8: flight schedule + notice (ids 936-940, passage 836)
(936, 7, 'reading', 'Which flight goes to Da Nang?', '["VN146 at 7:30 a.m.", "VN142 at 6:00 a.m.", "VN148 at 9:15 a.m.", "VN150 at 11:00 a.m."]', 0, 'VN146 bay Da Nang luc 7:30. EN: VN146 to Da Nang departs 7:30 a.m.', 'comprehension', 'travel', 836, 'Morning Departures - Hanoi Airport\nVN142 Hue 6:00 a.m. Gate 3. VN146 Da Nang 7:30 a.m. Gate 5. VN148 Nha Trang 9:15 a.m. Gate 2.\n\nNotice: VN148 is delayed 40 minutes due to fog. Passengers may wait in the lounge; coffee is free.'),
(937, 7, 'reading', 'Which flight is delayed?', '["VN148 to Nha Trang", "VN142 to Hue", "VN146 to Da Nang", "VN150 to Da Lat"]', 0, 'VN148 tre 40 phut do suong mu. EN: "VN148 is delayed 40 minutes due to fog" is stated.', 'comprehension', 'travel', 836, 'Morning Departures - Hanoi Airport\nVN142 Hue 6:00 a.m. Gate 3. VN146 Da Nang 7:30 a.m. Gate 5. VN148 Nha Trang 9:15 a.m. Gate 2.\n\nNotice: VN148 is delayed 40 minutes due to fog. Passengers may wait in the lounge; coffee is free.'),
(938, 7, 'reading', 'What is offered to waiting passengers?', '["Free coffee in the lounge", "Free meals", "Hotel rooms", "Shopping vouchers"]', 0, 'Ca phe mien phi o phong cho. EN: "Coffee is free" in the lounge is offered.', 'comprehension', 'travel', 836, 'Morning Departures - Hanoi Airport\nVN142 Hue 6:00 a.m. Gate 3. VN146 Da Nang 7:30 a.m. Gate 5. VN148 Nha Trang 9:15 a.m. Gate 2.\n\nNotice: VN148 is delayed 40 minutes due to fog. Passengers may wait in the lounge; coffee is free.'),
(939, 7, 'reading', 'What gate is the Da Nang flight at?', '["Gate 5", "Gate 3", "Gate 2", "Gate 7"]', 0, 'Cong so 5. EN: "Gate 5" is listed for VN146.', 'comprehension', 'travel', 836, 'Morning Departures - Hanoi Airport\nVN142 Hue 6:00 a.m. Gate 3. VN146 Da Nang 7:30 a.m. Gate 5. VN148 Nha Trang 9:15 a.m. Gate 2.\n\nNotice: VN148 is delayed 40 minutes due to fog. Passengers may wait in the lounge; coffee is free.'),
(940, 7, 'reading', 'Why is VN148 delayed?', '["Because of fog", "Because of rain", "Because of wind", "Because of snow"]', 0, 'Do suong mu. EN: "Due to fog" is the stated cause.', 'comprehension', 'travel', 836, 'Morning Departures - Hanoi Airport\nVN142 Hue 6:00 a.m. Gate 3. VN146 Da Nang 7:30 a.m. Gate 5. VN148 Nha Trang 9:15 a.m. Gate 2.\n\nNotice: VN148 is delayed 40 minutes due to fog. Passengers may wait in the lounge; coffee is free.'),
-- P7 double 9: memo + reply slip (ids 941-945, passage 837)
(941, 7, 'reading', 'What must employees complete?', '["A fire safety course", "A driving test", "An English exam", "A medical check"]', 0, 'Hoan thanh khoa phong chay. EN: A fire safety course must be completed.', 'comprehension', 'office', 837, 'Memo: Fire Safety Training\nAll staff must complete the online fire safety course by Friday. It takes 45 minutes. Print the certificate after finishing.\n\nReply slip - Mr. Teo: I finished the course in 30 minutes on Tuesday. Certificate attached.'),
(942, 7, 'reading', 'How long does the course take?', '["45 minutes", "30 minutes", "60 minutes", "90 minutes"]', 0, 'Khoa hoc 45 phut (Teo lam 30 phut la truong hop rieng). EN: The course takes 45 minutes; 30 was Mr. Teo''s own pace.', 'comprehension', 'office', 837, 'Memo: Fire Safety Training\nAll staff must complete the online fire safety course by Friday. It takes 45 minutes. Print the certificate after finishing.\n\nReply slip - Mr. Teo: I finished the course in 30 minutes on Tuesday. Certificate attached.'),
(943, 7, 'reading', 'What did Mr. Teo attach?', '["His course certificate", "His ID photo", "A doctor note", "A receipt"]', 0, 'Dinh kem chung chi. EN: "Certificate attached" is stated.', 'comprehension', 'office', 837, 'Memo: Fire Safety Training\nAll staff must complete the online fire safety course by Friday. It takes 45 minutes. Print the certificate after finishing.\n\nReply slip - Mr. Teo: I finished the course in 30 minutes on Tuesday. Certificate attached.'),
(944, 7, 'reading', 'When did Mr. Teo finish the course?', '["On Tuesday", "On Friday", "On Monday", "On Thursday"]', 0, 'Xong vao thu 3. EN: "Finished ... on Tuesday" is stated.', 'comprehension', 'office', 837, 'Memo: Fire Safety Training\nAll staff must complete the online fire safety course by Friday. It takes 45 minutes. Print the certificate after finishing.\n\nReply slip - Mr. Teo: I finished the course in 30 minutes on Tuesday. Certificate attached.'),
(945, 7, 'reading', 'What must employees do after finishing?', '["Print the certificate", "Email the manager", "Take a photo", "Call security"]', 0, 'In chung chi sau khi xong. EN: "Print the certificate after finishing" is instructed.', 'comprehension', 'office', 837, 'Memo: Fire Safety Training\nAll staff must complete the online fire safety course by Friday. It takes 45 minutes. Print the certificate after finishing.\n\nReply slip - Mr. Teo: I finished the course in 30 minutes on Tuesday. Certificate attached.'),
-- P7 extra singles for count (ids 946-949, passage 838-839)
(946, 7, 'reading', 'What service is announced?', '["Weekend home cleaning service", "Weekday office repair", "Night security patrol", "Daily laundry pickup"]', 0, 'Dich vu don nha cuoi tuan. EN: Weekend home cleaning is announced.', 'comprehension', 'general', 838, 'CleanHome Services\nWeekend home cleaning now available: Saturdays and Sundays, 8 a.m.-6 p.m. Basic package $45, deep clean $80. Book by phone or online. First-time customers save 10%.'),
(947, 7, 'reading', 'How much does deep cleaning cost?', '["$80", "$45", "$60", "$100"]', 0, 'Don sau $80 (co ban $45). EN: "Deep clean $80" is listed.', 'comprehension', 'general', 838, 'CleanHome Services\nWeekend home cleaning now available: Saturdays and Sundays, 8 a.m.-6 p.m. Basic package $45, deep clean $80. Book by phone or online. First-time customers save 10%.'),
(948, 7, 'reading', 'What discount is offered?', '["10% off for first-time customers", "20% off on Sundays", "Free deep clean", "50% off for members"]', 0, 'Khach moi giam 10%. EN: "First-time customers save 10%" is stated.', 'comprehension', 'general', 838, 'CleanHome Services\nWeekend home cleaning now available: Saturdays and Sundays, 8 a.m.-6 p.m. Basic package $45, deep clean $80. Book by phone or online. First-time customers save 10%.'),
(949, 7, 'reading', 'How can customers book?', '["By phone or online", "Only in person", "By fax", "By letter"]', 0, 'Dat qua dien thoai hoac online. EN: "Book by phone or online" is stated.', 'comprehension', 'general', 838, 'CleanHome Services\nWeekend home cleaning now available: Saturdays and Sundays, 8 a.m.-6 p.m. Basic package $45, deep clean $80. Book by phone or online. First-time customers save 10%.')
ON CONFLICT (id) DO NOTHING;
