-- TOEIC vocabulary decks batch 5 (100 tu van phong + hop hanh): tu dong chia bo 20.
-- Cot: en (UNIQUE) | vi | ipa | example | topic=toeic.

INSERT INTO words (en, vi, ipa, example, topic) VALUES
('stationery', 'văn phòng phẩm', '/ˈsteɪʃənəri/', 'Order more office stationery.', 'toeic'),
('stapler', 'máy dập ghim', '/ˈsteɪplər/', 'The stapler is out of pins.', 'toeic'),
('binder', 'bìa kẹp hồ sơ', '/ˈbaɪndər/', 'File it in the blue binder.', 'toeic'),
('clipboard', 'bảng kẹp giấy', '/ˈklɪpbɔːrd/', 'Sign on the clipboard.', 'toeic'),
('headset', 'tai nghe', '/ˈhedset/', 'Wear your headset daily.', 'toeic'),
('cubicle', 'ô làm việc', '/ˈkjuːbɪkəl/', 'My cubicle faces the window.', 'toeic'),
('reception', 'quầy lễ tân', '/rɪˈsepʃən/', 'Wait at reception please.', 'toeic'),
('memorandum', 'bản ghi nhớ', '/ˌmeməˈrændəm/', 'Read the new memorandum.', 'toeic'),
('circular', 'thông báo chung', '/ˈsɜːrkjələr/', 'A circular about holidays.', 'toeic'),
('bulletin', 'bảng tin', '/ˈbʊlətɪn/', 'Check the staff bulletin.', 'toeic'),
('announcement', 'thông báo', '/əˈnaʊnsmənt/', 'An important announcement today.', 'toeic'),
('projector', 'máy chiếu', '/prəˈdʒektər/', 'Connect the projector now.', 'toeic'),
('whiteboard', 'bảng trắng', '/ˈwaɪtbɔːrd/', 'Write it on the whiteboard.', 'toeic'),
('flipchart', 'bảng lật', '/ˈflɪptʃɑːrt/', 'Notes on the flipchart.', 'toeic'),
('podium', 'bục phát biểu', '/ˈpoʊdiəm/', 'Speak from the podium.', 'toeic'),
('microphone', 'mic', '/ˈmaɪkrəfoʊn/', 'Test the microphone first.', 'toeic'),
('intercom', 'loa nội bộ', '/ˈɪntərkɑːm/', 'Call via the intercom.', 'toeic'),
('handout', 'tài liệu phát tay', '/ˈhændaʊt/', 'Take a printed handout.', 'toeic'),
('minutes', 'biên bản họp', '/ˈmɪnəts/', 'Send the meeting minutes.', 'toeic'),
('action item', 'việc cần làm', '/ˈækʃən ˈaɪtəm/', 'Two action items remain.', 'toeic'),
('follow-up', 'buổi tiếp nối', '/ˈfɑːloʊ ʌp/', 'A follow-up email tomorrow.', 'toeic'),
('recap', 'tóm tắt', '/ˈriːkæp/', 'A quick recap please.', 'toeic'),
('brief', 'giao việc ngắn', '/briːf/', 'Brief the team now.', 'toeic'),
('debrief', 'họp rút kinh nghiệm', '/diːˈbriːf/', 'Debrief after the visit.', 'toeic'),
('keynote', 'diễn văn chính', '/ˈkiːnoʊt/', 'The keynote starts at nine.', 'toeic'),
('breakout', 'phiên thảo luận nhóm', '/ˈbreɪkaʊt/', 'Join a breakout session.', 'toeic'),
('webinar', 'hội thảo trực tuyến', '/ˈwebɪnɑːr/', 'A free marketing webinar.', 'toeic'),
('panel', 'ban tọa đàm', '/ˈpænl/', 'Ask the expert panel.', 'toeic'),
('roundtable', 'bàn tròn', '/ˈraʊndteɪbəl/', 'A roundtable on exports.', 'toeic'),
('symposium', 'hội thảo chuyên đề', '/sɪmˈpoʊziəm/', 'Attend the trade symposium.', 'toeic'),
('summit', 'hội nghị thượng đỉnh', '/ˈsʌmət/', 'A regional sales summit.', 'toeic'),
('convention', 'đại hội', '/kənˈvenʃən/', 'The annual auto convention.', 'toeic'),
('expo', 'hội chợ triển lãm', '/ˈekspoʊ/', 'Visit our expo booth.', 'toeic'),
('booth', 'gian hàng', '/buːð/', 'Staff the welcome booth.', 'toeic'),
('stall', 'quầy hàng', '/stɔːl/', 'A food stall outside.', 'toeic'),
('pavilion', 'gian triển lãm', '/pəˈvɪljən/', 'The tech pavilion opens.', 'toeic'),
('banner', 'biểu ngữ', '/ˈbænər/', 'Hang the event banner.', 'toeic'),
('backdrop', 'phông nền', '/ˈbækdrɑːp/', 'Photos before the backdrop.', 'toeic'),
('badge', 'thẻ đeo', '/bædʒ/', 'Wear your name badge.', 'toeic'),
('lanyard', 'dây đeo thẻ', '/ˈlænjərd/', 'A free event lanyard.', 'toeic'),
('program', 'chương trình', '/ˈproʊɡræm/', 'Check the event program.', 'toeic'),
('slot', 'khung giờ', '/slɑːt/', 'Book a morning slot.', 'toeic'),
('session', 'phiên họp', '/ˈseʃən/', 'The afternoon session runs long.', 'toeic'),
('intermission', 'giờ giải lao', '/ˌɪntərˈmɪʃən/', 'After a short intermission.', 'toeic'),
('icebreaker', 'trò khởi động', '/ˈaɪsbreɪkər/', 'Start with an icebreaker.', 'toeic'),
('emcee', 'MC', '/ˌemˈsiː/', 'Our emcee welcomes guests.', 'toeic'),
('moderator', 'điều phối viên', '/ˈmɑːdəreɪtər/', 'The panel moderator smiled.', 'toeic'),
('delegate', 'đại biểu', '/ˈdelɪɡət/', 'Greet every delegate warmly.', 'toeic'),
('presenter', 'người thuyết trình', '/prɪˈzentər/', 'Each presenter gets ten minutes.', 'toeic'),
('exhibitor', 'đơn vị triển lãm', '/ɪɡˈzɪbɪtər/', 'New exhibitors joined daily.', 'toeic'),
('organizer', 'ban tổ chức', '/ˈɔːrɡənaɪzər/', 'Thank the organizers kindly.', 'toeic'),
('coordinator', 'điều phối viên', '/koʊˈɔːrdɪneɪtər/', 'Ask the event coordinator.', 'toeic'),
('planner', 'người lập kế hoạch', '/ˈplænər/', 'A skilled wedding planner.', 'toeic'),
('caterer', 'đơn vị tiệc', '/ˈkeɪtərər/', 'The caterer serves lunch.', 'toeic'),
('florist', 'tiệm hoa', '/ˈflɔːrɪst/', 'Order from the lobby florist.', 'toeic'),
('photographer', 'thợ ảnh', '/fəˈtɑːɡrəfər/', 'Hire the event photographer.', 'toeic'),
('interpreter', 'phiên dịch viên', '/ɪnˈtɜːrprɪtər/', 'Speak via the interpreter.', 'toeic'),
('translator', 'biên dịch viên', '/trænsˈleɪtər/', 'Send it to a translator.', 'toeic'),
('transcript', 'bản ghi', '/ˈtrænskrɪpt/', 'Read the full transcript.', 'toeic'),
('caption', 'phụ đề', '/ˈkæpʃən/', 'Add captions to videos.', 'toeic'),
('subtitle', 'phụ đề phim', '/ˈsʌbtaɪtl/', 'Films with English subtitles.', 'toeic'),
('livestream', 'phát trực tiếp', '/ˈlaɪvstriːm/', 'Watch the livestream online.', 'toeic'),
('replay', 'xem lại', '/ˈriːpleɪ/', 'A replay is available.', 'toeic'),
('pointer', 'que chỉ', '/ˈpɔɪntər/', 'Use the laser pointer.', 'toeic'),
('clicker', 'bút trình chiếu', '/ˈklɪkər/', 'Pass me the clicker.', 'toeic'),
('survey', 'khảo sát', '/ˈsɜːrveɪ/', 'Complete a short survey.', 'toeic'),
('poll', 'thăm dò', '/poʊl/', 'Vote in the lunch poll.', 'toeic'),
('questionnaire', 'bảng hỏi', '/ˌkwestʃəˈner/', 'Fill out the questionnaire.', 'toeic'),
('networking', 'giao lưu', '/ˈnetwɜːrkɪŋ/', 'Join the networking hour.', 'toeic'),
('mixer', 'tiệc giao lưu', '/ˈmɪksər/', 'A Friday office mixer.', 'toeic'),
('gala', 'dạ tiệc', '/ˈɡeɪlə/', 'The charity gala shines.', 'toeic'),
('toast', 'lời chúc mừng', '/toʊst/', 'Raise a toast now.', 'toeic'),
('refreshment', 'đồ ăn nhẹ', '/rɪˈfreʃmənt/', 'Refreshments after the talk.', 'toeic'),
('buffet', 'tiệc đứng', '/bəˈfeɪ/', 'Lunch is a hot buffet.', 'toeic'),
('brunch', 'bữa nửa buổi', '/brʌntʃ/', 'Join our Sunday brunch.', 'toeic'),
('host', 'chủ trì', '/hoʊst/', 'She will host the forum.', 'toeic'),
('chair', 'chủ tọa', '/tʃer/', 'Who will chair today.', 'toeic'),
('preside', 'chủ trì', '/prɪˈzaɪd/', 'Preside over the hearing.', 'toeic'),
('convene', 'triệu tập', '/kənˈviːn/', 'Convene the board soon.', 'toeic'),
('adjourn', 'tạm nghỉ', '/əˈdʒɜːrn/', 'Adjourn until Monday noon.', 'toeic'),
('quorum', 'đủ số', '/ˈkwɔːrəm/', 'We lack a quorum now.', 'toeic'),
('proxy', 'ủy quyền', '/ˈprɑːksi/', 'Vote by proxy today.', 'toeic'),
('draft', 'bản thảo', '/dræft/', 'Review the first draft.', 'toeic'),
('outline', 'dàn ý', '/ˈaʊtlaɪn/', 'Send a brief outline.', 'toeic'),
('blueprint', 'bản vẽ', '/ˈbluːprɪnt/', 'Approve the new blueprint.', 'toeic'),
('prototype', 'mẫu thử', '/ˈproʊtətaɪp/', 'Test the latest prototype.', 'toeic'),
('specimen', 'mẫu vật', '/ˈspesɪmən/', 'Label each specimen jar.', 'toeic'),
('mock-up', 'mô hình thử', '/ˈmɑːk ʌp/', 'Build a quick mock-up.', 'toeic'),
('tender', 'đấu thầu', '/ˈtendər/', 'Submit a tender bid.', 'toeic'),
('bidder', 'nhà thầu', '/ˈbɪdər/', 'Three bidders applied.', 'toeic'),
('auction', 'đấu giá', '/ˈɔːkʃən/', 'Win the online auction.', 'toeic'),
('lot', 'lô hàng', '/lɑːt/', 'Inspect every lot first.', 'toeic'),
('bulk', 'số lượng lớn', '/bʌlk/', 'Buy in bulk cheaply.', 'toeic'),
('stock', 'hàng tồn', '/stɑːk/', 'Check current stock levels.', 'toeic'),
('reorder', 'đặt lại', '/riːˈɔːrdər/', 'Reorder printer paper soon.', 'toeic'),
('purchase', 'mua', '/ˈpɜːrtʃəs/', 'Approve each purchase fast.', 'toeic'),
('procurement', 'mua sắm', '/prəˈkjʊrmənt/', 'Join the procurement team.', 'toeic'),
('vendor', 'nhà cung cấp', '/ˈvendər/', 'Pay every vendor weekly.', 'toeic'),
('supplier', 'nhà cung ứng', '/səˈplaɪər/', 'Meet a new supplier.', 'toeic'),
('affiliate', 'công ty liên kết', '/əˈfɪlieɪt/', 'Our newest affiliate grows.', 'toeic')
ON CONFLICT (en) DO NOTHING;
