-- TOEIC vocabulary decks batch 6 (100 tu tai chinh + nhan su).

INSERT INTO words (en, vi, ipa, example, topic) VALUES
('ledger', 'sổ cái', '/ˈledʒər/', 'Update the sales ledger.', 'toeic'),
('auditor', 'kiểm toán viên', '/ˈɔːdɪtər/', 'The auditor arrives Monday.', 'toeic'),
('fiscal', 'tài khóa', '/ˈfɪskəl/', 'The fiscal year ends.', 'toeic'),
('quarter', 'quý', '/ˈkwɔːrtər/', 'Sales rose this quarter.', 'toeic'),
('dividend', 'cổ tức', '/ˈdɪvɪdənd/', 'Pay the annual dividend.', 'toeic'),
('equity', 'vốn chủ sở hữu', '/ˈekwəti/', 'Build more brand equity.', 'toeic'),
('liability', 'nợ phải trả', '/ˌlaɪəˈbɪləti/', 'List every liability clearly.', 'toeic'),
('asset', 'tài sản', '/ˈæset/', 'Our best asset is staff.', 'toeic'),
('capital', 'vốn', '/ˈkæpɪtl/', 'Raise more startup capital.', 'toeic'),
('venture', 'dự án mạo hiểm', '/ˈventʃər/', 'Fund the new venture.', 'toeic'),
('startup', 'khởi nghiệp', '/ˈstɑːrtʌp/', 'Join a fintech startup.', 'toeic'),
('depreciation', 'khấu hao', '/dɪˌpriːʃiˈeɪʃən/', 'Count annual depreciation.', 'toeic'),
('solvent', 'có khả năng trả nợ', '/ˈsɑːlvənt/', 'Stay solvent this year.', 'toeic'),
('default', 'vỡ nợ', '/dɪˈfɔːlt/', 'Never default on loans.', 'toeic'),
('escrow', 'ký quỹ', '/ˈeskroʊ/', 'Funds sit in escrow.', 'toeic'),
('collateral', 'tài sản thế chấp', '/kəˈlætərəl/', 'Offer land as collateral.', 'toeic'),
('guarantor', 'người bảo lãnh', '/ˌɡærənˈtɔːr/', 'Act as loan guarantor.', 'toeic'),
('premium', 'phí bảo hiểm', '/ˈpriːmiəm/', 'Pay premiums monthly.', 'toeic'),
('deductible', 'mức khấu trừ', '/dɪˈdʌktəbl/', 'A $500 deductible applies.', 'toeic'),
('claim', 'yêu cầu bồi thường', '/kleɪm/', 'File an insurance claim.', 'toeic'),
('policy', 'hợp đồng bảo hiểm', '/ˈpɑːləsi/', 'Read your policy twice.', 'toeic'),
('holder', 'chủ sở hữu', '/ˈhoʊldər/', 'Card holders save more.', 'toeic'),
('portfolio', 'danh mục', '/pɔːrtˈfoʊlioʊ/', 'Diversify your portfolio.', 'toeic'),
('brokerage', 'môi giới', '/ˈbroʊkərɪdʒ/', 'Open a brokerage account.', 'toeic'),
('trader', 'nhà giao dịch', '/ˈtreɪdər/', 'The trader closed early.', 'toeic'),
('hedge', 'phòng ngừa rủi ro', '/hedʒ/', 'Hedge against rate swings.', 'toeic'),
('margin', 'ký quỹ', '/ˈmɑːrdʒɪn/', 'Trade on margin wisely.', 'toeic'),
('leverage', 'đòn bẩy', '/ˈlevərɪdʒ/', 'Use debt leverage carefully.', 'toeic'),
('buyout', 'mua lại', '/ˈbaɪaʊt/', 'Approve the company buyout.', 'toeic'),
('severance', 'trợ cấp thôi việc', '/ˈsevərəns/', 'Offer fair severance pay.', 'toeic'),
('pension', 'lương hưu', '/ˈpenʃən/', 'A solid state pension.', 'toeic'),
('gratuity', 'tiền boa', '/ɡrəˈtuːəti/', 'Gratuity is not included.', 'toeic'),
('increment', 'mức tăng', '/ˈɪnkrəmənt/', 'A yearly pay increment.', 'toeic'),
('bracket', 'khung thuế', '/ˈbrækɪt/', 'A higher tax bracket.', 'toeic'),
('threshold', 'ngưỡng', '/ˈθreʃhoʊld/', 'Cross the sales threshold.', 'toeic'),
('ceiling', 'trần', '/ˈsiːlɪŋ/', 'Hit the price ceiling.', 'toeic'),
('cap', 'mức trần', '/kæp/', 'Cap overtime hours now.', 'toeic'),
('tariff', 'thuế quan', '/ˈtærɪf/', 'New import tariffs loom.', 'toeic'),
('levy', 'thuế đánh', '/ˈlevi/', 'Levy a small port fee.', 'toeic'),
('surcharge', 'phụ phí', '/ˈsɜːrtʃɑːrdʒ/', 'A weekend delivery surcharge.', 'toeic'),
('fee', 'lệ phí', '/fiː/', 'Pay the visa fee.', 'toeic'),
('fine', 'tiền phạt', '/faɪn/', 'Pay the parking fine.', 'toeic'),
('penalty', 'hình phạt', '/ˈpenəlti/', 'Avoid late penalties.', 'toeic'),
('grace period', 'thời gian ân hạn', '/ˈɡreɪs ˈpɪəriəd/', 'A ten-day grace period.', 'toeic'),
('rate', 'lãi suất', '/reɪt/', 'Lock a low rate.', 'toeic'),
('yield', 'lợi suất', '/jiːld/', 'Bonds with high yield.', 'toeic'),
('headhunt', 'săn nhân tài', '/ˈhedhʌnt/', 'Headhunt senior engineers.', 'toeic'),
('onboard', 'hội nhập', '/ˌɑːnˈbɔːrd/', 'Onboard new hires fast.', 'toeic'),
('orientation', 'định hướng', '/ˌɔːriənˈteɪʃən/', 'Attend staff orientation.', 'toeic'),
('probation', 'thử việc', '/proʊˈbeɪʃən/', 'Six months probation applies.', 'toeic'),
('appraisal', 'đánh giá', '/əˈpreɪzəl/', 'Yearly performance appraisal.', 'toeic'),
('mentor', 'cố vấn', '/ˈmentɔːr/', 'Find a senior mentor.', 'toeic'),
('mentee', 'người được cố vấn', '/menˈtiː/', 'Guide each new mentee.', 'toeic'),
('handbook', 'sổ tay', '/ˈhændbʊk/', 'Read the staff handbook.', 'toeic'),
('grievance', 'khiếu nại', '/ˈɡriːvəns/', 'File a formal grievance.', 'toeic'),
('dispute', 'tranh chấp', '/ˈdɪspjuːt/', 'Settle the pay dispute.', 'toeic'),
('mediate', 'hòa giải', '/ˈmiːdieɪt/', 'Mediate the shift dispute.', 'toeic'),
('arbitrate', 'phân xử', '/ˈɑːrbɪtreɪt/', 'Arbitrate contract conflicts.', 'toeic'),
('union', 'công đoàn', '/ˈjuːnjən/', 'Join the labor union.', 'toeic'),
('strike', 'đình công', '/straɪk/', 'Threaten a rail strike.', 'toeic'),
('walkout', 'bãi công', '/ˈwɔːkaʊt/', 'Stage a brief walkout.', 'toeic'),
('picket', 'biểu tình', '/ˈpɪkɪt/', 'Join the picket line.', 'toeic'),
('lockout', 'đóng cửa cấm', '/ˈlɑːkaʊt/', 'End the factory lockout.', 'toeic'),
('compromise', 'thỏa hiệp', '/ˈkɑːmprəmaɪz/', 'Reach a fair compromise.', 'toeic'),
('settle', 'dàn xếp', '/ˈsetl/', 'Settle out of court.', 'toeic'),
('quit', 'nghỉ việc', '/kwɪt/', 'Quit after fair notice.', 'toeic'),
('retire', 'nghỉ hưu', '/rɪˈtaɪər/', 'Retire at sixty-five.', 'toeic'),
('layoff', 'sa thải', '/ˈleɪɔːf/', 'Avoid mass layoffs now.', 'toeic'),
('downsize', 'thu hẹp', '/ˈdaʊnsaɪz/', 'Downsize the night shift.', 'toeic'),
('furlough', 'nghỉ không lương', '/ˈfɜːrloʊ/', 'Short holiday furloughs loom.', 'toeic'),
('dismiss', 'sa thải', '/dɪsˈmɪs/', 'Dismiss for misconduct only.', 'toeic'),
('terminate', 'chấm dứt', '/ˈtɜːrmɪneɪt/', 'Terminate the old contract.', 'toeic'),
('reinstate', 'phục chức', '/ˌriːɪnˈsteɪt/', 'Reinstate the fired clerk.', 'toeic'),
('promote', 'thăng chức', '/prəˈmoʊt/', 'Promote from within first.', 'toeic'),
('demote', 'giáng chức', '/dɪˈmoʊt/', 'Demote after two warnings.', 'toeic'),
('transfer', 'thuyên chuyển', '/trænsˈfɜːr/', 'Transfer to the Hanoi branch.', 'toeic'),
('relocate', 'chuyển địa điểm', '/ˌriːloʊˈkeɪt/', 'Relocate the design team.', 'toeic'),
('expatriate', 'chuyên gia nước ngoài', '/eksˈpeɪtriət/', 'Support each expatriate family.', 'toeic'),
('telecommute', 'làm từ xa', '/ˌtelɪkəˈmjuːt/', 'Telecommute twice weekly.', 'toeic'),
('remote', 'từ xa', '/rɪˈmoʊt/', 'A fully remote role.', 'toeic'),
('hybrid', 'lai', '/ˈhaɪbrɪd/', 'A hybrid work model.', 'toeic'),
('opening', 'vị trí trống', '/ˈoʊpnɪŋ/', 'An exciting job opening.', 'toeic'),
('applicant', 'ứng viên', '/ˈæplɪkənt/', 'Screen each applicant fast.', 'toeic'),
('cover letter', 'thư xin việc', '/ˈkʌvər ˈletər/', 'Attach a cover letter.', 'toeic'),
('reference', 'thư giới thiệu', '/ˈrefrəns/', 'Provide two references.', 'toeic'),
('background check', 'kiểm tra lý lịch', '/ˈbækɡraʊnd tʃek/', 'Pass a background check.', 'toeic'),
('callback', 'gọi lại', '/ˈkɔːlbæk/', 'Expect a callback soon.', 'toeic'),
('offer letter', 'thư mời nhận việc', '/ˈɔːfər ˈletər/', 'Sign the offer letter.', 'toeic'),
('tenure', 'thâm niên', '/ˈtenjər/', 'Reward long tenure well.', 'toeic'),
('seniority', 'thâm niên', '/ˌsiːniˈɔːrəti/', 'Respect shop seniority.', 'toeic'),
('merit', 'thành tích', '/ˈmerɪt/', 'Promote on merit only.', 'toeic'),
('fire', 'sa thải', '/ˈfaɪər/', 'Never fire by text.', 'toeic'),
('hire', 'tuyển', '/ˈhaɪər/', 'Hire two cashiers fast.', 'toeic'),
('coach', 'huấn luyện', '/koʊtʃ/', 'Coach junior sellers weekly.', 'toeic'),
('buddy', 'bạn đồng hành', '/ˈbʌdi/', 'Ask your onboarding buddy.', 'toeic'),
('roster', 'lịch trực', '/ˈrɑːstər/', 'Check the night roster.', 'toeic'),
('timesheet', 'bảng chấm công', '/ˈtaɪmʃiːt/', 'Submit timesheets Friday.', 'toeic'),
('payslip', 'phiếu lương', '/ˈpeɪslɪp/', 'Download your monthly payslip.', 'toeic'),
('flexitime', 'giờ linh hoạt', '/ˈfleksitaɪm/', 'Choose flexitime hours.', 'toeic'),
('second', 'biệt phái', '/səˈkɑːnd/', 'Second her to marketing.', 'toeic')
ON CONFLICT (en) DO NOTHING;
