-- TOEIC vocabulary decks batch 7 (100 tu du lich + khach san + hang khong).

INSERT INTO words (en, vi, ipa, example, topic) VALUES
('room service', 'phục vụ phòng', '/ˈruːm ˈsɜːrvɪs/', 'Order late room service.', 'toeic'),
('turndown', 'dọn phòng tối', '/ˈtɜːrndaʊn/', 'Nightly turndown service charms.', 'toeic'),
('wake-up call', 'gọi báo thức', '/ˈweɪk ʌp kɔːl/', 'Book a 6 a.m. wake-up call.', 'toeic'),
('upgrade', 'nâng hạng', '/ˌʌpˈɡreɪd/', 'Request a free upgrade.', 'toeic'),
('downgrade', 'hạ hạng', '/ˈdaʊnɡreɪd/', 'Never downgrade safety.', 'toeic'),
('overbook', 'bán quá chỗ', '/ˌoʊvərˈbʊk/', 'Airlines often overbook flights.', 'toeic'),
('bump', 'chuyển chuyến', '/bʌmp/', 'Bumped to a later flight.', 'toeic'),
('stand-by', 'chờ chỗ', '/ˈstænd baɪ/', 'Fly stand-by for less.', 'toeic'),
('gate', 'cổng', '/ɡeɪt/', 'Hurry to Gate 12.', 'toeic'),
('terminal', 'nhà ga', '/ˈtɜːrmɪnəl/', 'Meet at Terminal 2.', 'toeic'),
('concourse', 'sảnh', '/ˈkɑːnkɔːrs/', 'Walk the long concourse.', 'toeic'),
('runway', 'đường băng', '/ˈrʌnweɪ/', 'Clear the icy runway.', 'toeic'),
('tarmac', 'sân đỗ', '/ˈtɑːrmæk/', 'Wait on the hot tarmac.', 'toeic'),
('hangar', 'nhà chứa máy bay', '/ˈhæŋər/', 'Park inside the hangar.', 'toeic'),
('cockpit', 'buồng lái', '/ˈkɑːkpɪt/', 'Visitors enter the cockpit.', 'toeic'),
('cabin', 'khoang', '/ˈkæbɪn/', 'A quiet business cabin.', 'toeic'),
('aisle', 'lối đi', '/aɪl/', 'Choose an aisle seat.', 'toeic'),
('overhead bin', 'ngăn hành lý', '/ˈoʊvərhed bɪn/', 'Stow bags in the overhead bin.', 'toeic'),
('tray table', 'bàn ăn', '/ˈtreɪ ˈteɪbəl/', 'Fold your tray table up.', 'toeic'),
('seatbelt', 'dây an toàn', '/ˈsiːtbelt/', 'Fasten every seatbelt now.', 'toeic'),
('life vest', 'áo phao', '/ˈlaɪf vest/', 'Grab a life vest fast.', 'toeic'),
('oxygen mask', 'mặt nạ oxy', '/ˈɑːksɪdʒən mæsk/', 'Pull the oxygen mask down.', 'toeic'),
('turbulence', 'nhiễu động', '/ˈtɜːrbjələns/', 'Expect mild turbulence soon.', 'toeic'),
('divert', 'chuyển hướng', '/daɪˈvɜːrt/', 'Divert around the storm.', 'toeic'),
('reroute', 'đổi lộ trình', '/ˌriːˈruːt/', 'Reroute the delayed cargo.', 'toeic'),
('connection', 'chuyến nối', '/kəˈnekʃən/', 'Missed my noon connection.', 'toeic'),
('nonstop', 'bay thẳng', '/ˌnɑːnˈstɑːp/', 'Book a nonstop flight.', 'toeic'),
('round-trip', 'khứ hồi', '/ˈraʊnd trɪp/', 'A cheap round-trip fare.', 'toeic'),
('one-way', 'một chiều', '/ˈwʌn weɪ/', 'Just a one-way ticket.', 'toeic'),
('voucher', 'phiếu', '/ˈvaʊtʃər/', 'A $50 travel voucher.', 'toeic'),
('immigration', 'nhập cư', '/ˌɪmɪˈɡreɪʃən/', 'Clear immigration quickly.', 'toeic'),
('arrival', 'đến', '/əˈraɪvəl/', 'Check arrivals board now.', 'toeic'),
('departure', 'khởi hành', '/dɪˈpɑːrtʃər/', 'Delays hit departures hourly.', 'toeic'),
('carousel', 'băng chuyền', '/ˌkærəˈsel/', 'Wait by carousel four.', 'toeic'),
('lost and found', 'đồ thất lạc', '/ˈlɔːst ənd ˈfaʊnd/', 'Ask lost and found staff.', 'toeic'),
('taxi stand', 'điểm taxi', '/ˈtæksi stænd/', 'Queue at the taxi stand.', 'toeic'),
('tram', 'tàu điện', '/træm/', 'Ride the old town tram.', 'toeic'),
('voyage', 'chuyến đi biển', '/ˈvɔɪɪdʒ/', 'A calm night voyage.', 'toeic'),
('disembark', 'xuống tàu', '/ˌdɪsɪmˈbɑːrk/', 'Disembark with all luggage.', 'toeic'),
('embark', 'lên tàu', '/ɪmˈbɑːrk/', 'Embark before sunset.', 'toeic'),
('sail', 'ra khơi', '/seɪl/', 'Sail at dawn Friday.', 'toeic'),
('dock', 'cập bến', '/dɑːk/', 'Dock beside pier nine.', 'toeic'),
('harbor', 'bến cảng', '/ˈhɑːrbər/', 'A busy fishing harbor.', 'toeic'),
('port', 'cảng', '/pɔːrt/', 'The ship left port.', 'toeic'),
('marina', 'bến du thuyền', '/məˈriːnə/', 'Moor at the small marina.', 'toeic'),
('excursion', 'chuyến tham quan', '/ɪkˈskɜːrʒən/', 'Book a noon excursion.', 'toeic'),
('tour', 'chuyến tham quan', '/tʊr/', 'Join the free city tour.', 'toeic'),
('guide', 'hướng dẫn viên', '/ɡaɪd/', 'Tip your local guide.', 'toeic'),
('sightseeing', 'ngắm cảnh', '/ˈsaɪtsiːɪŋ/', 'Go sightseeing downtown.', 'toeic'),
('attraction', 'điểm đến', '/əˈtrækʃən/', 'A top-rated attraction.', 'toeic'),
('admittance', 'sự cho vào', '/ədˈmɪtns/', 'Gain free admittance.', 'toeic'),
('ticket', 'vé', '/ˈtɪkɪt/', 'Keep your train ticket.', 'toeic'),
('stub', 'cuống vé', '/stʌb/', 'Save the ticket stub.', 'toeic'),
('queue', 'xếp hàng', '/kjuː/', 'Join the short queue.', 'toeic'),
('peak', 'cao điểm', '/piːk/', 'Avoid peak hours daily.', 'toeic'),
('off-peak', 'thấp điểm', '/ˈɔːf ˈpiːk/', 'Cheaper off-peak fares rule.', 'toeic'),
('season', 'mùa', '/ˈsiːzən/', 'Peak tourist season nears.', 'toeic'),
('penthouse', 'căn áp mái', '/ˈpenthaʊs/', 'Book the glass penthouse.', 'toeic'),
('adjoining', 'liền kề', '/əˈdʒɔɪnɪŋ/', 'Two adjoining rooms please.', 'toeic'),
('amenity', 'tiện nghi', '/əˈmenəti/', 'Free gym amenity daily.', 'toeic'),
('spa', 'spa', '/spɑː/', 'Book a noon spa slot.', 'toeic'),
('sauna', 'xông hơi', '/ˈsɔːnə/', 'Try the cedar sauna.', 'toeic'),
('lounge', 'phòng chờ', '/laʊndʒ/', 'Wait in the gold lounge.', 'toeic'),
('bar', 'quầy bar', '/bɑːr/', 'Meet at the sky bar.', 'toeic'),
('restaurant', 'nhà hàng', '/ˈrestrɑːnt/', 'The rooftop restaurant shines.', 'toeic'),
('café', 'quán cà phê', '/kæˈfeɪ/', 'A quiet corner café.', 'toeic'),
('bistro', 'quán ăn nhỏ', '/ˈbiːstroʊ/', 'Lunch at the green bistro.', 'toeic'),
('all-inclusive', 'trọn gói', '/ˌɔːl ɪnˈkluːsɪv/', 'An all-inclusive resort deal.', 'toeic'),
('half-board', 'nửa suất ăn', '/ˈhæf bɔːrd/', 'Half-board includes breakfast.', 'toeic'),
('bellhop', 'nhân viên hành lý', '/ˈbelhɑːp/', 'Tip the kind bellhop.', 'toeic'),
('porter', 'khuân vác', '/ˈpɔːrtər/', 'Call a station porter.', 'toeic'),
('doorman', 'gác cửa', '/ˈdɔːrmæn/', 'Greet the smiling doorman.', 'toeic'),
('receptionist', 'lễ tân', '/rɪˈsepʃənɪst/', 'Ask any receptionist freely.', 'toeic'),
('housekeeper', 'nhân viên dọn phòng', '/ˈhaʊskiːpər/', 'Thank your floor housekeeper.', 'toeic'),
('late checkout', 'trả phòng muộn', '/ˈleɪt ˈtʃekaʊt/', 'Request free late checkout.', 'toeic'),
('early check-in', 'nhận phòng sớm', '/ˈɜːrli ˈtʃek ɪn/', 'Ask for early check-in.', 'toeic'),
('room key', 'thẻ phòng', '/ˈruːm kiː/', 'Tap your room key.', 'toeic'),
('keycard', 'thẻ từ', '/ˈkiːkɑːrd/', 'Swipe the door keycard.', 'toeic'),
('safe', 'két', '/seɪf/', 'Lock passports in the safe.', 'toeic'),
('blackout', 'mất điện', '/ˈblækaʊt/', 'A brief midnight blackout.', 'toeic'),
('outage', 'cúp', '/ˈaʊtɪdʒ/', 'Report the wifi outage.', 'toeic'),
('backup generator', 'máy phát dự phòng', '/ˈbækʌp ˈdʒenəreɪtər/', 'Start the backup generator.', 'toeic'),
('city tour', 'tham quan thành phố', '/ˈsɪti tʊr/', 'A free morning city tour.', 'toeic'),
('day trip', 'đi trong ngày', '/ˈdeɪ trɪp/', 'Plan a beach day trip.', 'toeic'),
('overnight', 'qua đêm', '/ˌoʊvərˈnaɪt/', 'An overnight bus ride.', 'toeic'),
('red-eye', 'chuyến đêm', '/ˈred aɪ/', 'Catch the cheap red-eye.', 'toeic'),
('window seat', 'ghế cửa sổ', '/ˈwɪndoʊ siːt/', 'I prefer a window seat.', 'toeic'),
('middle seat', 'ghế giữa', '/ˈmɪdl siːt/', 'Stuck in a middle seat.', 'toeic'),
('legroom', 'chỗ chân', '/ˈleɡruːm/', 'Extra legroom costs more.', 'toeic'),
('recline', 'ngả ghế', '/rɪˈklaɪn/', 'Do not recline fully.', 'toeic'),
('armrest', 'tay vịn', '/ˈɑːrmrest/', 'Share the small armrest.', 'toeic'),
('blanket', 'chăn', '/ˈblæŋkɪt/', 'Ask for a warm blanket.', 'toeic'),
('pillow', 'gối', '/ˈpɪloʊ/', 'A soft neck pillow.', 'toeic'),
('eye mask', 'bịt mắt', '/ˈaɪ mæsk/', 'Wear a dark eye mask.', 'toeic'),
('earplug', 'nút tai', '/ˈɪrplʌɡ/', 'Pack foam earplugs.', 'toeic'),
('adapter', 'đầu chuyển', '/əˈdæptər/', 'Bring a world adapter.', 'toeic'),
('converter', 'bộ đổi điện', '/kənˈvɜːrtər/', 'Need a power converter.', 'toeic'),
('roaming', 'chuyển vùng', '/ˈroʊmɪŋ/', 'Turn off data roaming.', 'toeic'),
('sim card', 'sim', '/ˈsɪm kɑːrd/', 'Buy a local sim card.', 'toeic'),
('currency', 'tiền tệ', '/ˈkɜːrənsi/', 'Exchange some local currency.', 'toeic')
ON CONFLICT (en) DO NOTHING;
