-- TOEIC vocabulary decks batch 8 (100 tu ban hang + marketing + san xuat + dich vu).

INSERT INTO words (en, vi, ipa, example, topic) VALUES
('pitch', 'chào hàng', '/pɪtʃ/', 'Nail the sales pitch.', 'toeic'),
('demo', 'dùng thử', '/ˈdemoʊ/', 'Book a live demo.', 'toeic'),
('trial', 'dùng thử', '/ˈtraɪəl/', 'Start a free trial.', 'toeic'),
('sample', 'mẫu', '/ˈsæmpəl/', 'Request free samples.', 'toeic'),
('rebate', 'hoàn tiền', '/ˈriːbeɪt/', 'Claim a $20 rebate.', 'toeic'),
('bundle', 'gói combo', '/ˈbʌndəl/', 'Buy the family bundle.', 'toeic'),
('upsell', 'bán nâng cấp', '/ˌʌpˈsel/', 'Upsell with care daily.', 'toeic'),
('close', 'chốt sale', '/kloʊz/', 'Close the deal today.', 'toeic'),
('lead', 'khách tiềm năng', '/liːd/', 'Chase every warm lead.', 'toeic'),
('prospect', 'khách triển vọng', '/ˈprɑːspekt/', 'Call each new prospect.', 'toeic'),
('pipeline', 'quy trình bán', '/ˈpaɪplaɪn/', 'Fill the sales pipeline.', 'toeic'),
('funnel', 'phễu', '/ˈfʌnl/', 'Fix the leaky funnel.', 'toeic'),
('conversion', 'chuyển đổi', '/kənˈvɜːrʒən/', 'Boost online conversion.', 'toeic'),
('churn', 'rời bỏ', '/tʃɜːrn/', 'Cut monthly churn fast.', 'toeic'),
('retention', 'giữ chân', '/rɪˈtenʃən/', 'Focus on user retention.', 'toeic'),
('loyalty', 'trung thành', '/ˈlɔɪəlti/', 'Reward loyal shoppers.', 'toeic'),
('referral', 'giới thiệu', '/rɪˈfɜːrəl/', 'Earn referral bonuses.', 'toeic'),
('testimonial', 'lời chứng thực', '/ˌtestɪˈmoʊniəl/', 'Post fresh testimonials.', 'toeic'),
('rating', 'đánh giá', '/ˈreɪtɪŋ/', 'Keep a five-star rating.', 'toeic'),
('unboxing', 'đập hộp', '/ʌnˈbɑːksɪŋ/', 'Film a fun unboxing.', 'toeic'),
('influencer', 'người ảnh hưởng', '/ˈɪnfluənsər/', 'Partner with local influencers.', 'toeic'),
('campaign', 'chiến dịch', '/kæmˈpeɪn/', 'Launch the spring campaign.', 'toeic'),
('rollout', 'triển khai', '/ˈroʊlaʊt/', 'A nationwide product rollout.', 'toeic'),
('teaser', 'nhá hàng', '/ˈtiːzər/', 'Drop a short teaser.', 'toeic'),
('reveal', 'ra mắt', '/rɪˈviːl/', 'The big reveal wowed crowds.', 'toeic'),
('rebrand', 'đổi thương hiệu', '/ˌriːˈbrænd/', 'Rebrand the old chain.', 'toeic'),
('tagline', 'khẩu hiệu', '/ˈtæɡlaɪn/', 'A catchy new tagline.', 'toeic'),
('jingle', 'nhạc hiệu', '/ˈdʒɪŋɡəl/', 'Hum the famous jingle.', 'toeic'),
('mascot', 'linh vật', '/ˈmæskɑːt/', 'Meet our cute mascot.', 'toeic'),
('identity', 'nhận diện', '/aɪˈdentəti/', 'Refresh brand identity.', 'toeic'),
('guideline', 'hướng dẫn', '/ˈɡaɪdlaɪn/', 'Follow brand guidelines.', 'toeic'),
('trademark', 'thương hiệu', '/ˈtreɪdmɑːrk/', 'Register the new trademark.', 'toeic'),
('copyright', 'bản quyền', '/ˈkɑːpiraɪt/', 'Respect photo copyright.', 'toeic'),
('patent', 'bằng sáng chế', '/ˈpætnt/', 'File a fresh patent.', 'toeic'),
('promo', 'khuyến mãi', '/ˈproʊmoʊ/', 'Catch the weekend promo.', 'toeic'),
('blitz', 'đợt dồn dập', '/blɪts/', 'An ad blitz downtown.', 'toeic'),
('roadshow', 'lưu diễn', '/ˈroʊdʃoʊ/', 'Join the product roadshow.', 'toeic'),
('pop-up', 'cửa hàng tạm', '/ˈpɑːp ʌp/', 'Shop the holiday pop-up.', 'toeic'),
('flagship', 'chủ lực', '/ˈflæɡʃɪp/', 'Our flagship store shines.', 'toeic'),
('foot traffic', 'lượt khách', '/ˈfʊt ˈtræfɪk/', 'Boost mall foot traffic.', 'toeic'),
('dwell', 'nán lại', '/dwel/', 'Shoppers dwell longer here.', 'toeic'),
('bounce', 'thoát trang', '/baʊns/', 'Cut the high bounce rate.', 'toeic'),
('impression', 'lượt hiển thị', '/ɪmˈpreʃən/', 'Buy a million impressions.', 'toeic'),
('reach', 'tiếp cận', '/riːtʃ/', 'Expand our global reach.', 'toeic'),
('engagement', 'tương tác', '/ɪnˈɡeɪdʒmənt/', 'Drive more post engagement.', 'toeic'),
('viral', 'lan truyền', '/ˈvaɪrəl/', 'Go viral overnight.', 'toeic'),
('trend', 'xu hướng', '/trend/', 'Ride the new trend.', 'toeic'),
('hashtag', 'hashtag', '/ˈhæʃtæɡ/', 'Add one event hashtag.', 'toeic'),
('mention', 'nhắc đến', '/ˈmenʃən/', 'Thanks for the mention.', 'toeic'),
('subscriber', 'người đăng ký', '/səbˈskraɪbər/', 'Gain ten thousand subscribers.', 'toeic'),
('follower', 'người theo dõi', '/ˈfɑːloʊər/', 'Thank new followers daily.', 'toeic'),
('install', 'cài đặt', '/ɪnˈstɔːl/', 'Install the update now.', 'toeic'),
('signup', 'đăng ký', '/ˈsaɪnʌp/', 'Finish signup in minutes.', 'toeic'),
('freemium', 'miễn phí cơ bản', '/ˈfriːmiəm/', 'Try our freemium plan.', 'toeic'),
('paywall', 'tường phí', '/ˈpeɪwɔːl/', 'Hit the monthly paywall.', 'toeic'),
('assembly line', 'dây chuyền', '/əˈsembli laɪn/', 'Stop the whole assembly line.', 'toeic'),
('conveyor', 'băng tải', '/kənˈveɪər/', 'Fix the loud conveyor.', 'toeic'),
('output', 'sản lượng', '/ˈaʊtpʊt/', 'Double factory output.', 'toeic'),
('throughput', 'thông lượng', '/ˈθruːpʊt/', 'Raise daily throughput.', 'toeic'),
('downtime', 'ngừng máy', '/ˈdaʊntaɪm/', 'Cut weekend downtime.', 'toeic'),
('uptime', 'thời gian chạy', '/ˈʌptaɪm/', 'Guarantee 99% uptime.', 'toeic'),
('preventive', 'phòng ngừa', '/prɪˈventɪv/', 'Schedule preventive care.', 'toeic'),
('breakdown', 'hỏng', '/ˈbreɪkdaʊn/', 'Report any van breakdown.', 'toeic'),
('malfunction', 'trục trặc', '/ˌmælˈfʌŋkʃən/', 'A sensor malfunction halted work.', 'toeic'),
('glitch', 'lỗi nhỏ', '/ɡlɪtʃ/', 'A brief software glitch.', 'toeic'),
('defect', 'lỗi', '/ˈdiːfekt/', 'Zero defects this month.', 'toeic'),
('flaw', 'khuyết điểm', '/flɔː/', 'No visible flaws found.', 'toeic'),
('rework', 'làm lại', '/ˌriːˈwɜːrk/', 'Rework faulty batches fast.', 'toeic'),
('scrap', 'phế liệu', '/skræp/', 'Sell metal scrap weekly.', 'toeic'),
('lean', 'tinh gọn', '/liːn/', 'Adopt lean methods.', 'toeic'),
('batch', 'mẻ', '/bætʃ/', 'Mix a fresh paint batch.', 'toeic'),
('backlog', 'tồn đọng', '/ˈbækloʊɡ/', 'Clear the order backlog.', 'toeic'),
('fulfillment', 'hoàn tất đơn', '/fʊlˈfɪlmənt/', 'Speed up order fulfillment.', 'toeic'),
('inspection', 'kiểm tra', '/ɪnˈspekʃən/', 'Pass the safety inspection.', 'toeic'),
('certify', 'chứng nhận', '/ˈsɜːrtɪfaɪ/', 'Certify each new welder.', 'toeic'),
('comply', 'tuân thủ', '/kəmˈplaɪ/', 'Comply with new rules.', 'toeic'),
('violation', 'vi phạm', '/ˌvaɪəˈleɪʃən/', 'Fix every code violation.', 'toeic'),
('shutdown', 'dừng', '/ˈʃʌtdaʊn/', 'Plan a Sunday shutdown.', 'toeic'),
('ramp up', 'tăng tốc', '/ˈræmp ʌp/', 'Ramp up holiday hiring.', 'toeic'),
('pilot', 'thí điểm', '/ˈpaɪlət/', 'Pilot the scheme downtown.', 'toeic'),
('calibrate', 'hiệu chuẩn', '/ˈkæləbreɪt/', 'Calibrate scales monthly.', 'toeic'),
('troubleshoot', 'khắc phục', '/ˈtrʌblʃuːt/', 'Troubleshoot login errors.', 'toeic'),
('diagnose', 'chẩn đoán', '/ˈdaɪəɡnoʊs/', 'Diagnose engine noise fast.', 'toeic'),
('overhaul', 'đại tu', '/ˌoʊvərˈhɔːl/', 'Overhaul old elevators.', 'toeic'),
('retrofit', 'cải tạo', '/ˈretroʊfɪt/', 'Retrofit with LED lights.', 'toeic'),
('patch', 'bản vá', '/pætʃ/', 'Install the urgent patch.', 'toeic'),
('reboot', 'khởi động lại', '/ˌriːˈbuːt/', 'Reboot the frozen till.', 'toeic'),
('reset', 'đặt lại', '/ˌriːˈset/', 'Reset your password now.', 'toeic'),
('restore', 'khôi phục', '/rɪˈstɔːr/', 'Restore deleted files.', 'toeic'),
('migrate', 'di chuyển', '/ˈmaɪɡreɪt/', 'Migrate data overnight.', 'toeic'),
('deploy', 'triển khai', '/dɪˈplɔɪ/', 'Deploy the fix today.', 'toeic'),
('monitor', 'giám sát', '/ˈmɑːnɪtər/', 'Monitor server loads.', 'toeic'),
('alert', 'cảnh báo', '/əˈlɜːrt/', 'Get instant fraud alerts.', 'toeic'),
('dashboard', 'bảng điều khiển', '/ˈdæʃbɔːrd/', 'Check the sales dashboard.', 'toeic'),
('metric', 'chỉ số', '/ˈmetrɪk/', 'Track one key metric.', 'toeic'),
('benchmark', 'chuẩn', '/ˈbentʃmɑːrk/', 'Beat the industry benchmark.', 'toeic'),
('variance', 'chênh lệch', '/ˈveriəns/', 'Explain budget variance.', 'toeic'),
('deviation', 'độ lệch', '/ˌdiːviˈeɪʃən/', 'Flag large deviations fast.', 'toeic'),
('tolerance', 'dung sai', '/ˈtɑːlərəns/', 'Within allowed tolerance.', 'toeic'),
('spec', 'thông số', '/spek/', 'Meet every design spec.', 'toeic')
ON CONFLICT (en) DO NOTHING;
